// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module deepwaveaccel_crosscor (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_goertzel_dout,
        s_goertzel_empty_n,
        s_goertzel_read,
        s_goertzel_num_data_valid,
        s_goertzel_fifo_cap,
        s_xcor_din,
        s_xcor_full_n,
        s_xcor_write,
        s_xcor_num_data_valid,
        s_xcor_fifo_cap,
        s_norm_din,
        s_norm_full_n,
        s_norm_write,
        s_norm_num_data_valid,
        s_norm_fifo_cap,
        status_cc_state,
        status_cc_state_ap_vld,
        status_cc_samples_in,
        status_cc_samples_in_ap_vld,
        status_cc_samples_out,
        status_cc_samples_out_ap_vld,
        status_cc_sample_idx,
        status_cc_sample_idx_ap_vld,
        status_cc_current_norm,
        status_cc_current_norm_ap_vld,
        status_cc_norms_written,
        status_cc_norms_written_ap_vld,
        status_cc_out_fifo,
        status_cc_out_fifo_ap_vld,
        status_cc_norms_fifo,
        status_cc_norms_fifo_ap_vld
);

parameter    ap_ST_fsm_state1 = 91'd1;
parameter    ap_ST_fsm_state2 = 91'd2;
parameter    ap_ST_fsm_state3 = 91'd4;
parameter    ap_ST_fsm_state4 = 91'd8;
parameter    ap_ST_fsm_state5 = 91'd16;
parameter    ap_ST_fsm_state6 = 91'd32;
parameter    ap_ST_fsm_state7 = 91'd64;
parameter    ap_ST_fsm_state8 = 91'd128;
parameter    ap_ST_fsm_state9 = 91'd256;
parameter    ap_ST_fsm_state10 = 91'd512;
parameter    ap_ST_fsm_state11 = 91'd1024;
parameter    ap_ST_fsm_state12 = 91'd2048;
parameter    ap_ST_fsm_state13 = 91'd4096;
parameter    ap_ST_fsm_state14 = 91'd8192;
parameter    ap_ST_fsm_state15 = 91'd16384;
parameter    ap_ST_fsm_state16 = 91'd32768;
parameter    ap_ST_fsm_state17 = 91'd65536;
parameter    ap_ST_fsm_state18 = 91'd131072;
parameter    ap_ST_fsm_state19 = 91'd262144;
parameter    ap_ST_fsm_state20 = 91'd524288;
parameter    ap_ST_fsm_state21 = 91'd1048576;
parameter    ap_ST_fsm_state22 = 91'd2097152;
parameter    ap_ST_fsm_state23 = 91'd4194304;
parameter    ap_ST_fsm_state24 = 91'd8388608;
parameter    ap_ST_fsm_state25 = 91'd16777216;
parameter    ap_ST_fsm_state26 = 91'd33554432;
parameter    ap_ST_fsm_state27 = 91'd67108864;
parameter    ap_ST_fsm_state28 = 91'd134217728;
parameter    ap_ST_fsm_state29 = 91'd268435456;
parameter    ap_ST_fsm_state30 = 91'd536870912;
parameter    ap_ST_fsm_state31 = 91'd1073741824;
parameter    ap_ST_fsm_state32 = 91'd2147483648;
parameter    ap_ST_fsm_state33 = 91'd4294967296;
parameter    ap_ST_fsm_state34 = 91'd8589934592;
parameter    ap_ST_fsm_state35 = 91'd17179869184;
parameter    ap_ST_fsm_state36 = 91'd34359738368;
parameter    ap_ST_fsm_state37 = 91'd68719476736;
parameter    ap_ST_fsm_state38 = 91'd137438953472;
parameter    ap_ST_fsm_state39 = 91'd274877906944;
parameter    ap_ST_fsm_state40 = 91'd549755813888;
parameter    ap_ST_fsm_state41 = 91'd1099511627776;
parameter    ap_ST_fsm_state42 = 91'd2199023255552;
parameter    ap_ST_fsm_state43 = 91'd4398046511104;
parameter    ap_ST_fsm_state44 = 91'd8796093022208;
parameter    ap_ST_fsm_state45 = 91'd17592186044416;
parameter    ap_ST_fsm_state46 = 91'd35184372088832;
parameter    ap_ST_fsm_state47 = 91'd70368744177664;
parameter    ap_ST_fsm_state48 = 91'd140737488355328;
parameter    ap_ST_fsm_state49 = 91'd281474976710656;
parameter    ap_ST_fsm_state50 = 91'd562949953421312;
parameter    ap_ST_fsm_state51 = 91'd1125899906842624;
parameter    ap_ST_fsm_state52 = 91'd2251799813685248;
parameter    ap_ST_fsm_state53 = 91'd4503599627370496;
parameter    ap_ST_fsm_state54 = 91'd9007199254740992;
parameter    ap_ST_fsm_state55 = 91'd18014398509481984;
parameter    ap_ST_fsm_state56 = 91'd36028797018963968;
parameter    ap_ST_fsm_state57 = 91'd72057594037927936;
parameter    ap_ST_fsm_state58 = 91'd144115188075855872;
parameter    ap_ST_fsm_state59 = 91'd288230376151711744;
parameter    ap_ST_fsm_state60 = 91'd576460752303423488;
parameter    ap_ST_fsm_state61 = 91'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 91'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 91'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 91'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 91'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 91'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 91'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 91'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 91'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 91'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 91'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 91'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 91'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 91'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 91'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 91'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 91'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 91'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 91'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 91'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 91'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 91'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 91'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 91'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 91'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 91'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 91'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 91'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 91'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 91'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 91'd1237940039285380274899124224;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [35:0] s_goertzel_dout;
input   s_goertzel_empty_n;
output   s_goertzel_read;
input  [6:0] s_goertzel_num_data_valid;
input  [6:0] s_goertzel_fifo_cap;
output  [35:0] s_xcor_din;
input   s_xcor_full_n;
output   s_xcor_write;
input  [11:0] s_xcor_num_data_valid;
input  [11:0] s_xcor_fifo_cap;
output  [24:0] s_norm_din;
input   s_norm_full_n;
output   s_norm_write;
input  [2:0] s_norm_num_data_valid;
input  [2:0] s_norm_fifo_cap;
output  [7:0] status_cc_state;
output   status_cc_state_ap_vld;
output  [31:0] status_cc_samples_in;
output   status_cc_samples_in_ap_vld;
output  [31:0] status_cc_samples_out;
output   status_cc_samples_out_ap_vld;
output  [31:0] status_cc_sample_idx;
output   status_cc_sample_idx_ap_vld;
output  [31:0] status_cc_current_norm;
output   status_cc_current_norm_ap_vld;
output  [31:0] status_cc_norms_written;
output   status_cc_norms_written_ap_vld;
output  [31:0] status_cc_out_fifo;
output   status_cc_out_fifo_ap_vld;
output  [31:0] status_cc_norms_fifo;
output   status_cc_norms_fifo_ap_vld;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_goertzel_read;
reg s_xcor_write;
reg s_norm_write;
reg[7:0] status_cc_state;
reg status_cc_state_ap_vld;
reg[31:0] status_cc_samples_in;
reg status_cc_samples_in_ap_vld;
reg[31:0] status_cc_samples_out;
reg status_cc_samples_out_ap_vld;
reg[31:0] status_cc_sample_idx;
reg status_cc_sample_idx_ap_vld;
reg[31:0] status_cc_current_norm;
reg status_cc_current_norm_ap_vld;
reg[31:0] status_cc_norms_written;
reg status_cc_norms_written_ap_vld;
reg[31:0] status_cc_out_fifo;
reg status_cc_out_fifo_ap_vld;
reg[31:0] status_cc_norms_fifo;
reg status_cc_norms_fifo_ap_vld;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [90:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [1:0] st_1;
reg   [31:0] pair_idx;
reg   [31:0] samples_in_1;
reg   [31:0] v_count;
wire   [17:0] u_M_real_q0;
wire   [17:0] u_M_real_q1;
wire   [17:0] u_M_imag_q0;
wire   [17:0] u_M_imag_d1;
wire   [17:0] u_M_imag_q1;
reg   [0:0] phase;
reg   [31:0] diag_i;
reg   [31:0] frames_acc;
reg   [35:0] power_acc;
reg   [31:0] norms_written;
reg   [23:0] scale;
reg   [31:0] k_1;
reg   [31:0] j;
wire   [10:0] R_flat_M_real_address0;
wire   [35:0] R_flat_M_real_q0;
wire   [35:0] R_flat_M_real_q1;
wire   [10:0] R_flat_M_imag_address0;
wire   [35:0] R_flat_M_imag_q0;
wire   [35:0] R_flat_M_imag_q1;
reg   [31:0] samples_out_1;
reg    s_goertzel_blk_n;
wire    ap_CS_fsm_state91;
reg    s_xcor_blk_n;
wire    ap_CS_fsm_state48;
reg    s_norm_blk_n;
wire    ap_CS_fsm_state3;
wire   [1:0] st_1_load_load_fu_756_p1;
reg   [1:0] st_1_load_reg_1389;
reg    ap_block_state1;
reg   [31:0] pair_idx_load_reg_1393;
wire   [0:0] phase_load_load_fu_772_p1;
reg   [0:0] phase_load_reg_1399;
wire   [0:0] icmp_ln84_fu_802_p2;
reg   [0:0] icmp_ln84_reg_1416;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln87_fu_893_p2;
reg   [0:0] icmp_ln87_reg_1439;
reg  signed [24:0] trunc_ln1_reg_1443;
wire    ap_CS_fsm_state46;
reg   [10:0] R_flat_M_real_addr_1_reg_1479;
reg   [10:0] R_flat_M_imag_addr_1_reg_1485;
wire   [31:0] add_ln117_fu_1188_p2;
wire    ap_CS_fsm_state47;
wire   [31:0] grp_fu_751_p2;
wire   [31:0] add_ln120_fu_1199_p2;
wire   [1:0] select_ln128_1_fu_1235_p3;
wire   [31:0] add_ln122_fu_1249_p2;
wire    ap_CS_fsm_state90;
wire   [31:0] add_ln62_fu_1359_p2;
reg   [35:0] ap_phi_mux_power_acc_new_0_phi_fu_411_p4;
reg   [35:0] power_acc_new_0_reg_408;
wire    ap_CS_fsm_state45;
reg   [35:0] ap_phi_mux_power_acc_new_1_phi_fu_421_p4;
reg   [35:0] power_acc_new_1_reg_418;
reg   [0:0] ap_phi_mux_v_count_flag_0_phi_fu_433_p18;
reg   [0:0] v_count_flag_0_reg_428;
wire   [0:0] icmp_ln63_fu_1365_p2;
wire   [0:0] tmp_nbreadreq_fu_183_p3;
wire   [0:0] icmp_ln119_fu_1193_p2;
wire   [0:0] icmp_ln121_fu_1204_p2;
wire   [0:0] icmp_ln155_fu_1303_p2;
reg   [31:0] v_count_new_0_reg_462;
reg   [0:0] ap_phi_mux_k_3_flag_0_phi_fu_500_p18;
reg   [0:0] k_3_flag_0_reg_495;
reg   [31:0] k_3_new_0_reg_529;
reg   [0:0] ap_phi_mux_j_flag_0_phi_fu_566_p18;
reg   [0:0] j_flag_0_reg_561;
reg   [31:0] j_new_0_reg_595;
reg   [0:0] ap_phi_mux_pair_idx_flag_0_phi_fu_633_p18;
reg   [0:0] pair_idx_flag_0_reg_628;
reg   [31:0] pair_idx_new_0_reg_662;
reg   [1:0] ap_phi_mux_phi_ln164_phi_fu_699_p18;
reg   [1:0] phi_ln164_reg_693;
wire   [63:0] zext_ln79_fu_784_p1;
wire   [63:0] zext_ln143_fu_808_p1;
wire   [63:0] zext_ln109_fu_1049_p1;
wire   [63:0] zext_ln111_fu_1059_p1;
wire   [63:0] zext_ln113_fu_1065_p1;
wire   [63:0] zext_ln61_fu_1353_p1;
wire   [31:0] add_ln58_fu_1319_p2;
wire   [31:0] add_ln83_fu_790_p2;
wire   [31:0] select_ln128_fu_1221_p3;
wire   [31:0] add_ln94_fu_912_p2;
wire   [23:0] trunc_ln97_fu_994_p1;
wire   [31:0] add_ln151_fu_818_p2;
reg   [31:0] status_cc_samples_out_preg;
reg   [31:0] status_cc_norms_written_preg;
wire   [24:0] corrected_2_fu_934_p4;
wire   [31:0] zext_ln92_fu_955_p1;
reg   [31:0] status_cc_current_norm_preg;
reg   [31:0] status_cc_norms_fifo_preg;
wire   [7:0] zext_ln164_fu_1016_p1;
reg   [7:0] status_cc_state_preg;
reg   [31:0] status_cc_out_fifo_preg;
reg   [31:0] status_cc_samples_in_preg;
reg   [31:0] status_cc_sample_idx_preg;
reg    u_M_real_ce0_local;
reg   [5:0] u_M_real_address0_local;
reg    u_M_real_ce1_local;
reg   [5:0] u_M_real_address1_local;
reg    u_M_real_we1_local;
wire   [17:0] w_re_fu_1337_p1;
reg    u_M_imag_ce0_local;
reg   [5:0] u_M_imag_address0_local;
reg    u_M_imag_ce1_local;
reg   [5:0] u_M_imag_address1_local;
reg    u_M_imag_we1_local;
reg    R_flat_M_real_ce1_local;
reg   [10:0] R_flat_M_real_address1_local;
reg    R_flat_M_real_we1_local;
reg   [35:0] R_flat_M_real_d1_local;
reg    R_flat_M_real_ce0_local;
reg    R_flat_M_imag_ce1_local;
reg   [10:0] R_flat_M_imag_address1_local;
reg    R_flat_M_imag_we1_local;
reg   [35:0] R_flat_M_imag_d1_local;
reg    R_flat_M_imag_ce0_local;
reg  signed [30:0] grp_fu_727_p0;
wire  signed [61:0] sext_ln81_fu_847_p1;
wire  signed [61:0] sext_ln113_1_fu_1108_p1;
reg  signed [30:0] grp_fu_727_p1;
wire  signed [61:0] sext_ln113_fu_1102_p1;
reg  signed [30:0] grp_fu_731_p0;
wire  signed [61:0] sext_ln81_1_fu_853_p1;
wire  signed [61:0] sext_ln113_3_fu_1120_p1;
reg  signed [30:0] grp_fu_731_p1;
wire  signed [61:0] sext_ln113_2_fu_1114_p1;
wire   [23:0] mul_ln146_fu_743_p1;
wire   [53:0] zext_ln146_fu_1263_p1;
wire   [23:0] mul_ln147_fu_747_p1;
wire   [30:0] ur_fu_831_p3;
wire   [30:0] ui_fu_839_p3;
wire   [61:0] grp_fu_727_p2;
wire   [61:0] shl_ln1_fu_863_p3;
wire   [61:0] add_ln81_fu_871_p2;
wire   [61:0] grp_fu_731_p2;
wire   [61:0] add_ln81_1_fu_877_p2;
wire   [15:0] mul_ln89_fu_928_p1;
wire   [39:0] mul_ln89_fu_928_p2;
wire   [9:0] tmp_5_fu_960_p4;
wire   [0:0] icmp_ln96_fu_970_p2;
wire   [23:0] trunc_ln89_2_fu_945_p4;
wire   [23:0] corrected_fu_976_p3;
wire   [23:0] grp_fu_988_p1;
wire   [23:0] grp_fu_988_p2;
wire  signed [30:0] re1_fu_1070_p3;
wire  signed [30:0] re2_fu_1086_p3;
wire  signed [30:0] im1_fu_1078_p3;
wire  signed [30:0] im2_fu_1094_p3;
wire   [61:0] shl_ln_fu_1126_p3;
wire   [61:0] add_ln113_fu_1134_p2;
wire   [61:0] add_ln113_1_fu_1140_p2;
wire   [61:0] mul_ln114_fu_735_p2;
wire   [61:0] mul_ln114_1_fu_739_p2;
wire   [61:0] sub_ln114_fu_1157_p2;
wire   [61:0] shl_ln9_fu_1163_p3;
wire   [61:0] add_ln114_fu_1171_p2;
wire   [31:0] add_ln127_fu_1210_p2;
wire   [0:0] icmp_ln128_fu_1215_p2;
wire  signed [35:0] sext_ln146_fu_1254_p0;
wire   [53:0] mul_ln146_fu_743_p2;
wire  signed [35:0] sext_ln147_fu_1279_p0;
wire   [53:0] mul_ln147_fu_747_p2;
wire   [17:0] out_im_fu_1284_p4;
wire   [17:0] out_re_fu_1269_p4;
reg    grp_fu_988_ap_start;
wire    grp_fu_988_ap_done;
reg    grp_fu_988_ce;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
reg   [90:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
reg    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
reg    ap_ST_fsm_state91_blk;
wire   [38:0] grp_fu_988_p10;
reg    ap_condition_1509;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 91'd1;
#0 st_1 = 2'd0;
#0 pair_idx = 32'd0;
#0 samples_in_1 = 32'd0;
#0 v_count = 32'd0;
#0 phase = 1'd0;
#0 diag_i = 32'd0;
#0 frames_acc = 32'd0;
#0 power_acc = 36'd0;
#0 norms_written = 32'd0;
#0 scale = 24'd0;
#0 k_1 = 32'd1;
#0 j = 32'd0;
#0 samples_out_1 = 32'd0;
#0 status_cc_samples_out_preg = 32'd0;
#0 status_cc_norms_written_preg = 32'd0;
#0 status_cc_current_norm_preg = 32'd0;
#0 status_cc_norms_fifo_preg = 32'd0;
#0 status_cc_state_preg = 8'd0;
#0 status_cc_out_fifo_preg = 32'd0;
#0 status_cc_samples_in_preg = 32'd0;
#0 status_cc_sample_idx_preg = 32'd0;
end

deepwaveaccel_crosscor_u_M_real_RAM_2P_BRAM_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
u_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(u_M_real_address0_local),
    .ce0(u_M_real_ce0_local),
    .q0(u_M_real_q0),
    .address1(u_M_real_address1_local),
    .ce1(u_M_real_ce1_local),
    .we1(u_M_real_we1_local),
    .d1(w_re_fu_1337_p1),
    .q1(u_M_real_q1)
);

deepwaveaccel_crosscor_u_M_real_RAM_2P_BRAM_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
u_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(u_M_imag_address0_local),
    .ce0(u_M_imag_ce0_local),
    .q0(u_M_imag_q0),
    .address1(u_M_imag_address1_local),
    .ce1(u_M_imag_ce1_local),
    .we1(u_M_imag_we1_local),
    .d1(u_M_imag_d1),
    .q1(u_M_imag_q1)
);

deepwaveaccel_crosscor_R_flat_M_real_RAM_2P_BRAM_1R1W #(
    .DataWidth( 36 ),
    .AddressRange( 1128 ),
    .AddressWidth( 11 ))
R_flat_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(R_flat_M_real_address0),
    .ce0(R_flat_M_real_ce0_local),
    .q0(R_flat_M_real_q0),
    .address1(R_flat_M_real_address1_local),
    .ce1(R_flat_M_real_ce1_local),
    .we1(R_flat_M_real_we1_local),
    .d1(R_flat_M_real_d1_local),
    .q1(R_flat_M_real_q1)
);

deepwaveaccel_crosscor_R_flat_M_real_RAM_2P_BRAM_1R1W #(
    .DataWidth( 36 ),
    .AddressRange( 1128 ),
    .AddressWidth( 11 ))
R_flat_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(R_flat_M_imag_address0),
    .ce0(R_flat_M_imag_ce0_local),
    .q0(R_flat_M_imag_q0),
    .address1(R_flat_M_imag_address1_local),
    .ce1(R_flat_M_imag_ce1_local),
    .we1(R_flat_M_imag_we1_local),
    .d1(R_flat_M_imag_d1_local),
    .q1(R_flat_M_imag_q1)
);

deepwaveaccel_mul_31s_31s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31s_31s_62_1_1_U29(
    .din0(grp_fu_727_p0),
    .din1(grp_fu_727_p1),
    .dout(grp_fu_727_p2)
);

deepwaveaccel_mul_31s_31s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31s_31s_62_1_1_U30(
    .din0(grp_fu_731_p0),
    .din1(grp_fu_731_p1),
    .dout(grp_fu_731_p2)
);

deepwaveaccel_mul_31s_31s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31s_31s_62_1_1_U31(
    .din0(im2_fu_1094_p3),
    .din1(re1_fu_1070_p3),
    .dout(mul_ln114_fu_735_p2)
);

deepwaveaccel_mul_31s_31s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31s_31s_62_1_1_U32(
    .din0(re2_fu_1086_p3),
    .din1(im1_fu_1078_p3),
    .dout(mul_ln114_1_fu_739_p2)
);

deepwaveaccel_mul_36s_24ns_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 54 ))
mul_36s_24ns_54_1_1_U33(
    .din0(sext_ln146_fu_1254_p0),
    .din1(mul_ln146_fu_743_p1),
    .dout(mul_ln146_fu_743_p2)
);

deepwaveaccel_mul_36s_24ns_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 54 ))
mul_36s_24ns_54_1_1_U34(
    .din0(sext_ln147_fu_1279_p0),
    .din1(mul_ln147_fu_747_p1),
    .dout(mul_ln147_fu_747_p2)
);

deepwaveaccel_mul_25s_16ns_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
mul_25s_16ns_40_1_1_U35(
    .din0(trunc_ln1_reg_1443),
    .din1(mul_ln89_fu_928_p1),
    .dout(mul_ln89_fu_928_p2)
);

deepwaveaccel_udiv_39s_24ns_24_43_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 43 ),
    .din0_WIDTH( 39 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
udiv_39s_24ns_24_43_seq_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_988_ap_start),
    .done(grp_fu_988_ap_done),
    .din0(39'd274877906944),
    .din1(grp_fu_988_p1),
    .ce(grp_fu_988_ce),
    .dout(grp_fu_988_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state45)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                status_cc_current_norm_preg[0] <= 1'b0;
        status_cc_current_norm_preg[1] <= 1'b0;
        status_cc_current_norm_preg[2] <= 1'b0;
        status_cc_current_norm_preg[3] <= 1'b0;
        status_cc_current_norm_preg[4] <= 1'b0;
        status_cc_current_norm_preg[5] <= 1'b0;
        status_cc_current_norm_preg[6] <= 1'b0;
        status_cc_current_norm_preg[7] <= 1'b0;
        status_cc_current_norm_preg[8] <= 1'b0;
        status_cc_current_norm_preg[9] <= 1'b0;
        status_cc_current_norm_preg[10] <= 1'b0;
        status_cc_current_norm_preg[11] <= 1'b0;
        status_cc_current_norm_preg[12] <= 1'b0;
        status_cc_current_norm_preg[13] <= 1'b0;
        status_cc_current_norm_preg[14] <= 1'b0;
        status_cc_current_norm_preg[15] <= 1'b0;
        status_cc_current_norm_preg[16] <= 1'b0;
        status_cc_current_norm_preg[17] <= 1'b0;
        status_cc_current_norm_preg[18] <= 1'b0;
        status_cc_current_norm_preg[19] <= 1'b0;
        status_cc_current_norm_preg[20] <= 1'b0;
        status_cc_current_norm_preg[21] <= 1'b0;
        status_cc_current_norm_preg[22] <= 1'b0;
        status_cc_current_norm_preg[23] <= 1'b0;
        status_cc_current_norm_preg[24] <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
                        status_cc_current_norm_preg[24 : 0] <= zext_ln92_fu_955_p1[24 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_norms_fifo_preg <= 32'd0;
    end else begin
        if (((icmp_ln87_reg_1439 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
            status_cc_norms_fifo_preg <= s_norm_num_data_valid;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_norms_written_preg <= 32'd0;
    end else begin
        if (((icmp_ln87_fu_893_p2 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            status_cc_norms_written_preg <= add_ln94_fu_912_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_out_fifo_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state90)) begin
            status_cc_out_fifo_preg <= s_xcor_num_data_valid;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_sample_idx_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
            status_cc_sample_idx_preg <= v_count;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_samples_in_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
            status_cc_samples_in_preg <= add_ln58_fu_1319_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        status_cc_samples_out_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
            status_cc_samples_out_preg <= add_ln151_fu_818_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                status_cc_state_preg[0] <= 1'b0;
        status_cc_state_preg[1] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state45)) begin
                        status_cc_state_preg[1 : 0] <= zext_ln164_fu_1016_p1[1 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((phase_load_load_fu_772_p1 == 1'd0) & (1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        diag_i <= add_ln83_fu_790_p2;
    end else if (((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        diag_i <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)))) begin
        j_flag_0_reg_561 <= 1'd1;
    end else if ((((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | (~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln63_fu_1365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45)))) begin
        j_flag_0_reg_561 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        if ((icmp_ln121_fu_1204_p2 == 1'd0)) begin
            j_new_0_reg_595 <= 32'd0;
        end else if ((icmp_ln121_fu_1204_p2 == 1'd1)) begin
            j_new_0_reg_595 <= add_ln120_fu_1199_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)))) begin
        k_3_flag_0_reg_495 <= 1'd1;
    end else if ((((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | (~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln63_fu_1365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45)))) begin
        k_3_flag_0_reg_495 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        if ((icmp_ln119_fu_1193_p2 == 1'd0)) begin
            k_3_new_0_reg_529 <= add_ln117_fu_1188_p2;
        end else if (((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1))) begin
            k_3_new_0_reg_529 <= 32'd1;
        end else if (((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1))) begin
            k_3_new_0_reg_529 <= add_ln122_fu_1249_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)))) begin
        pair_idx_flag_0_reg_628 <= 1'd1;
    end else if (((~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln63_fu_1365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45)))) begin
        pair_idx_flag_0_reg_628 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)))) begin
        pair_idx_new_0_reg_662 <= 32'd0;
    end else if ((((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)))) begin
        pair_idx_new_0_reg_662 <= grp_fu_751_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        phase <= 1'd1;
    end else if (((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        phase <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90))) begin
        phi_ln164_reg_693 <= 2'd2;
    end else if (((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        phi_ln164_reg_693 <= select_ln128_1_fu_1235_p3;
    end else if ((((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | (~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln63_fu_1365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)))) begin
        phi_ln164_reg_693 <= 2'd0;
    end else if ((((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45)))) begin
        phi_ln164_reg_693 <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((icmp_ln84_reg_1416 == 1'd1)) begin
        if (((icmp_ln87_fu_893_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            power_acc_new_0_reg_408 <= {{add_ln81_1_fu_877_p2[61:26]}};
        end else if ((1'b1 == ap_condition_1509)) begin
            power_acc_new_0_reg_408 <= 36'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        power_acc_new_1_reg_418 <= ap_phi_mux_power_acc_new_0_phi_fu_411_p4;
    end else if (((icmp_ln84_reg_1416 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        power_acc_new_1_reg_418 <= {{add_ln81_1_fu_877_p2[61:26]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        st_1 <= select_ln128_1_fu_1235_p3;
    end else if (((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90))) begin
        st_1 <= 2'd0;
    end else if (((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        st_1 <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln155_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln155_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state90)) | ((icmp_ln119_fu_1193_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | ((icmp_ln121_fu_1204_p2 == 1'd1) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47)) | (~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45)))) begin
        v_count_flag_0_reg_428 <= 1'd0;
    end else if ((((icmp_ln63_fu_1365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)) | ((icmp_ln63_fu_1365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)))) begin
        v_count_flag_0_reg_428 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        if ((icmp_ln63_fu_1365_p2 == 1'd0)) begin
            v_count_new_0_reg_462 <= add_ln62_fu_1359_p2;
        end else if ((icmp_ln63_fu_1365_p2 == 1'd1)) begin
            v_count_new_0_reg_462 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        R_flat_M_imag_addr_1_reg_1485 <= zext_ln113_fu_1065_p1;
        R_flat_M_real_addr_1_reg_1479 <= zext_ln113_fu_1065_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln121_fu_1204_p2 == 1'd0) & (icmp_ln119_fu_1193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        frames_acc <= select_ln128_fu_1221_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln84_reg_1416 <= icmp_ln84_fu_802_p2;
        pair_idx_load_reg_1393 <= pair_idx;
        phase_load_reg_1399 <= phase;
        st_1_load_reg_1389 <= st_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln87_reg_1439 <= icmp_ln87_fu_893_p2;
        trunc_ln1_reg_1443 <= {{add_ln81_1_fu_877_p2[61:37]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_j_flag_0_phi_fu_566_p18 == 1'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        j <= j_new_0_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_k_3_flag_0_phi_fu_500_p18 == 1'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        k_1 <= k_3_new_0_reg_529;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln87_fu_893_p2 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        norms_written <= add_ln94_fu_912_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_pair_idx_flag_0_phi_fu_633_p18 == 1'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        pair_idx <= pair_idx_new_0_reg_662;
    end
end

always @ (posedge ap_clk) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        power_acc <= ap_phi_mux_power_acc_new_1_phi_fu_421_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        samples_in_1 <= add_ln58_fu_1319_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        samples_out_1 <= add_ln151_fu_818_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln87_reg_1439 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        scale <= trunc_ln97_fu_994_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_v_count_flag_0_phi_fu_433_p18 == 1'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        v_count <= v_count_new_0_reg_462;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        R_flat_M_imag_address1_local = R_flat_M_imag_addr_1_reg_1485;
    end else if (((st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        R_flat_M_imag_address1_local = zext_ln143_fu_808_p1;
    end else begin
        R_flat_M_imag_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        R_flat_M_imag_ce0_local = 1'b1;
    end else begin
        R_flat_M_imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state47) | ((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        R_flat_M_imag_ce1_local = 1'b1;
    end else begin
        R_flat_M_imag_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        R_flat_M_imag_d1_local = {{add_ln114_fu_1171_p2[61:26]}};
    end else if (((st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        R_flat_M_imag_d1_local = 36'd0;
    end else begin
        R_flat_M_imag_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state47) | ((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        R_flat_M_imag_we1_local = 1'b1;
    end else begin
        R_flat_M_imag_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        R_flat_M_real_address1_local = R_flat_M_real_addr_1_reg_1479;
    end else if (((st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        R_flat_M_real_address1_local = zext_ln143_fu_808_p1;
    end else begin
        R_flat_M_real_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        R_flat_M_real_ce0_local = 1'b1;
    end else begin
        R_flat_M_real_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state47) | ((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        R_flat_M_real_ce1_local = 1'b1;
    end else begin
        R_flat_M_real_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        R_flat_M_real_d1_local = {{add_ln113_1_fu_1140_p2[61:26]}};
    end else if (((st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        R_flat_M_real_d1_local = 36'd0;
    end else begin
        R_flat_M_real_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state47) | ((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        R_flat_M_real_we1_local = 1'b1;
    end else begin
        R_flat_M_real_we1_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((s_norm_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

always @ (*) begin
    if ((s_xcor_full_n == 1'b0)) begin
        ap_ST_fsm_state48_blk = 1'b1;
    end else begin
        ap_ST_fsm_state48_blk = 1'b0;
    end
end

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

always @ (*) begin
    if ((s_goertzel_empty_n == 1'b0)) begin
        ap_ST_fsm_state91_blk = 1'b1;
    end else begin
        ap_ST_fsm_state91_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_j_flag_0_phi_fu_566_p18 = 1'd0;
    end else begin
        ap_phi_mux_j_flag_0_phi_fu_566_p18 = j_flag_0_reg_561;
    end
end

always @ (*) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_k_3_flag_0_phi_fu_500_p18 = 1'd0;
    end else begin
        ap_phi_mux_k_3_flag_0_phi_fu_500_p18 = k_3_flag_0_reg_495;
    end
end

always @ (*) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_pair_idx_flag_0_phi_fu_633_p18 = 1'd0;
    end else begin
        ap_phi_mux_pair_idx_flag_0_phi_fu_633_p18 = pair_idx_flag_0_reg_628;
    end
end

always @ (*) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_phi_ln164_phi_fu_699_p18 = 2'd1;
    end else begin
        ap_phi_mux_phi_ln164_phi_fu_699_p18 = phi_ln164_reg_693;
    end
end

always @ (*) begin
    if (((icmp_ln87_reg_1439 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_power_acc_new_0_phi_fu_411_p4 = 36'd0;
    end else begin
        ap_phi_mux_power_acc_new_0_phi_fu_411_p4 = power_acc_new_0_reg_408;
    end
end

always @ (*) begin
    if (((icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_power_acc_new_1_phi_fu_421_p4 = ap_phi_mux_power_acc_new_0_phi_fu_411_p4;
    end else begin
        ap_phi_mux_power_acc_new_1_phi_fu_421_p4 = power_acc_new_1_reg_418;
    end
end

always @ (*) begin
    if (((phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_phi_mux_v_count_flag_0_phi_fu_433_p18 = 1'd0;
    end else begin
        ap_phi_mux_v_count_flag_0_phi_fu_433_p18 = v_count_flag_0_reg_428;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_727_p0 = sext_ln113_1_fu_1108_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_727_p0 = sext_ln81_fu_847_p1;
    end else begin
        grp_fu_727_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_727_p1 = sext_ln113_fu_1102_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_727_p1 = sext_ln81_fu_847_p1;
    end else begin
        grp_fu_727_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_731_p0 = sext_ln113_3_fu_1120_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_731_p0 = sext_ln81_1_fu_853_p1;
    end else begin
        grp_fu_731_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_731_p1 = sext_ln113_2_fu_1114_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_731_p1 = sext_ln81_1_fu_853_p1;
    end else begin
        grp_fu_731_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
        grp_fu_988_ap_start = 1'b1;
    end else begin
        grp_fu_988_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) 
    | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34))) begin
        grp_fu_988_ce = 1'b1;
    end else begin
        grp_fu_988_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state91)) begin
        s_goertzel_blk_n = s_goertzel_empty_n;
    end else begin
        s_goertzel_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        s_goertzel_read = 1'b1;
    end else begin
        s_goertzel_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_norm_blk_n = s_norm_full_n;
    end else begin
        s_norm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
        s_norm_write = 1'b1;
    end else begin
        s_norm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        s_xcor_blk_n = s_xcor_full_n;
    end else begin
        s_xcor_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state48) & (s_xcor_full_n == 1'b1))) begin
        s_xcor_write = 1'b1;
    end else begin
        s_xcor_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
        status_cc_current_norm = zext_ln92_fu_955_p1;
    end else begin
        status_cc_current_norm = status_cc_current_norm_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
        status_cc_current_norm_ap_vld = 1'b1;
    end else begin
        status_cc_current_norm_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln87_reg_1439 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        status_cc_norms_fifo = s_norm_num_data_valid;
    end else begin
        status_cc_norms_fifo = status_cc_norms_fifo_preg;
    end
end

always @ (*) begin
    if (((icmp_ln87_reg_1439 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45))) begin
        status_cc_norms_fifo_ap_vld = 1'b1;
    end else begin
        status_cc_norms_fifo_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln87_fu_893_p2 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        status_cc_norms_written = add_ln94_fu_912_p2;
    end else begin
        status_cc_norms_written = status_cc_norms_written_preg;
    end
end

always @ (*) begin
    if (((icmp_ln87_fu_893_p2 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        status_cc_norms_written_ap_vld = 1'b1;
    end else begin
        status_cc_norms_written_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        status_cc_out_fifo = s_xcor_num_data_valid;
    end else begin
        status_cc_out_fifo = status_cc_out_fifo_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        status_cc_out_fifo_ap_vld = 1'b1;
    end else begin
        status_cc_out_fifo_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        status_cc_sample_idx = v_count;
    end else begin
        status_cc_sample_idx = status_cc_sample_idx_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        status_cc_sample_idx_ap_vld = 1'b1;
    end else begin
        status_cc_sample_idx_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        status_cc_samples_in = add_ln58_fu_1319_p2;
    end else begin
        status_cc_samples_in = status_cc_samples_in_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        status_cc_samples_in_ap_vld = 1'b1;
    end else begin
        status_cc_samples_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        status_cc_samples_out = add_ln151_fu_818_p2;
    end else begin
        status_cc_samples_out = status_cc_samples_out_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        status_cc_samples_out_ap_vld = 1'b1;
    end else begin
        status_cc_samples_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        status_cc_state = zext_ln164_fu_1016_p1;
    end else begin
        status_cc_state = status_cc_state_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        status_cc_state_ap_vld = 1'b1;
    end else begin
        status_cc_state_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        u_M_imag_address0_local = zext_ln111_fu_1059_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        u_M_imag_address0_local = zext_ln79_fu_784_p1;
    end else begin
        u_M_imag_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state91)) begin
        u_M_imag_address1_local = zext_ln61_fu_1353_p1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        u_M_imag_address1_local = zext_ln109_fu_1049_p1;
    end else begin
        u_M_imag_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        u_M_imag_ce0_local = 1'b1;
    end else begin
        u_M_imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | ((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)))) begin
        u_M_imag_ce1_local = 1'b1;
    end else begin
        u_M_imag_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        u_M_imag_we1_local = 1'b1;
    end else begin
        u_M_imag_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        u_M_real_address0_local = zext_ln111_fu_1059_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        u_M_real_address0_local = zext_ln79_fu_784_p1;
    end else begin
        u_M_real_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state91)) begin
        u_M_real_address1_local = zext_ln61_fu_1353_p1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        u_M_real_address1_local = zext_ln109_fu_1049_p1;
    end else begin
        u_M_real_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        u_M_real_ce0_local = 1'b1;
    end else begin
        u_M_real_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | ((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1)))) begin
        u_M_real_ce1_local = 1'b1;
    end else begin
        u_M_real_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
        u_M_real_we1_local = 1'b1;
    end else begin
        u_M_real_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd1) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state91;
            end else if ((~(st_1_load_load_fu_756_p1 == 2'd1) & ~(st_1_load_load_fu_756_p1 == 2'd2) & (tmp_nbreadreq_fu_183_p3 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else if (((phase_load_load_fu_772_p1 == 1'd1) & (1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end else if (((phase_load_load_fu_772_p1 == 1'd0) & (1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b0 == ap_block_state1) & (st_1_load_load_fu_756_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln87_fu_893_p2 == 1'd1) & (icmp_ln84_reg_1416 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (s_norm_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state48 : begin
            if (((1'b1 == ap_CS_fsm_state48) & (s_xcor_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state91 : begin
            if (((1'b1 == ap_CS_fsm_state91) & (s_goertzel_empty_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state91;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_flat_M_imag_address0 = zext_ln113_fu_1065_p1;

assign R_flat_M_real_address0 = zext_ln113_fu_1065_p1;

assign add_ln113_1_fu_1140_p2 = (add_ln113_fu_1134_p2 + grp_fu_731_p2);

assign add_ln113_fu_1134_p2 = (grp_fu_727_p2 + shl_ln_fu_1126_p3);

assign add_ln114_fu_1171_p2 = (sub_ln114_fu_1157_p2 + shl_ln9_fu_1163_p3);

assign add_ln117_fu_1188_p2 = (k_1 + 32'd1);

assign add_ln120_fu_1199_p2 = (j + 32'd1);

assign add_ln122_fu_1249_p2 = (j + 32'd2);

assign add_ln127_fu_1210_p2 = (frames_acc + 32'd1);

assign add_ln151_fu_818_p2 = (samples_out_1 + 32'd1);

assign add_ln58_fu_1319_p2 = (samples_in_1 + 32'd1);

assign add_ln62_fu_1359_p2 = (v_count + 32'd1);

assign add_ln81_1_fu_877_p2 = (add_ln81_fu_871_p2 + grp_fu_731_p2);

assign add_ln81_fu_871_p2 = (grp_fu_727_p2 + shl_ln1_fu_863_p3);

assign add_ln83_fu_790_p2 = (diag_i + 32'd1);

assign add_ln94_fu_912_p2 = (norms_written + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign ap_CS_fsm_state91 = ap_CS_fsm[32'd90];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_condition_1509 = ((icmp_ln87_reg_1439 == 1'd1) & (phase_load_reg_1399 == 1'd0) & (st_1_load_reg_1389 == 2'd1) & (1'b1 == ap_CS_fsm_state45));
end

assign ap_ready = internal_ap_ready;

assign corrected_2_fu_934_p4 = {{mul_ln89_fu_928_p2[39:15]}};

assign corrected_fu_976_p3 = ((icmp_ln96_fu_970_p2[0:0] == 1'b1) ? 24'd32768 : trunc_ln89_2_fu_945_p4);

assign grp_fu_751_p2 = (pair_idx_load_reg_1393 + 32'd1);

assign grp_fu_988_p1 = grp_fu_988_p10;

assign grp_fu_988_p10 = corrected_fu_976_p3;

assign icmp_ln119_fu_1193_p2 = ((add_ln117_fu_1188_p2 == 32'd48) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_1204_p2 = (($signed(add_ln120_fu_1199_p2) < $signed(32'd47)) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_1215_p2 = (($signed(add_ln127_fu_1210_p2) < $signed(32'd9)) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_1303_p2 = ((grp_fu_751_p2 == 32'd1128) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_1365_p2 = ((add_ln62_fu_1359_p2 == 32'd48) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_802_p2 = ((add_ln83_fu_790_p2 == 32'd48) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_893_p2 = ((frames_acc == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_970_p2 = (($signed(tmp_5_fu_960_p4) < $signed(10'd1)) ? 1'b1 : 1'b0);

assign im1_fu_1078_p3 = {{u_M_imag_q1}, {13'd0}};

assign im2_fu_1094_p3 = {{u_M_imag_q0}, {13'd0}};

assign mul_ln146_fu_743_p1 = zext_ln146_fu_1263_p1;

assign mul_ln147_fu_747_p1 = zext_ln146_fu_1263_p1;

assign mul_ln89_fu_928_p1 = 40'd23170;

assign out_im_fu_1284_p4 = {{mul_ln147_fu_747_p2[53:36]}};

assign out_re_fu_1269_p4 = {{mul_ln146_fu_743_p2[53:36]}};

assign phase_load_load_fu_772_p1 = phase;

assign re1_fu_1070_p3 = {{u_M_real_q1}, {13'd0}};

assign re2_fu_1086_p3 = {{u_M_real_q0}, {13'd0}};

assign s_norm_din = {{mul_ln89_fu_928_p2[39:15]}};

assign s_xcor_din = {{out_im_fu_1284_p4}, {out_re_fu_1269_p4}};

assign select_ln128_1_fu_1235_p3 = ((icmp_ln128_fu_1215_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln128_fu_1221_p3 = ((icmp_ln128_fu_1215_p2[0:0] == 1'b1) ? add_ln127_fu_1210_p2 : 32'd0);

assign sext_ln113_1_fu_1108_p1 = re2_fu_1086_p3;

assign sext_ln113_2_fu_1114_p1 = im1_fu_1078_p3;

assign sext_ln113_3_fu_1120_p1 = im2_fu_1094_p3;

assign sext_ln113_fu_1102_p1 = re1_fu_1070_p3;

assign sext_ln146_fu_1254_p0 = R_flat_M_real_q1;

assign sext_ln147_fu_1279_p0 = R_flat_M_imag_q1;

assign sext_ln81_1_fu_853_p1 = $signed(ui_fu_839_p3);

assign sext_ln81_fu_847_p1 = $signed(ur_fu_831_p3);

assign shl_ln1_fu_863_p3 = {{power_acc}, {26'd0}};

assign shl_ln9_fu_1163_p3 = {{R_flat_M_imag_q0}, {26'd0}};

assign shl_ln_fu_1126_p3 = {{R_flat_M_real_q0}, {26'd0}};

assign st_1_load_load_fu_756_p1 = st_1;

assign start_out = real_start;

assign sub_ln114_fu_1157_p2 = (mul_ln114_fu_735_p2 - mul_ln114_1_fu_739_p2);

assign tmp_5_fu_960_p4 = {{mul_ln89_fu_928_p2[39:30]}};

assign tmp_nbreadreq_fu_183_p3 = s_goertzel_empty_n;

assign trunc_ln89_2_fu_945_p4 = {{mul_ln89_fu_928_p2[38:15]}};

assign trunc_ln97_fu_994_p1 = grp_fu_988_p2[23:0];

assign u_M_imag_d1 = {{s_goertzel_dout[35:18]}};

assign ui_fu_839_p3 = {{u_M_imag_q0}, {13'd0}};

assign ur_fu_831_p3 = {{u_M_real_q0}, {13'd0}};

assign w_re_fu_1337_p1 = s_goertzel_dout[17:0];

assign zext_ln109_fu_1049_p1 = k_1;

assign zext_ln111_fu_1059_p1 = j;

assign zext_ln113_fu_1065_p1 = pair_idx_load_reg_1393;

assign zext_ln143_fu_808_p1 = pair_idx;

assign zext_ln146_fu_1263_p1 = scale;

assign zext_ln164_fu_1016_p1 = ap_phi_mux_phi_ln164_phi_fu_699_p18;

assign zext_ln61_fu_1353_p1 = v_count;

assign zext_ln79_fu_784_p1 = diag_i;

assign zext_ln92_fu_955_p1 = corrected_2_fu_934_p4;

always @ (posedge ap_clk) begin
    status_cc_current_norm_preg[31:25] <= 7'b0000000;
    status_cc_state_preg[7:2] <= 6'b000000;
end

endmodule //deepwaveaccel_crosscor
