-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity deepwaveaccel_goertzel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    goer_cfg_COS_OMEGA_0 : IN STD_LOGIC_VECTOR (17 downto 0);
    goer_cfg_COS_OMEGA_1 : IN STD_LOGIC_VECTOR (17 downto 0);
    goer_cfg_COS_OMEGA2_0 : IN STD_LOGIC_VECTOR (17 downto 0);
    goer_cfg_COS_OMEGA2_1 : IN STD_LOGIC_VECTOR (17 downto 0);
    goer_cfg_SIN_OMEGA_0 : IN STD_LOGIC_VECTOR (17 downto 0);
    goer_cfg_SIN_OMEGA_1 : IN STD_LOGIC_VECTOR (17 downto 0);
    in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_r_TVALID : IN STD_LOGIC;
    in_r_TREADY : OUT STD_LOGIC;
    s_goertzel_din : OUT STD_LOGIC_VECTOR (35 downto 0);
    s_goertzel_full_n : IN STD_LOGIC;
    s_goertzel_write : OUT STD_LOGIC;
    s_goertzel_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    s_goertzel_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    status_gz_samples_in : OUT STD_LOGIC_VECTOR (31 downto 0);
    status_gz_samples_in_ap_vld : OUT STD_LOGIC;
    status_gz_sample_win : OUT STD_LOGIC_VECTOR (31 downto 0);
    status_gz_sample_win_ap_vld : OUT STD_LOGIC;
    status_gz_samples_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    status_gz_samples_out_ap_vld : OUT STD_LOGIC;
    status_gz_samples_out_fifo : OUT STD_LOGIC_VECTOR (31 downto 0);
    status_gz_samples_out_fifo_ap_vld : OUT STD_LOGIC );
end;


architecture behav of deepwaveaccel_goertzel is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal samples_in : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sample : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hann_window_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hann_window_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal samples_out : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal s_goertzel_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal cosw_reg_638 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cosw_1_reg_643 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinw_reg_648 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinw_1_reg_653 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_nbreadreq_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_658 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_i_i26_i244_i_fu_370_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln_fu_391_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln75_1_fu_418_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln80_fu_428_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln83_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln83_reg_717 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln88_fu_439_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_6_reg_731 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln88_2_fu_465_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_phi_mux_sample_new_0_phi_fu_220_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_new_0_reg_217 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_phi_fu_230_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_phi_fu_240_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_phi_fu_250_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_phi_fu_260_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln63_fu_313_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln56_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln95_fu_479_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal status_gz_samples_in_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal status_gz_sample_win_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal status_gz_samples_out_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal status_gz_samples_out_fifo_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hann_window_ce0_local : STD_LOGIC;
    signal sext_ln75_1_fu_292_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln75_3_fu_304_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln64_fu_318_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_322_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln64_1_fu_330_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln64_fu_346_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln64_fu_346_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal xw_fu_352_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_362_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_593_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln1_fu_378_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln75_fu_386_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of sub_ln75_fu_386_p2 : signal is "no";
    signal grp_fu_602_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln75_1_fu_405_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln75_1_fu_413_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 of sub_ln75_1_fu_413_p2 : signal is "no";
    signal mul_ln89_fu_449_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln89_fu_449_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln2_fu_492_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln88_1_fu_506_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_513_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_611_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_5_fu_513_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal and_ln_fu_522_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln88_fu_530_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_620_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln88_fu_530_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 of add_ln88_fu_530_p2 : signal is "no";
    signal trunc_ln2_fu_545_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_629_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln2_fu_545_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln1_fu_535_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_593_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_602_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_611_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_611_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_620_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_620_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_629_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_629_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_593_ce : STD_LOGIC;
    signal grp_fu_602_ce : STD_LOGIC;
    signal grp_fu_611_ce : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_620_ce : STD_LOGIC;
    signal grp_fu_629_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_in_r_U_apdone_blk : STD_LOGIC;
    signal in_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_r_TVALID_int_regslice : STD_LOGIC;
    signal in_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_r_U_ack_in : STD_LOGIC;
    signal mul_ln64_fu_346_p10 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component deepwaveaccel_mul_14s_13ns_27_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component deepwaveaccel_mul_18s_18s_34_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component deepwaveaccel_mac_muladd_18s_18s_30s_34_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component deepwaveaccel_mac_mulsub_18s_18s_34ns_34_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component deepwaveaccel_mac_muladd_18s_18s_34ns_34_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component deepwaveaccel_goertzel_hann_window_ROM_1P_BRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component deepwaveaccel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    hann_window_U : component deepwaveaccel_goertzel_hann_window_ROM_1P_BRAM_1R
    generic map (
        DataWidth => 12,
        AddressRange => 200,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hann_window_address0,
        ce0 => hann_window_ce0_local,
        q0 => hann_window_q0);

    mul_14s_13ns_27_1_1_U3 : component deepwaveaccel_mul_14s_13ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 13,
        dout_WIDTH => 27)
    port map (
        din0 => shl_ln_fu_322_p3,
        din1 => mul_ln64_fu_346_p1,
        dout => mul_ln64_fu_346_p2);

    mul_18s_18s_34_1_1_U4 : component deepwaveaccel_mul_18s_18s_34_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 34)
    port map (
        din0 => mul_ln89_fu_449_p0,
        din1 => sinw_reg_648,
        dout => mul_ln89_fu_449_p2);

    mac_muladd_18s_18s_30s_34_4_1_U5 : component deepwaveaccel_mac_muladd_18s_18s_30s_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 30,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln75_1_fu_292_p0,
        din1 => goer_cfg_COS_OMEGA2_0,
        din2 => grp_fu_593_p2,
        ce => grp_fu_593_ce,
        dout => grp_fu_593_p3);

    mac_muladd_18s_18s_30s_34_4_1_U6 : component deepwaveaccel_mac_muladd_18s_18s_30s_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 30,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln75_3_fu_304_p0,
        din1 => goer_cfg_COS_OMEGA2_1,
        din2 => grp_fu_602_p2,
        ce => grp_fu_602_ce,
        dout => grp_fu_602_p3);

    mac_mulsub_18s_18s_34ns_34_4_1_U7 : component deepwaveaccel_mac_mulsub_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_611_p0,
        din1 => cosw_reg_638,
        din2 => grp_fu_611_p2,
        ce => grp_fu_611_ce,
        dout => grp_fu_611_p3);

    mac_mulsub_18s_18s_34ns_34_4_1_U8 : component deepwaveaccel_mac_mulsub_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_620_p0,
        din1 => cosw_1_reg_643,
        din2 => grp_fu_620_p2,
        ce => grp_fu_620_ce,
        dout => grp_fu_620_p3);

    mac_muladd_18s_18s_34ns_34_4_1_U9 : component deepwaveaccel_mac_muladd_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_629_p0,
        din1 => sinw_1_reg_653,
        din2 => grp_fu_629_p2,
        ce => grp_fu_629_ce,
        dout => grp_fu_629_p3);

    regslice_both_in_r_U : component deepwaveaccel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_r_TDATA,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_U_ack_in,
        data_out => in_r_TDATA_int_regslice,
        vld_out => in_r_TVALID_int_regslice,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    status_gz_sample_win_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                status_gz_sample_win_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    status_gz_sample_win_preg <= sample;
                end if; 
            end if;
        end if;
    end process;


    status_gz_samples_in_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                status_gz_samples_in_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    status_gz_samples_in_preg <= add_ln56_fu_271_p2;
                end if; 
            end if;
        end if;
    end process;


    status_gz_samples_out_fifo_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                status_gz_samples_out_fifo_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                    status_gz_samples_out_fifo_preg <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_goertzel_num_data_valid),32));
                end if; 
            end if;
        end if;
    end process;


    status_gz_samples_out_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                status_gz_samples_out_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_1))) then 
                    status_gz_samples_out_preg <= add_ln95_fu_479_p2;
                end if; 
            end if;
        end if;
    end process;


    goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247 <= ap_const_lv18_0;
            end if; 
        end if;
    end process;

    goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237 <= ap_const_lv18_0;
            end if; 
        end if;
    end process;

    goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257 <= sub_ln75_1_fu_413_p2(33 downto 16);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257 <= ap_const_lv18_0;
            end if; 
        end if;
    end process;

    goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227 <= sub_ln75_fu_386_p2(33 downto 16);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227 <= ap_const_lv18_0;
            end if; 
        end if;
    end process;

    sample_new_0_reg_217_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then 
                sample_new_0_reg_217 <= add_ln80_fu_428_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
                sample_new_0_reg_217 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                cosw_1_reg_643 <= goer_cfg_COS_OMEGA_1;
                cosw_reg_638 <= goer_cfg_COS_OMEGA_0;
                sinw_1_reg_653 <= goer_cfg_SIN_OMEGA_1;
                sinw_reg_648 <= goer_cfg_SIN_OMEGA_0;
                tmp_reg_658 <= tmp_nbreadreq_fu_148_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (tmp_reg_658 = ap_const_lv1_1))) then
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev <= ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_phi_fu_260_p4;
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2 <= ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_phi_fu_250_p4;
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_1 <= ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_phi_fu_240_p4;
                goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_1 <= ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_phi_fu_230_p4;
                sample <= ap_phi_mux_sample_new_0_phi_fu_220_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln83_reg_717 <= icmp_ln83_fu_433_p2;
                tmp_6_reg_731 <= mul_ln89_fu_449_p2(33 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then
                samples_in <= add_ln56_fu_271_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_1))) then
                samples_out <= add_ln95_fu_479_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, s_goertzel_full_n, ap_CS_fsm_state3, ap_CS_fsm_state7, ap_block_state1, tmp_nbreadreq_fu_148_p3, ap_CS_fsm_state4, icmp_ln83_fu_433_p2, in_r_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((in_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((s_goertzel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln56_fu_271_p2 <= std_logic_vector(unsigned(samples_in) + unsigned(ap_const_lv32_1));
    add_ln80_fu_428_p2 <= std_logic_vector(unsigned(sample) + unsigned(ap_const_lv32_1));
    add_ln88_fu_530_p1 <= grp_fu_620_p3;
    add_ln88_fu_530_p2 <= std_logic_vector(unsigned(and_ln_fu_522_p3) + unsigned(add_ln88_fu_530_p1));
    add_ln95_fu_479_p2 <= std_logic_vector(unsigned(samples_out) + unsigned(ap_const_lv32_1));
    and_ln_fu_522_p3 <= (tmp_5_fu_513_p4 & ap_const_lv16_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(in_r_TVALID_int_regslice)
    begin
        if ((in_r_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(s_goertzel_full_n)
    begin
        if ((s_goertzel_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_phi_fu_250_p4_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8, goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_phi_fu_250_p4 <= ap_const_lv18_0;
        else 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_phi_fu_250_p4 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_19_new_0_reg_247;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_phi_fu_240_p4_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8, goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_phi_fu_240_p4 <= ap_const_lv18_0;
        else 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_phi_fu_240_p4 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_new_0_reg_237;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_phi_fu_260_p4_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8, goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_phi_fu_260_p4 <= ap_const_lv18_0;
        else 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_phi_fu_260_p4 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_18_new_0_reg_257;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_phi_fu_230_p4_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8, goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_phi_fu_230_p4 <= ap_const_lv18_0;
        else 
            ap_phi_mux_goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_phi_fu_230_p4 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_new_0_reg_227;
        end if; 
    end process;


    ap_phi_mux_sample_new_0_phi_fu_220_p4_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, sample_new_0_reg_217, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            ap_phi_mux_sample_new_0_phi_fu_220_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_sample_new_0_phi_fu_220_p4 <= sample_new_0_reg_217;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    grp_fu_593_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, in_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((in_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            grp_fu_593_ce <= ap_const_logic_1;
        else 
            grp_fu_593_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_593_p2 <= shl_i_i26_i244_i_fu_370_p1(30 - 1 downto 0);

    grp_fu_602_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, in_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((in_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            grp_fu_602_ce <= ap_const_logic_1;
        else 
            grp_fu_602_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_602_p2 <= shl_i_i26_i244_i_fu_370_p1(30 - 1 downto 0);

    grp_fu_611_ce_assign_proc : process(s_goertzel_full_n, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((s_goertzel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            grp_fu_611_ce <= ap_const_logic_1;
        else 
            grp_fu_611_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_611_p0 <= sext_ln88_fu_439_p1(18 - 1 downto 0);
    grp_fu_611_p2 <= (shl_ln2_fu_492_p1 & ap_const_lv16_0);

    grp_fu_620_ce_assign_proc : process(s_goertzel_full_n, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((s_goertzel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            grp_fu_620_ce <= ap_const_logic_1;
        else 
            grp_fu_620_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_620_p0 <= sext_ln88_2_fu_465_p1(18 - 1 downto 0);
    grp_fu_620_p2 <= (shl_ln88_1_fu_506_p1 & ap_const_lv16_0);

    grp_fu_629_ce_assign_proc : process(s_goertzel_full_n, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((s_goertzel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            grp_fu_629_ce <= ap_const_logic_1;
        else 
            grp_fu_629_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_629_p0 <= sext_ln88_2_fu_465_p1(18 - 1 downto 0);
    grp_fu_629_p2 <= (tmp_6_reg_731 & ap_const_lv16_0);
    hann_window_address0 <= zext_ln63_fu_313_p1(8 - 1 downto 0);

    hann_window_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hann_window_ce0_local <= ap_const_logic_1;
        else 
            hann_window_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln83_fu_433_p2 <= "1" when (add_ln80_fu_428_p2 = ap_const_lv32_C8) else "0";

    in_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, in_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_TDATA_blk_n <= in_r_TVALID_int_regslice;
        else 
            in_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_r_TREADY <= regslice_both_in_r_U_ack_in;

    in_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state3, in_r_TVALID_int_regslice)
    begin
        if (((in_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln64_fu_346_p1 <= mul_ln64_fu_346_p10(13 - 1 downto 0);
    mul_ln64_fu_346_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln64_1_fu_330_p3),27));
    mul_ln89_fu_449_p0 <= sext_ln88_fu_439_p1(18 - 1 downto 0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_goertzel_blk_n_assign_proc : process(s_goertzel_full_n, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            s_goertzel_blk_n <= s_goertzel_full_n;
        else 
            s_goertzel_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_goertzel_din <= (trunc_ln2_fu_545_p4 & trunc_ln1_fu_535_p4);

    s_goertzel_write_assign_proc : process(s_goertzel_full_n, ap_CS_fsm_state7)
    begin
        if (((s_goertzel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            s_goertzel_write <= ap_const_logic_1;
        else 
            s_goertzel_write <= ap_const_logic_0;
        end if; 
    end process;

    sext_ln75_1_fu_292_p0 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_1;
    sext_ln75_3_fu_304_p0 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev;
        sext_ln88_2_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln75_1_fu_418_p4),34));

        sext_ln88_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_391_p4),34));

        shl_i_i26_i244_i_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_362_p3),34));

    shl_ln1_fu_378_p3 <= (goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2_1 & ap_const_lv16_0);
    shl_ln2_fu_492_p1 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev_1;
    shl_ln64_1_fu_330_p3 <= (hann_window_q0 & ap_const_lv1_0);
    shl_ln75_1_fu_405_p3 <= (goertzel_stream_stream_goertzel_config_status_gz_t_s_prev2 & ap_const_lv16_0);
    shl_ln88_1_fu_506_p1 <= goertzel_stream_stream_goertzel_config_status_gz_t_s_prev;
    shl_ln_fu_322_p3 <= (trunc_ln64_fu_318_p1 & ap_const_lv2_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    status_gz_sample_win_assign_proc : process(sample, ap_CS_fsm_state2, status_gz_sample_win_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            status_gz_sample_win <= sample;
        else 
            status_gz_sample_win <= status_gz_sample_win_preg;
        end if; 
    end process;


    status_gz_sample_win_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            status_gz_sample_win_ap_vld <= ap_const_logic_1;
        else 
            status_gz_sample_win_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    status_gz_samples_in_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, tmp_nbreadreq_fu_148_p3, add_ln56_fu_271_p2, status_gz_samples_in_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then 
            status_gz_samples_in <= add_ln56_fu_271_p2;
        else 
            status_gz_samples_in <= status_gz_samples_in_preg;
        end if; 
    end process;


    status_gz_samples_in_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, tmp_nbreadreq_fu_148_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_nbreadreq_fu_148_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then 
            status_gz_samples_in_ap_vld <= ap_const_logic_1;
        else 
            status_gz_samples_in_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    status_gz_samples_out_assign_proc : process(ap_CS_fsm_state4, icmp_ln83_fu_433_p2, add_ln95_fu_479_p2, status_gz_samples_out_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_1))) then 
            status_gz_samples_out <= add_ln95_fu_479_p2;
        else 
            status_gz_samples_out <= status_gz_samples_out_preg;
        end if; 
    end process;


    status_gz_samples_out_ap_vld_assign_proc : process(ap_CS_fsm_state4, icmp_ln83_fu_433_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln83_fu_433_p2 = ap_const_lv1_1))) then 
            status_gz_samples_out_ap_vld <= ap_const_logic_1;
        else 
            status_gz_samples_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    status_gz_samples_out_fifo_assign_proc : process(s_goertzel_num_data_valid, tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8, status_gz_samples_out_fifo_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            status_gz_samples_out_fifo <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_goertzel_num_data_valid),32));
        else 
            status_gz_samples_out_fifo <= status_gz_samples_out_fifo_preg;
        end if; 
    end process;


    status_gz_samples_out_fifo_ap_vld_assign_proc : process(tmp_reg_658, icmp_ln83_reg_717, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln83_reg_717 = ap_const_lv1_1) and (tmp_reg_658 = ap_const_lv1_1))) then 
            status_gz_samples_out_fifo_ap_vld <= ap_const_logic_1;
        else 
            status_gz_samples_out_fifo_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln75_1_fu_413_p2 <= std_logic_vector(signed(grp_fu_602_p3) - signed(shl_ln75_1_fu_405_p3));
    sub_ln75_fu_386_p2 <= std_logic_vector(signed(grp_fu_593_p3) - signed(shl_ln1_fu_378_p3));
    tmp_2_fu_362_p3 <= (xw_fu_352_p4 & ap_const_lv16_0);
    tmp_5_fu_513_p1 <= grp_fu_611_p3;
    tmp_5_fu_513_p4 <= tmp_5_fu_513_p1(33 downto 16);
    tmp_nbreadreq_fu_148_p3 <= (0=>(in_r_TVALID_int_regslice), others=>'-');
    trunc_ln1_fu_535_p4 <= add_ln88_fu_530_p2(33 downto 16);
    trunc_ln2_fu_545_p1 <= grp_fu_629_p3;
    trunc_ln2_fu_545_p4 <= trunc_ln2_fu_545_p1(33 downto 16);
    trunc_ln64_fu_318_p1 <= in_r_TDATA_int_regslice(12 - 1 downto 0);
    trunc_ln75_1_fu_418_p4 <= sub_ln75_1_fu_413_p2(33 downto 16);
    trunc_ln_fu_391_p4 <= sub_ln75_fu_386_p2(33 downto 16);
    xw_fu_352_p4 <= mul_ln64_fu_346_p2(26 downto 13);
    zext_ln63_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sample),64));
end behav;
