-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity deepwaveaccel is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    param_bp_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    param_db_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_r_TVALID : IN STD_LOGIC;
    in_r_TREADY : OUT STD_LOGIC;
    param_bp_TVALID : IN STD_LOGIC;
    param_bp_TREADY : OUT STD_LOGIC;
    param_db_TVALID : IN STD_LOGIC;
    param_db_TREADY : OUT STD_LOGIC;
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC );
end;


architecture behav of deepwaveaccel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "deepwaveaccel_deepwaveaccel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.047667,HLS_SYN_LAT=67,HLS_SYN_TPT=25,HLS_SYN_MEM=72,HLS_SYN_DSP=0,HLS_SYN_FF=7434,HLS_SYN_LUT=18511,HLS_VERSION=2025_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal goer_cfg_COS_OMEGA_0 : STD_LOGIC_VECTOR (17 downto 0);
    signal goer_cfg_COS_OMEGA_1 : STD_LOGIC_VECTOR (17 downto 0);
    signal goer_cfg_COS_OMEGA2_0 : STD_LOGIC_VECTOR (17 downto 0);
    signal goer_cfg_COS_OMEGA2_1 : STD_LOGIC_VECTOR (17 downto 0);
    signal goer_cfg_SIN_OMEGA_0 : STD_LOGIC_VECTOR (17 downto 0);
    signal goer_cfg_SIN_OMEGA_1 : STD_LOGIC_VECTOR (17 downto 0);
    signal debl_cfg : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_debl_cfg_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_debl_cfg_c_write : STD_LOGIC;
    signal goertzel_U0_ap_start : STD_LOGIC;
    signal goertzel_U0_ap_done : STD_LOGIC;
    signal goertzel_U0_ap_continue : STD_LOGIC;
    signal goertzel_U0_ap_idle : STD_LOGIC;
    signal goertzel_U0_ap_ready : STD_LOGIC;
    signal goertzel_U0_start_out : STD_LOGIC;
    signal goertzel_U0_start_write : STD_LOGIC;
    signal goertzel_U0_in_r_TREADY : STD_LOGIC;
    signal goertzel_U0_s_goertzel_din : STD_LOGIC_VECTOR (35 downto 0);
    signal goertzel_U0_s_goertzel_write : STD_LOGIC;
    signal goertzel_U0_status_gz_samples_in : STD_LOGIC_VECTOR (31 downto 0);
    signal goertzel_U0_status_gz_samples_in_ap_vld : STD_LOGIC;
    signal goertzel_U0_status_gz_sample_win : STD_LOGIC_VECTOR (31 downto 0);
    signal goertzel_U0_status_gz_sample_win_ap_vld : STD_LOGIC;
    signal goertzel_U0_status_gz_samples_out : STD_LOGIC_VECTOR (31 downto 0);
    signal goertzel_U0_status_gz_samples_out_ap_vld : STD_LOGIC;
    signal goertzel_U0_status_gz_samples_out_fifo : STD_LOGIC_VECTOR (31 downto 0);
    signal goertzel_U0_status_gz_samples_out_fifo_ap_vld : STD_LOGIC;
    signal crosscor_U0_ap_start : STD_LOGIC;
    signal crosscor_U0_ap_done : STD_LOGIC;
    signal crosscor_U0_ap_continue : STD_LOGIC;
    signal crosscor_U0_ap_idle : STD_LOGIC;
    signal crosscor_U0_ap_ready : STD_LOGIC;
    signal crosscor_U0_start_out : STD_LOGIC;
    signal crosscor_U0_start_write : STD_LOGIC;
    signal crosscor_U0_s_goertzel_read : STD_LOGIC;
    signal crosscor_U0_s_xcor_din : STD_LOGIC_VECTOR (35 downto 0);
    signal crosscor_U0_s_xcor_write : STD_LOGIC;
    signal crosscor_U0_s_norm_din : STD_LOGIC_VECTOR (24 downto 0);
    signal crosscor_U0_s_norm_write : STD_LOGIC;
    signal crosscor_U0_status_cc_state : STD_LOGIC_VECTOR (7 downto 0);
    signal crosscor_U0_status_cc_state_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_samples_in : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_samples_in_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_samples_out : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_samples_out_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_sample_idx : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_sample_idx_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_current_norm : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_current_norm_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_norms_written : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_norms_written_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_out_fifo : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_out_fifo_ap_vld : STD_LOGIC;
    signal crosscor_U0_status_cc_norms_fifo : STD_LOGIC_VECTOR (31 downto 0);
    signal crosscor_U0_status_cc_norms_fifo_ap_vld : STD_LOGIC;
    signal backprojection_U0_ap_start : STD_LOGIC;
    signal backprojection_U0_ap_done : STD_LOGIC;
    signal backprojection_U0_ap_continue : STD_LOGIC;
    signal backprojection_U0_ap_idle : STD_LOGIC;
    signal backprojection_U0_ap_ready : STD_LOGIC;
    signal backprojection_U0_s_xcor_read : STD_LOGIC;
    signal backprojection_U0_param_bp_TREADY : STD_LOGIC;
    signal backprojection_U0_s_bp_din : STD_LOGIC_VECTOR (17 downto 0);
    signal backprojection_U0_s_bp_write : STD_LOGIC;
    signal backprojection_U0_status_bp_config_loaded : STD_LOGIC_VECTOR (0 downto 0);
    signal backprojection_U0_status_bp_config_loaded_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_fsm_state : STD_LOGIC_VECTOR (7 downto 0);
    signal backprojection_U0_status_bp_fsm_state_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_param_state : STD_LOGIC_VECTOR (7 downto 0);
    signal backprojection_U0_status_bp_param_state_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_idx : STD_LOGIC_VECTOR (15 downto 0);
    signal backprojection_U0_status_bp_idx_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_sigmas_in : STD_LOGIC_VECTOR (31 downto 0);
    signal backprojection_U0_status_bp_sigmas_in_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_pixels_out : STD_LOGIC_VECTOR (31 downto 0);
    signal backprojection_U0_status_bp_pixels_out_ap_vld : STD_LOGIC;
    signal backprojection_U0_status_bp_out_fifo_level : STD_LOGIC_VECTOR (15 downto 0);
    signal backprojection_U0_status_bp_out_fifo_level_ap_vld : STD_LOGIC;
    signal deblur_U0_ap_start : STD_LOGIC;
    signal deblur_U0_ap_done : STD_LOGIC;
    signal deblur_U0_ap_continue : STD_LOGIC;
    signal deblur_U0_ap_idle : STD_LOGIC;
    signal deblur_U0_ap_ready : STD_LOGIC;
    signal deblur_U0_debl_cfg_read : STD_LOGIC;
    signal deblur_U0_s_bp_read : STD_LOGIC;
    signal deblur_U0_param_db_TREADY : STD_LOGIC;
    signal deblur_U0_out_r_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal deblur_U0_out_r_TVALID : STD_LOGIC;
    signal deblur_U0_out_r_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal deblur_U0_s_norm_read : STD_LOGIC;
    signal deblur_U0_status_db_config_loaded : STD_LOGIC_VECTOR (0 downto 0);
    signal deblur_U0_status_db_config_loaded_ap_vld : STD_LOGIC;
    signal deblur_U0_status_db_fsm_state : STD_LOGIC_VECTOR (7 downto 0);
    signal deblur_U0_status_db_fsm_state_ap_vld : STD_LOGIC;
    signal deblur_U0_status_db_param_state : STD_LOGIC_VECTOR (7 downto 0);
    signal deblur_U0_status_db_param_state_ap_vld : STD_LOGIC;
    signal deblur_U0_status_db_idx : STD_LOGIC_VECTOR (15 downto 0);
    signal deblur_U0_status_db_idx_ap_vld : STD_LOGIC;
    signal deblur_U0_status_db_pixels_in : STD_LOGIC_VECTOR (31 downto 0);
    signal deblur_U0_status_db_pixels_in_ap_vld : STD_LOGIC;
    signal deblur_U0_status_db_pixels_out : STD_LOGIC_VECTOR (31 downto 0);
    signal deblur_U0_status_db_pixels_out_ap_vld : STD_LOGIC;
    signal debl_cfg_c_full_n : STD_LOGIC;
    signal debl_cfg_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal debl_cfg_c_empty_n : STD_LOGIC;
    signal debl_cfg_c_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal debl_cfg_c_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal s_goertzel_full_n : STD_LOGIC;
    signal s_goertzel_dout : STD_LOGIC_VECTOR (35 downto 0);
    signal s_goertzel_empty_n : STD_LOGIC;
    signal s_goertzel_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_goertzel_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_xcor_full_n : STD_LOGIC;
    signal s_xcor_dout : STD_LOGIC_VECTOR (35 downto 0);
    signal s_xcor_empty_n : STD_LOGIC;
    signal s_xcor_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_xcor_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_norm_full_n : STD_LOGIC;
    signal s_norm_dout : STD_LOGIC_VECTOR (24 downto 0);
    signal s_norm_empty_n : STD_LOGIC;
    signal s_norm_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal s_norm_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal s_bp_full_n : STD_LOGIC;
    signal s_bp_dout : STD_LOGIC_VECTOR (17 downto 0);
    signal s_bp_empty_n : STD_LOGIC;
    signal s_bp_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_bp_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal start_for_deblur_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_deblur_U0_full_n : STD_LOGIC;
    signal start_for_deblur_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_deblur_U0_empty_n : STD_LOGIC;
    signal start_for_crosscor_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_crosscor_U0_full_n : STD_LOGIC;
    signal start_for_crosscor_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_crosscor_U0_empty_n : STD_LOGIC;
    signal start_for_backprojection_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_backprojection_U0_full_n : STD_LOGIC;
    signal start_for_backprojection_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_backprojection_U0_empty_n : STD_LOGIC;

    component deepwaveaccel_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        debl_cfg : IN STD_LOGIC_VECTOR (7 downto 0);
        debl_cfg_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        debl_cfg_c_full_n : IN STD_LOGIC;
        debl_cfg_c_write : OUT STD_LOGIC;
        debl_cfg_c_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        debl_cfg_c_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component deepwaveaccel_goertzel IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        goer_cfg_COS_OMEGA_0 : IN STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA_1 : IN STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA2_0 : IN STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA2_1 : IN STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_SIN_OMEGA_0 : IN STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_SIN_OMEGA_1 : IN STD_LOGIC_VECTOR (17 downto 0);
        in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_r_TVALID : IN STD_LOGIC;
        in_r_TREADY : OUT STD_LOGIC;
        s_goertzel_din : OUT STD_LOGIC_VECTOR (35 downto 0);
        s_goertzel_full_n : IN STD_LOGIC;
        s_goertzel_write : OUT STD_LOGIC;
        s_goertzel_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_goertzel_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        status_gz_samples_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_in_ap_vld : OUT STD_LOGIC;
        status_gz_sample_win : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_gz_sample_win_ap_vld : OUT STD_LOGIC;
        status_gz_samples_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_out_ap_vld : OUT STD_LOGIC;
        status_gz_samples_out_fifo : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_out_fifo_ap_vld : OUT STD_LOGIC );
    end component;


    component deepwaveaccel_crosscor IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_goertzel_dout : IN STD_LOGIC_VECTOR (35 downto 0);
        s_goertzel_empty_n : IN STD_LOGIC;
        s_goertzel_read : OUT STD_LOGIC;
        s_goertzel_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_goertzel_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_xcor_din : OUT STD_LOGIC_VECTOR (35 downto 0);
        s_xcor_full_n : IN STD_LOGIC;
        s_xcor_write : OUT STD_LOGIC;
        s_xcor_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_xcor_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_norm_din : OUT STD_LOGIC_VECTOR (24 downto 0);
        s_norm_full_n : IN STD_LOGIC;
        s_norm_write : OUT STD_LOGIC;
        s_norm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s_norm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        status_cc_state : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_cc_state_ap_vld : OUT STD_LOGIC;
        status_cc_samples_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_samples_in_ap_vld : OUT STD_LOGIC;
        status_cc_samples_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_samples_out_ap_vld : OUT STD_LOGIC;
        status_cc_sample_idx : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_sample_idx_ap_vld : OUT STD_LOGIC;
        status_cc_current_norm : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_current_norm_ap_vld : OUT STD_LOGIC;
        status_cc_norms_written : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_norms_written_ap_vld : OUT STD_LOGIC;
        status_cc_out_fifo : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_out_fifo_ap_vld : OUT STD_LOGIC;
        status_cc_norms_fifo : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_cc_norms_fifo_ap_vld : OUT STD_LOGIC );
    end component;


    component deepwaveaccel_backprojection IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_xcor_dout : IN STD_LOGIC_VECTOR (35 downto 0);
        s_xcor_empty_n : IN STD_LOGIC;
        s_xcor_read : OUT STD_LOGIC;
        s_xcor_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_xcor_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        param_bp_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        param_bp_TVALID : IN STD_LOGIC;
        param_bp_TREADY : OUT STD_LOGIC;
        s_bp_din : OUT STD_LOGIC_VECTOR (17 downto 0);
        s_bp_full_n : IN STD_LOGIC;
        s_bp_write : OUT STD_LOGIC;
        s_bp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_bp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        status_bp_config_loaded : OUT STD_LOGIC_VECTOR (0 downto 0);
        status_bp_config_loaded_ap_vld : OUT STD_LOGIC;
        status_bp_fsm_state : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_bp_fsm_state_ap_vld : OUT STD_LOGIC;
        status_bp_param_state : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_bp_param_state_ap_vld : OUT STD_LOGIC;
        status_bp_idx : OUT STD_LOGIC_VECTOR (15 downto 0);
        status_bp_idx_ap_vld : OUT STD_LOGIC;
        status_bp_sigmas_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_bp_sigmas_in_ap_vld : OUT STD_LOGIC;
        status_bp_pixels_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_bp_pixels_out_ap_vld : OUT STD_LOGIC;
        status_bp_out_fifo_level : OUT STD_LOGIC_VECTOR (15 downto 0);
        status_bp_out_fifo_level_ap_vld : OUT STD_LOGIC );
    end component;


    component deepwaveaccel_deblur IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        debl_cfg_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        debl_cfg_empty_n : IN STD_LOGIC;
        debl_cfg_read : OUT STD_LOGIC;
        debl_cfg_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        debl_cfg_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        s_bp_dout : IN STD_LOGIC_VECTOR (17 downto 0);
        s_bp_empty_n : IN STD_LOGIC;
        s_bp_read : OUT STD_LOGIC;
        s_bp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_bp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        param_db_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        param_db_TVALID : IN STD_LOGIC;
        param_db_TREADY : OUT STD_LOGIC;
        out_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_TVALID : OUT STD_LOGIC;
        out_r_TREADY : IN STD_LOGIC;
        out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        s_norm_dout : IN STD_LOGIC_VECTOR (24 downto 0);
        s_norm_empty_n : IN STD_LOGIC;
        s_norm_read : OUT STD_LOGIC;
        s_norm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s_norm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        status_db_config_loaded : OUT STD_LOGIC_VECTOR (0 downto 0);
        status_db_config_loaded_ap_vld : OUT STD_LOGIC;
        status_db_fsm_state : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_db_fsm_state_ap_vld : OUT STD_LOGIC;
        status_db_param_state : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_db_param_state_ap_vld : OUT STD_LOGIC;
        status_db_idx : OUT STD_LOGIC_VECTOR (15 downto 0);
        status_db_idx_ap_vld : OUT STD_LOGIC;
        status_db_pixels_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_db_pixels_in_ap_vld : OUT STD_LOGIC;
        status_db_pixels_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        status_db_pixels_out_ap_vld : OUT STD_LOGIC );
    end component;


    component deepwaveaccel_fifo_w8_d5_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component deepwaveaccel_fifo_w36_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (35 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (35 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component deepwaveaccel_fifo_w25_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (24 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (24 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component deepwaveaccel_fifo_w18_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (17 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (17 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component deepwaveaccel_start_for_deblur_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component deepwaveaccel_start_for_crosscor_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component deepwaveaccel_start_for_backprojection_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component deepwaveaccel_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        goer_cfg_COS_OMEGA_0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA_1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA2_0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_COS_OMEGA2_1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_SIN_OMEGA_0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        goer_cfg_SIN_OMEGA_1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        debl_cfg : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_gz_samples_in : IN STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_in_ap_vld : IN STD_LOGIC;
        status_gz_sample_win : IN STD_LOGIC_VECTOR (31 downto 0);
        status_gz_sample_win_ap_vld : IN STD_LOGIC;
        status_gz_samples_out : IN STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_out_ap_vld : IN STD_LOGIC;
        status_gz_samples_out_fifo : IN STD_LOGIC_VECTOR (31 downto 0);
        status_gz_samples_out_fifo_ap_vld : IN STD_LOGIC;
        status_cc_state : IN STD_LOGIC_VECTOR (7 downto 0);
        status_cc_state_ap_vld : IN STD_LOGIC;
        status_cc_samples_in : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_samples_in_ap_vld : IN STD_LOGIC;
        status_cc_samples_out : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_samples_out_ap_vld : IN STD_LOGIC;
        status_cc_sample_idx : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_sample_idx_ap_vld : IN STD_LOGIC;
        status_cc_current_norm : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_current_norm_ap_vld : IN STD_LOGIC;
        status_cc_norms_written : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_norms_written_ap_vld : IN STD_LOGIC;
        status_cc_out_fifo : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_out_fifo_ap_vld : IN STD_LOGIC;
        status_cc_norms_fifo : IN STD_LOGIC_VECTOR (31 downto 0);
        status_cc_norms_fifo_ap_vld : IN STD_LOGIC;
        status_bp_config_loaded : IN STD_LOGIC_VECTOR (0 downto 0);
        status_bp_config_loaded_ap_vld : IN STD_LOGIC;
        status_bp_fsm_state : IN STD_LOGIC_VECTOR (7 downto 0);
        status_bp_fsm_state_ap_vld : IN STD_LOGIC;
        status_bp_param_state : IN STD_LOGIC_VECTOR (7 downto 0);
        status_bp_param_state_ap_vld : IN STD_LOGIC;
        status_bp_idx : IN STD_LOGIC_VECTOR (15 downto 0);
        status_bp_idx_ap_vld : IN STD_LOGIC;
        status_bp_sigmas_in : IN STD_LOGIC_VECTOR (31 downto 0);
        status_bp_sigmas_in_ap_vld : IN STD_LOGIC;
        status_bp_pixels_out : IN STD_LOGIC_VECTOR (31 downto 0);
        status_bp_pixels_out_ap_vld : IN STD_LOGIC;
        status_bp_out_fifo_level : IN STD_LOGIC_VECTOR (15 downto 0);
        status_bp_out_fifo_level_ap_vld : IN STD_LOGIC;
        status_db_config_loaded : IN STD_LOGIC_VECTOR (0 downto 0);
        status_db_config_loaded_ap_vld : IN STD_LOGIC;
        status_db_fsm_state : IN STD_LOGIC_VECTOR (7 downto 0);
        status_db_fsm_state_ap_vld : IN STD_LOGIC;
        status_db_param_state : IN STD_LOGIC_VECTOR (7 downto 0);
        status_db_param_state_ap_vld : IN STD_LOGIC;
        status_db_idx : IN STD_LOGIC_VECTOR (15 downto 0);
        status_db_idx_ap_vld : IN STD_LOGIC;
        status_db_pixels_in : IN STD_LOGIC_VECTOR (31 downto 0);
        status_db_pixels_in_ap_vld : IN STD_LOGIC;
        status_db_pixels_out : IN STD_LOGIC_VECTOR (31 downto 0);
        status_db_pixels_out_ap_vld : IN STD_LOGIC );
    end component;



begin
    CTRL_BUS_s_axi_U : component deepwaveaccel_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        goer_cfg_COS_OMEGA_0 => goer_cfg_COS_OMEGA_0,
        goer_cfg_COS_OMEGA_1 => goer_cfg_COS_OMEGA_1,
        goer_cfg_COS_OMEGA2_0 => goer_cfg_COS_OMEGA2_0,
        goer_cfg_COS_OMEGA2_1 => goer_cfg_COS_OMEGA2_1,
        goer_cfg_SIN_OMEGA_0 => goer_cfg_SIN_OMEGA_0,
        goer_cfg_SIN_OMEGA_1 => goer_cfg_SIN_OMEGA_1,
        debl_cfg => debl_cfg,
        status_gz_samples_in => goertzel_U0_status_gz_samples_in,
        status_gz_samples_in_ap_vld => goertzel_U0_status_gz_samples_in_ap_vld,
        status_gz_sample_win => goertzel_U0_status_gz_sample_win,
        status_gz_sample_win_ap_vld => goertzel_U0_status_gz_sample_win_ap_vld,
        status_gz_samples_out => goertzel_U0_status_gz_samples_out,
        status_gz_samples_out_ap_vld => goertzel_U0_status_gz_samples_out_ap_vld,
        status_gz_samples_out_fifo => goertzel_U0_status_gz_samples_out_fifo,
        status_gz_samples_out_fifo_ap_vld => goertzel_U0_status_gz_samples_out_fifo_ap_vld,
        status_cc_state => crosscor_U0_status_cc_state,
        status_cc_state_ap_vld => crosscor_U0_status_cc_state_ap_vld,
        status_cc_samples_in => crosscor_U0_status_cc_samples_in,
        status_cc_samples_in_ap_vld => crosscor_U0_status_cc_samples_in_ap_vld,
        status_cc_samples_out => crosscor_U0_status_cc_samples_out,
        status_cc_samples_out_ap_vld => crosscor_U0_status_cc_samples_out_ap_vld,
        status_cc_sample_idx => crosscor_U0_status_cc_sample_idx,
        status_cc_sample_idx_ap_vld => crosscor_U0_status_cc_sample_idx_ap_vld,
        status_cc_current_norm => crosscor_U0_status_cc_current_norm,
        status_cc_current_norm_ap_vld => crosscor_U0_status_cc_current_norm_ap_vld,
        status_cc_norms_written => crosscor_U0_status_cc_norms_written,
        status_cc_norms_written_ap_vld => crosscor_U0_status_cc_norms_written_ap_vld,
        status_cc_out_fifo => crosscor_U0_status_cc_out_fifo,
        status_cc_out_fifo_ap_vld => crosscor_U0_status_cc_out_fifo_ap_vld,
        status_cc_norms_fifo => crosscor_U0_status_cc_norms_fifo,
        status_cc_norms_fifo_ap_vld => crosscor_U0_status_cc_norms_fifo_ap_vld,
        status_bp_config_loaded => backprojection_U0_status_bp_config_loaded,
        status_bp_config_loaded_ap_vld => backprojection_U0_status_bp_config_loaded_ap_vld,
        status_bp_fsm_state => backprojection_U0_status_bp_fsm_state,
        status_bp_fsm_state_ap_vld => backprojection_U0_status_bp_fsm_state_ap_vld,
        status_bp_param_state => backprojection_U0_status_bp_param_state,
        status_bp_param_state_ap_vld => backprojection_U0_status_bp_param_state_ap_vld,
        status_bp_idx => backprojection_U0_status_bp_idx,
        status_bp_idx_ap_vld => backprojection_U0_status_bp_idx_ap_vld,
        status_bp_sigmas_in => backprojection_U0_status_bp_sigmas_in,
        status_bp_sigmas_in_ap_vld => backprojection_U0_status_bp_sigmas_in_ap_vld,
        status_bp_pixels_out => backprojection_U0_status_bp_pixels_out,
        status_bp_pixels_out_ap_vld => backprojection_U0_status_bp_pixels_out_ap_vld,
        status_bp_out_fifo_level => backprojection_U0_status_bp_out_fifo_level,
        status_bp_out_fifo_level_ap_vld => backprojection_U0_status_bp_out_fifo_level_ap_vld,
        status_db_config_loaded => deblur_U0_status_db_config_loaded,
        status_db_config_loaded_ap_vld => deblur_U0_status_db_config_loaded_ap_vld,
        status_db_fsm_state => deblur_U0_status_db_fsm_state,
        status_db_fsm_state_ap_vld => deblur_U0_status_db_fsm_state_ap_vld,
        status_db_param_state => deblur_U0_status_db_param_state,
        status_db_param_state_ap_vld => deblur_U0_status_db_param_state_ap_vld,
        status_db_idx => deblur_U0_status_db_idx,
        status_db_idx_ap_vld => deblur_U0_status_db_idx_ap_vld,
        status_db_pixels_in => deblur_U0_status_db_pixels_in,
        status_db_pixels_in_ap_vld => deblur_U0_status_db_pixels_in_ap_vld,
        status_db_pixels_out => deblur_U0_status_db_pixels_out,
        status_db_pixels_out_ap_vld => deblur_U0_status_db_pixels_out_ap_vld);

    entry_proc_U0 : component deepwaveaccel_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_deblur_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        debl_cfg => debl_cfg,
        debl_cfg_c_din => entry_proc_U0_debl_cfg_c_din,
        debl_cfg_c_full_n => debl_cfg_c_full_n,
        debl_cfg_c_write => entry_proc_U0_debl_cfg_c_write,
        debl_cfg_c_num_data_valid => debl_cfg_c_num_data_valid,
        debl_cfg_c_fifo_cap => debl_cfg_c_fifo_cap);

    goertzel_U0 : component deepwaveaccel_goertzel
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => goertzel_U0_ap_start,
        start_full_n => start_for_crosscor_U0_full_n,
        ap_done => goertzel_U0_ap_done,
        ap_continue => goertzel_U0_ap_continue,
        ap_idle => goertzel_U0_ap_idle,
        ap_ready => goertzel_U0_ap_ready,
        start_out => goertzel_U0_start_out,
        start_write => goertzel_U0_start_write,
        goer_cfg_COS_OMEGA_0 => goer_cfg_COS_OMEGA_0,
        goer_cfg_COS_OMEGA_1 => goer_cfg_COS_OMEGA_1,
        goer_cfg_COS_OMEGA2_0 => goer_cfg_COS_OMEGA2_0,
        goer_cfg_COS_OMEGA2_1 => goer_cfg_COS_OMEGA2_1,
        goer_cfg_SIN_OMEGA_0 => goer_cfg_SIN_OMEGA_0,
        goer_cfg_SIN_OMEGA_1 => goer_cfg_SIN_OMEGA_1,
        in_r_TDATA => in_r_TDATA,
        in_r_TVALID => in_r_TVALID,
        in_r_TREADY => goertzel_U0_in_r_TREADY,
        s_goertzel_din => goertzel_U0_s_goertzel_din,
        s_goertzel_full_n => s_goertzel_full_n,
        s_goertzel_write => goertzel_U0_s_goertzel_write,
        s_goertzel_num_data_valid => s_goertzel_num_data_valid,
        s_goertzel_fifo_cap => s_goertzel_fifo_cap,
        status_gz_samples_in => goertzel_U0_status_gz_samples_in,
        status_gz_samples_in_ap_vld => goertzel_U0_status_gz_samples_in_ap_vld,
        status_gz_sample_win => goertzel_U0_status_gz_sample_win,
        status_gz_sample_win_ap_vld => goertzel_U0_status_gz_sample_win_ap_vld,
        status_gz_samples_out => goertzel_U0_status_gz_samples_out,
        status_gz_samples_out_ap_vld => goertzel_U0_status_gz_samples_out_ap_vld,
        status_gz_samples_out_fifo => goertzel_U0_status_gz_samples_out_fifo,
        status_gz_samples_out_fifo_ap_vld => goertzel_U0_status_gz_samples_out_fifo_ap_vld);

    crosscor_U0 : component deepwaveaccel_crosscor
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => crosscor_U0_ap_start,
        start_full_n => start_for_backprojection_U0_full_n,
        ap_done => crosscor_U0_ap_done,
        ap_continue => crosscor_U0_ap_continue,
        ap_idle => crosscor_U0_ap_idle,
        ap_ready => crosscor_U0_ap_ready,
        start_out => crosscor_U0_start_out,
        start_write => crosscor_U0_start_write,
        s_goertzel_dout => s_goertzel_dout,
        s_goertzel_empty_n => s_goertzel_empty_n,
        s_goertzel_read => crosscor_U0_s_goertzel_read,
        s_goertzel_num_data_valid => s_goertzel_num_data_valid,
        s_goertzel_fifo_cap => s_goertzel_fifo_cap,
        s_xcor_din => crosscor_U0_s_xcor_din,
        s_xcor_full_n => s_xcor_full_n,
        s_xcor_write => crosscor_U0_s_xcor_write,
        s_xcor_num_data_valid => s_xcor_num_data_valid,
        s_xcor_fifo_cap => s_xcor_fifo_cap,
        s_norm_din => crosscor_U0_s_norm_din,
        s_norm_full_n => s_norm_full_n,
        s_norm_write => crosscor_U0_s_norm_write,
        s_norm_num_data_valid => s_norm_num_data_valid,
        s_norm_fifo_cap => s_norm_fifo_cap,
        status_cc_state => crosscor_U0_status_cc_state,
        status_cc_state_ap_vld => crosscor_U0_status_cc_state_ap_vld,
        status_cc_samples_in => crosscor_U0_status_cc_samples_in,
        status_cc_samples_in_ap_vld => crosscor_U0_status_cc_samples_in_ap_vld,
        status_cc_samples_out => crosscor_U0_status_cc_samples_out,
        status_cc_samples_out_ap_vld => crosscor_U0_status_cc_samples_out_ap_vld,
        status_cc_sample_idx => crosscor_U0_status_cc_sample_idx,
        status_cc_sample_idx_ap_vld => crosscor_U0_status_cc_sample_idx_ap_vld,
        status_cc_current_norm => crosscor_U0_status_cc_current_norm,
        status_cc_current_norm_ap_vld => crosscor_U0_status_cc_current_norm_ap_vld,
        status_cc_norms_written => crosscor_U0_status_cc_norms_written,
        status_cc_norms_written_ap_vld => crosscor_U0_status_cc_norms_written_ap_vld,
        status_cc_out_fifo => crosscor_U0_status_cc_out_fifo,
        status_cc_out_fifo_ap_vld => crosscor_U0_status_cc_out_fifo_ap_vld,
        status_cc_norms_fifo => crosscor_U0_status_cc_norms_fifo,
        status_cc_norms_fifo_ap_vld => crosscor_U0_status_cc_norms_fifo_ap_vld);

    backprojection_U0 : component deepwaveaccel_backprojection
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => backprojection_U0_ap_start,
        ap_done => backprojection_U0_ap_done,
        ap_continue => backprojection_U0_ap_continue,
        ap_idle => backprojection_U0_ap_idle,
        ap_ready => backprojection_U0_ap_ready,
        s_xcor_dout => s_xcor_dout,
        s_xcor_empty_n => s_xcor_empty_n,
        s_xcor_read => backprojection_U0_s_xcor_read,
        s_xcor_num_data_valid => s_xcor_num_data_valid,
        s_xcor_fifo_cap => s_xcor_fifo_cap,
        param_bp_TDATA => param_bp_TDATA,
        param_bp_TVALID => param_bp_TVALID,
        param_bp_TREADY => backprojection_U0_param_bp_TREADY,
        s_bp_din => backprojection_U0_s_bp_din,
        s_bp_full_n => s_bp_full_n,
        s_bp_write => backprojection_U0_s_bp_write,
        s_bp_num_data_valid => s_bp_num_data_valid,
        s_bp_fifo_cap => s_bp_fifo_cap,
        status_bp_config_loaded => backprojection_U0_status_bp_config_loaded,
        status_bp_config_loaded_ap_vld => backprojection_U0_status_bp_config_loaded_ap_vld,
        status_bp_fsm_state => backprojection_U0_status_bp_fsm_state,
        status_bp_fsm_state_ap_vld => backprojection_U0_status_bp_fsm_state_ap_vld,
        status_bp_param_state => backprojection_U0_status_bp_param_state,
        status_bp_param_state_ap_vld => backprojection_U0_status_bp_param_state_ap_vld,
        status_bp_idx => backprojection_U0_status_bp_idx,
        status_bp_idx_ap_vld => backprojection_U0_status_bp_idx_ap_vld,
        status_bp_sigmas_in => backprojection_U0_status_bp_sigmas_in,
        status_bp_sigmas_in_ap_vld => backprojection_U0_status_bp_sigmas_in_ap_vld,
        status_bp_pixels_out => backprojection_U0_status_bp_pixels_out,
        status_bp_pixels_out_ap_vld => backprojection_U0_status_bp_pixels_out_ap_vld,
        status_bp_out_fifo_level => backprojection_U0_status_bp_out_fifo_level,
        status_bp_out_fifo_level_ap_vld => backprojection_U0_status_bp_out_fifo_level_ap_vld);

    deblur_U0 : component deepwaveaccel_deblur
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => deblur_U0_ap_start,
        ap_done => deblur_U0_ap_done,
        ap_continue => deblur_U0_ap_continue,
        ap_idle => deblur_U0_ap_idle,
        ap_ready => deblur_U0_ap_ready,
        debl_cfg_dout => debl_cfg_c_dout,
        debl_cfg_empty_n => debl_cfg_c_empty_n,
        debl_cfg_read => deblur_U0_debl_cfg_read,
        debl_cfg_num_data_valid => debl_cfg_c_num_data_valid,
        debl_cfg_fifo_cap => debl_cfg_c_fifo_cap,
        s_bp_dout => s_bp_dout,
        s_bp_empty_n => s_bp_empty_n,
        s_bp_read => deblur_U0_s_bp_read,
        s_bp_num_data_valid => s_bp_num_data_valid,
        s_bp_fifo_cap => s_bp_fifo_cap,
        param_db_TDATA => param_db_TDATA,
        param_db_TVALID => param_db_TVALID,
        param_db_TREADY => deblur_U0_param_db_TREADY,
        out_r_TDATA => deblur_U0_out_r_TDATA,
        out_r_TVALID => deblur_U0_out_r_TVALID,
        out_r_TREADY => out_r_TREADY,
        out_r_TLAST => deblur_U0_out_r_TLAST,
        s_norm_dout => s_norm_dout,
        s_norm_empty_n => s_norm_empty_n,
        s_norm_read => deblur_U0_s_norm_read,
        s_norm_num_data_valid => s_norm_num_data_valid,
        s_norm_fifo_cap => s_norm_fifo_cap,
        status_db_config_loaded => deblur_U0_status_db_config_loaded,
        status_db_config_loaded_ap_vld => deblur_U0_status_db_config_loaded_ap_vld,
        status_db_fsm_state => deblur_U0_status_db_fsm_state,
        status_db_fsm_state_ap_vld => deblur_U0_status_db_fsm_state_ap_vld,
        status_db_param_state => deblur_U0_status_db_param_state,
        status_db_param_state_ap_vld => deblur_U0_status_db_param_state_ap_vld,
        status_db_idx => deblur_U0_status_db_idx,
        status_db_idx_ap_vld => deblur_U0_status_db_idx_ap_vld,
        status_db_pixels_in => deblur_U0_status_db_pixels_in,
        status_db_pixels_in_ap_vld => deblur_U0_status_db_pixels_in_ap_vld,
        status_db_pixels_out => deblur_U0_status_db_pixels_out,
        status_db_pixels_out_ap_vld => deblur_U0_status_db_pixels_out_ap_vld);

    debl_cfg_c_U : component deepwaveaccel_fifo_w8_d5_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_debl_cfg_c_din,
        if_full_n => debl_cfg_c_full_n,
        if_write => entry_proc_U0_debl_cfg_c_write,
        if_dout => debl_cfg_c_dout,
        if_empty_n => debl_cfg_c_empty_n,
        if_read => deblur_U0_debl_cfg_read,
        if_num_data_valid => debl_cfg_c_num_data_valid,
        if_fifo_cap => debl_cfg_c_fifo_cap);

    s_goertzel_U : component deepwaveaccel_fifo_w36_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => goertzel_U0_s_goertzel_din,
        if_full_n => s_goertzel_full_n,
        if_write => goertzel_U0_s_goertzel_write,
        if_dout => s_goertzel_dout,
        if_empty_n => s_goertzel_empty_n,
        if_read => crosscor_U0_s_goertzel_read,
        if_num_data_valid => s_goertzel_num_data_valid,
        if_fifo_cap => s_goertzel_fifo_cap);

    s_xcor_U : component deepwaveaccel_fifo_w36_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => crosscor_U0_s_xcor_din,
        if_full_n => s_xcor_full_n,
        if_write => crosscor_U0_s_xcor_write,
        if_dout => s_xcor_dout,
        if_empty_n => s_xcor_empty_n,
        if_read => backprojection_U0_s_xcor_read,
        if_num_data_valid => s_xcor_num_data_valid,
        if_fifo_cap => s_xcor_fifo_cap);

    s_norm_U : component deepwaveaccel_fifo_w25_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => crosscor_U0_s_norm_din,
        if_full_n => s_norm_full_n,
        if_write => crosscor_U0_s_norm_write,
        if_dout => s_norm_dout,
        if_empty_n => s_norm_empty_n,
        if_read => deblur_U0_s_norm_read,
        if_num_data_valid => s_norm_num_data_valid,
        if_fifo_cap => s_norm_fifo_cap);

    s_bp_U : component deepwaveaccel_fifo_w18_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => backprojection_U0_s_bp_din,
        if_full_n => s_bp_full_n,
        if_write => backprojection_U0_s_bp_write,
        if_dout => s_bp_dout,
        if_empty_n => s_bp_empty_n,
        if_read => deblur_U0_s_bp_read,
        if_num_data_valid => s_bp_num_data_valid,
        if_fifo_cap => s_bp_fifo_cap);

    start_for_deblur_U0_U : component deepwaveaccel_start_for_deblur_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_deblur_U0_din,
        if_full_n => start_for_deblur_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_deblur_U0_dout,
        if_empty_n => start_for_deblur_U0_empty_n,
        if_read => deblur_U0_ap_ready);

    start_for_crosscor_U0_U : component deepwaveaccel_start_for_crosscor_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_crosscor_U0_din,
        if_full_n => start_for_crosscor_U0_full_n,
        if_write => goertzel_U0_start_write,
        if_dout => start_for_crosscor_U0_dout,
        if_empty_n => start_for_crosscor_U0_empty_n,
        if_read => crosscor_U0_ap_ready);

    start_for_backprojection_U0_U : component deepwaveaccel_start_for_backprojection_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_backprojection_U0_din,
        if_full_n => start_for_backprojection_U0_full_n,
        if_write => crosscor_U0_start_write,
        if_dout => start_for_backprojection_U0_dout,
        if_empty_n => start_for_backprojection_U0_empty_n,
        if_read => backprojection_U0_ap_ready);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    backprojection_U0_ap_continue <= ap_const_logic_1;
    backprojection_U0_ap_start <= start_for_backprojection_U0_empty_n;
    crosscor_U0_ap_continue <= ap_const_logic_1;
    crosscor_U0_ap_start <= start_for_crosscor_U0_empty_n;
    deblur_U0_ap_continue <= ap_const_logic_1;
    deblur_U0_ap_start <= start_for_deblur_U0_empty_n;
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ap_const_logic_1;
    goertzel_U0_ap_continue <= ap_const_logic_1;
    goertzel_U0_ap_start <= ap_const_logic_1;
    in_r_TREADY <= goertzel_U0_in_r_TREADY;
    out_r_TDATA <= deblur_U0_out_r_TDATA;
    out_r_TLAST <= deblur_U0_out_r_TLAST;
    out_r_TVALID <= deblur_U0_out_r_TVALID;
    param_bp_TREADY <= backprojection_U0_param_bp_TREADY;
    param_db_TREADY <= deblur_U0_param_db_TREADY;
    start_for_backprojection_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_crosscor_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_deblur_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
