// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module deepwaveaccel_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        debl_cfg_n_layers,
        debl_cfg_n_layers_c_din,
        debl_cfg_n_layers_c_full_n,
        debl_cfg_n_layers_c_write,
        debl_cfg_n_layers_c_num_data_valid,
        debl_cfg_n_layers_c_fifo_cap,
        debl_cfg_K,
        debl_cfg_K_c_din,
        debl_cfg_K_c_full_n,
        debl_cfg_K_c_write,
        debl_cfg_K_c_num_data_valid,
        debl_cfg_K_c_fifo_cap,
        debl_cfg_lap_off_0,
        debl_cfg_lap_off_0_c_din,
        debl_cfg_lap_off_0_c_full_n,
        debl_cfg_lap_off_0_c_write,
        debl_cfg_lap_off_0_c_num_data_valid,
        debl_cfg_lap_off_0_c_fifo_cap,
        debl_cfg_lap_off_1,
        debl_cfg_lap_off_1_c_din,
        debl_cfg_lap_off_1_c_full_n,
        debl_cfg_lap_off_1_c_write,
        debl_cfg_lap_off_1_c_num_data_valid,
        debl_cfg_lap_off_1_c_fifo_cap,
        debl_cfg_lap_off_2,
        debl_cfg_lap_off_2_c_din,
        debl_cfg_lap_off_2_c_full_n,
        debl_cfg_lap_off_2_c_write,
        debl_cfg_lap_off_2_c_num_data_valid,
        debl_cfg_lap_off_2_c_fifo_cap,
        debl_cfg_lap_off_3,
        debl_cfg_lap_off_3_c_din,
        debl_cfg_lap_off_3_c_full_n,
        debl_cfg_lap_off_3_c_write,
        debl_cfg_lap_off_3_c_num_data_valid,
        debl_cfg_lap_off_3_c_fifo_cap,
        debl_cfg_lap_off_4,
        debl_cfg_lap_off_4_c_din,
        debl_cfg_lap_off_4_c_full_n,
        debl_cfg_lap_off_4_c_write,
        debl_cfg_lap_off_4_c_num_data_valid,
        debl_cfg_lap_off_4_c_fifo_cap,
        debl_cfg_lap_off_5,
        debl_cfg_lap_off_5_c_din,
        debl_cfg_lap_off_5_c_full_n,
        debl_cfg_lap_off_5_c_write,
        debl_cfg_lap_off_5_c_num_data_valid,
        debl_cfg_lap_off_5_c_fifo_cap,
        debl_cfg_theta_0,
        debl_cfg_theta_0_c_din,
        debl_cfg_theta_0_c_full_n,
        debl_cfg_theta_0_c_write,
        debl_cfg_theta_0_c_num_data_valid,
        debl_cfg_theta_0_c_fifo_cap,
        debl_cfg_theta_1,
        debl_cfg_theta_1_c_din,
        debl_cfg_theta_1_c_full_n,
        debl_cfg_theta_1_c_write,
        debl_cfg_theta_1_c_num_data_valid,
        debl_cfg_theta_1_c_fifo_cap,
        debl_cfg_theta_2,
        debl_cfg_theta_2_c_din,
        debl_cfg_theta_2_c_full_n,
        debl_cfg_theta_2_c_write,
        debl_cfg_theta_2_c_num_data_valid,
        debl_cfg_theta_2_c_fifo_cap,
        debl_cfg_theta_3,
        debl_cfg_theta_3_c_din,
        debl_cfg_theta_3_c_full_n,
        debl_cfg_theta_3_c_write,
        debl_cfg_theta_3_c_num_data_valid,
        debl_cfg_theta_3_c_fifo_cap,
        debl_cfg_theta_4,
        debl_cfg_theta_4_c_din,
        debl_cfg_theta_4_c_full_n,
        debl_cfg_theta_4_c_write,
        debl_cfg_theta_4_c_num_data_valid,
        debl_cfg_theta_4_c_fifo_cap,
        debl_cfg_theta_5,
        debl_cfg_theta_5_c_din,
        debl_cfg_theta_5_c_full_n,
        debl_cfg_theta_5_c_write,
        debl_cfg_theta_5_c_num_data_valid,
        debl_cfg_theta_5_c_fifo_cap,
        debl_cfg_theta_6,
        debl_cfg_theta_6_c_din,
        debl_cfg_theta_6_c_full_n,
        debl_cfg_theta_6_c_write,
        debl_cfg_theta_6_c_num_data_valid,
        debl_cfg_theta_6_c_fifo_cap,
        debl_cfg_theta_7,
        debl_cfg_theta_7_c_din,
        debl_cfg_theta_7_c_full_n,
        debl_cfg_theta_7_c_write,
        debl_cfg_theta_7_c_num_data_valid,
        debl_cfg_theta_7_c_fifo_cap,
        debl_cfg_theta_8,
        debl_cfg_theta_8_c_din,
        debl_cfg_theta_8_c_full_n,
        debl_cfg_theta_8_c_write,
        debl_cfg_theta_8_c_num_data_valid,
        debl_cfg_theta_8_c_fifo_cap,
        debl_cfg_theta_9,
        debl_cfg_theta_9_c_din,
        debl_cfg_theta_9_c_full_n,
        debl_cfg_theta_9_c_write,
        debl_cfg_theta_9_c_num_data_valid,
        debl_cfg_theta_9_c_fifo_cap,
        debl_cfg_theta_10,
        debl_cfg_theta_10_c_din,
        debl_cfg_theta_10_c_full_n,
        debl_cfg_theta_10_c_write,
        debl_cfg_theta_10_c_num_data_valid,
        debl_cfg_theta_10_c_fifo_cap,
        debl_cfg_theta_11,
        debl_cfg_theta_11_c_din,
        debl_cfg_theta_11_c_full_n,
        debl_cfg_theta_11_c_write,
        debl_cfg_theta_11_c_num_data_valid,
        debl_cfg_theta_11_c_fifo_cap,
        debl_cfg_theta_12,
        debl_cfg_theta_12_c_din,
        debl_cfg_theta_12_c_full_n,
        debl_cfg_theta_12_c_write,
        debl_cfg_theta_12_c_num_data_valid,
        debl_cfg_theta_12_c_fifo_cap,
        debl_cfg_theta_13,
        debl_cfg_theta_13_c_din,
        debl_cfg_theta_13_c_full_n,
        debl_cfg_theta_13_c_write,
        debl_cfg_theta_13_c_num_data_valid,
        debl_cfg_theta_13_c_fifo_cap,
        debl_cfg_theta_14,
        debl_cfg_theta_14_c_din,
        debl_cfg_theta_14_c_full_n,
        debl_cfg_theta_14_c_write,
        debl_cfg_theta_14_c_num_data_valid,
        debl_cfg_theta_14_c_fifo_cap,
        debl_cfg_theta_15,
        debl_cfg_theta_15_c_din,
        debl_cfg_theta_15_c_full_n,
        debl_cfg_theta_15_c_write,
        debl_cfg_theta_15_c_num_data_valid,
        debl_cfg_theta_15_c_fifo_cap,
        debl_cfg_theta_16,
        debl_cfg_theta_16_c_din,
        debl_cfg_theta_16_c_full_n,
        debl_cfg_theta_16_c_write,
        debl_cfg_theta_16_c_num_data_valid,
        debl_cfg_theta_16_c_fifo_cap,
        debl_cfg_theta_17,
        debl_cfg_theta_17_c_din,
        debl_cfg_theta_17_c_full_n,
        debl_cfg_theta_17_c_write,
        debl_cfg_theta_17_c_num_data_valid,
        debl_cfg_theta_17_c_fifo_cap,
        debl_cfg_theta_18,
        debl_cfg_theta_18_c_din,
        debl_cfg_theta_18_c_full_n,
        debl_cfg_theta_18_c_write,
        debl_cfg_theta_18_c_num_data_valid,
        debl_cfg_theta_18_c_fifo_cap,
        debl_cfg_theta_19,
        debl_cfg_theta_19_c_din,
        debl_cfg_theta_19_c_full_n,
        debl_cfg_theta_19_c_write,
        debl_cfg_theta_19_c_num_data_valid,
        debl_cfg_theta_19_c_fifo_cap,
        debl_cfg_theta_20,
        debl_cfg_theta_20_c_din,
        debl_cfg_theta_20_c_full_n,
        debl_cfg_theta_20_c_write,
        debl_cfg_theta_20_c_num_data_valid,
        debl_cfg_theta_20_c_fifo_cap,
        debl_cfg_theta_21,
        debl_cfg_theta_21_c_din,
        debl_cfg_theta_21_c_full_n,
        debl_cfg_theta_21_c_write,
        debl_cfg_theta_21_c_num_data_valid,
        debl_cfg_theta_21_c_fifo_cap,
        debl_cfg_theta_22,
        debl_cfg_theta_22_c_din,
        debl_cfg_theta_22_c_full_n,
        debl_cfg_theta_22_c_write,
        debl_cfg_theta_22_c_num_data_valid,
        debl_cfg_theta_22_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] debl_cfg_n_layers;
output  [7:0] debl_cfg_n_layers_c_din;
input   debl_cfg_n_layers_c_full_n;
output   debl_cfg_n_layers_c_write;
input  [3:0] debl_cfg_n_layers_c_num_data_valid;
input  [3:0] debl_cfg_n_layers_c_fifo_cap;
input  [5:0] debl_cfg_K;
output  [5:0] debl_cfg_K_c_din;
input   debl_cfg_K_c_full_n;
output   debl_cfg_K_c_write;
input  [3:0] debl_cfg_K_c_num_data_valid;
input  [3:0] debl_cfg_K_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_0;
output  [11:0] debl_cfg_lap_off_0_c_din;
input   debl_cfg_lap_off_0_c_full_n;
output   debl_cfg_lap_off_0_c_write;
input  [3:0] debl_cfg_lap_off_0_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_0_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_1;
output  [11:0] debl_cfg_lap_off_1_c_din;
input   debl_cfg_lap_off_1_c_full_n;
output   debl_cfg_lap_off_1_c_write;
input  [3:0] debl_cfg_lap_off_1_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_1_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_2;
output  [11:0] debl_cfg_lap_off_2_c_din;
input   debl_cfg_lap_off_2_c_full_n;
output   debl_cfg_lap_off_2_c_write;
input  [3:0] debl_cfg_lap_off_2_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_2_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_3;
output  [11:0] debl_cfg_lap_off_3_c_din;
input   debl_cfg_lap_off_3_c_full_n;
output   debl_cfg_lap_off_3_c_write;
input  [3:0] debl_cfg_lap_off_3_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_3_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_4;
output  [11:0] debl_cfg_lap_off_4_c_din;
input   debl_cfg_lap_off_4_c_full_n;
output   debl_cfg_lap_off_4_c_write;
input  [3:0] debl_cfg_lap_off_4_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_4_c_fifo_cap;
input  [11:0] debl_cfg_lap_off_5;
output  [11:0] debl_cfg_lap_off_5_c_din;
input   debl_cfg_lap_off_5_c_full_n;
output   debl_cfg_lap_off_5_c_write;
input  [3:0] debl_cfg_lap_off_5_c_num_data_valid;
input  [3:0] debl_cfg_lap_off_5_c_fifo_cap;
input  [17:0] debl_cfg_theta_0;
output  [17:0] debl_cfg_theta_0_c_din;
input   debl_cfg_theta_0_c_full_n;
output   debl_cfg_theta_0_c_write;
input  [3:0] debl_cfg_theta_0_c_num_data_valid;
input  [3:0] debl_cfg_theta_0_c_fifo_cap;
input  [17:0] debl_cfg_theta_1;
output  [17:0] debl_cfg_theta_1_c_din;
input   debl_cfg_theta_1_c_full_n;
output   debl_cfg_theta_1_c_write;
input  [3:0] debl_cfg_theta_1_c_num_data_valid;
input  [3:0] debl_cfg_theta_1_c_fifo_cap;
input  [17:0] debl_cfg_theta_2;
output  [17:0] debl_cfg_theta_2_c_din;
input   debl_cfg_theta_2_c_full_n;
output   debl_cfg_theta_2_c_write;
input  [3:0] debl_cfg_theta_2_c_num_data_valid;
input  [3:0] debl_cfg_theta_2_c_fifo_cap;
input  [17:0] debl_cfg_theta_3;
output  [17:0] debl_cfg_theta_3_c_din;
input   debl_cfg_theta_3_c_full_n;
output   debl_cfg_theta_3_c_write;
input  [3:0] debl_cfg_theta_3_c_num_data_valid;
input  [3:0] debl_cfg_theta_3_c_fifo_cap;
input  [17:0] debl_cfg_theta_4;
output  [17:0] debl_cfg_theta_4_c_din;
input   debl_cfg_theta_4_c_full_n;
output   debl_cfg_theta_4_c_write;
input  [3:0] debl_cfg_theta_4_c_num_data_valid;
input  [3:0] debl_cfg_theta_4_c_fifo_cap;
input  [17:0] debl_cfg_theta_5;
output  [17:0] debl_cfg_theta_5_c_din;
input   debl_cfg_theta_5_c_full_n;
output   debl_cfg_theta_5_c_write;
input  [3:0] debl_cfg_theta_5_c_num_data_valid;
input  [3:0] debl_cfg_theta_5_c_fifo_cap;
input  [17:0] debl_cfg_theta_6;
output  [17:0] debl_cfg_theta_6_c_din;
input   debl_cfg_theta_6_c_full_n;
output   debl_cfg_theta_6_c_write;
input  [3:0] debl_cfg_theta_6_c_num_data_valid;
input  [3:0] debl_cfg_theta_6_c_fifo_cap;
input  [17:0] debl_cfg_theta_7;
output  [17:0] debl_cfg_theta_7_c_din;
input   debl_cfg_theta_7_c_full_n;
output   debl_cfg_theta_7_c_write;
input  [3:0] debl_cfg_theta_7_c_num_data_valid;
input  [3:0] debl_cfg_theta_7_c_fifo_cap;
input  [17:0] debl_cfg_theta_8;
output  [17:0] debl_cfg_theta_8_c_din;
input   debl_cfg_theta_8_c_full_n;
output   debl_cfg_theta_8_c_write;
input  [3:0] debl_cfg_theta_8_c_num_data_valid;
input  [3:0] debl_cfg_theta_8_c_fifo_cap;
input  [17:0] debl_cfg_theta_9;
output  [17:0] debl_cfg_theta_9_c_din;
input   debl_cfg_theta_9_c_full_n;
output   debl_cfg_theta_9_c_write;
input  [3:0] debl_cfg_theta_9_c_num_data_valid;
input  [3:0] debl_cfg_theta_9_c_fifo_cap;
input  [17:0] debl_cfg_theta_10;
output  [17:0] debl_cfg_theta_10_c_din;
input   debl_cfg_theta_10_c_full_n;
output   debl_cfg_theta_10_c_write;
input  [3:0] debl_cfg_theta_10_c_num_data_valid;
input  [3:0] debl_cfg_theta_10_c_fifo_cap;
input  [17:0] debl_cfg_theta_11;
output  [17:0] debl_cfg_theta_11_c_din;
input   debl_cfg_theta_11_c_full_n;
output   debl_cfg_theta_11_c_write;
input  [3:0] debl_cfg_theta_11_c_num_data_valid;
input  [3:0] debl_cfg_theta_11_c_fifo_cap;
input  [17:0] debl_cfg_theta_12;
output  [17:0] debl_cfg_theta_12_c_din;
input   debl_cfg_theta_12_c_full_n;
output   debl_cfg_theta_12_c_write;
input  [3:0] debl_cfg_theta_12_c_num_data_valid;
input  [3:0] debl_cfg_theta_12_c_fifo_cap;
input  [17:0] debl_cfg_theta_13;
output  [17:0] debl_cfg_theta_13_c_din;
input   debl_cfg_theta_13_c_full_n;
output   debl_cfg_theta_13_c_write;
input  [3:0] debl_cfg_theta_13_c_num_data_valid;
input  [3:0] debl_cfg_theta_13_c_fifo_cap;
input  [17:0] debl_cfg_theta_14;
output  [17:0] debl_cfg_theta_14_c_din;
input   debl_cfg_theta_14_c_full_n;
output   debl_cfg_theta_14_c_write;
input  [3:0] debl_cfg_theta_14_c_num_data_valid;
input  [3:0] debl_cfg_theta_14_c_fifo_cap;
input  [17:0] debl_cfg_theta_15;
output  [17:0] debl_cfg_theta_15_c_din;
input   debl_cfg_theta_15_c_full_n;
output   debl_cfg_theta_15_c_write;
input  [3:0] debl_cfg_theta_15_c_num_data_valid;
input  [3:0] debl_cfg_theta_15_c_fifo_cap;
input  [17:0] debl_cfg_theta_16;
output  [17:0] debl_cfg_theta_16_c_din;
input   debl_cfg_theta_16_c_full_n;
output   debl_cfg_theta_16_c_write;
input  [3:0] debl_cfg_theta_16_c_num_data_valid;
input  [3:0] debl_cfg_theta_16_c_fifo_cap;
input  [17:0] debl_cfg_theta_17;
output  [17:0] debl_cfg_theta_17_c_din;
input   debl_cfg_theta_17_c_full_n;
output   debl_cfg_theta_17_c_write;
input  [3:0] debl_cfg_theta_17_c_num_data_valid;
input  [3:0] debl_cfg_theta_17_c_fifo_cap;
input  [17:0] debl_cfg_theta_18;
output  [17:0] debl_cfg_theta_18_c_din;
input   debl_cfg_theta_18_c_full_n;
output   debl_cfg_theta_18_c_write;
input  [3:0] debl_cfg_theta_18_c_num_data_valid;
input  [3:0] debl_cfg_theta_18_c_fifo_cap;
input  [17:0] debl_cfg_theta_19;
output  [17:0] debl_cfg_theta_19_c_din;
input   debl_cfg_theta_19_c_full_n;
output   debl_cfg_theta_19_c_write;
input  [3:0] debl_cfg_theta_19_c_num_data_valid;
input  [3:0] debl_cfg_theta_19_c_fifo_cap;
input  [17:0] debl_cfg_theta_20;
output  [17:0] debl_cfg_theta_20_c_din;
input   debl_cfg_theta_20_c_full_n;
output   debl_cfg_theta_20_c_write;
input  [3:0] debl_cfg_theta_20_c_num_data_valid;
input  [3:0] debl_cfg_theta_20_c_fifo_cap;
input  [17:0] debl_cfg_theta_21;
output  [17:0] debl_cfg_theta_21_c_din;
input   debl_cfg_theta_21_c_full_n;
output   debl_cfg_theta_21_c_write;
input  [3:0] debl_cfg_theta_21_c_num_data_valid;
input  [3:0] debl_cfg_theta_21_c_fifo_cap;
input  [17:0] debl_cfg_theta_22;
output  [17:0] debl_cfg_theta_22_c_din;
input   debl_cfg_theta_22_c_full_n;
output   debl_cfg_theta_22_c_write;
input  [3:0] debl_cfg_theta_22_c_num_data_valid;
input  [3:0] debl_cfg_theta_22_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg debl_cfg_n_layers_c_write;
reg debl_cfg_K_c_write;
reg debl_cfg_lap_off_0_c_write;
reg debl_cfg_lap_off_1_c_write;
reg debl_cfg_lap_off_2_c_write;
reg debl_cfg_lap_off_3_c_write;
reg debl_cfg_lap_off_4_c_write;
reg debl_cfg_lap_off_5_c_write;
reg debl_cfg_theta_0_c_write;
reg debl_cfg_theta_1_c_write;
reg debl_cfg_theta_2_c_write;
reg debl_cfg_theta_3_c_write;
reg debl_cfg_theta_4_c_write;
reg debl_cfg_theta_5_c_write;
reg debl_cfg_theta_6_c_write;
reg debl_cfg_theta_7_c_write;
reg debl_cfg_theta_8_c_write;
reg debl_cfg_theta_9_c_write;
reg debl_cfg_theta_10_c_write;
reg debl_cfg_theta_11_c_write;
reg debl_cfg_theta_12_c_write;
reg debl_cfg_theta_13_c_write;
reg debl_cfg_theta_14_c_write;
reg debl_cfg_theta_15_c_write;
reg debl_cfg_theta_16_c_write;
reg debl_cfg_theta_17_c_write;
reg debl_cfg_theta_18_c_write;
reg debl_cfg_theta_19_c_write;
reg debl_cfg_theta_20_c_write;
reg debl_cfg_theta_21_c_write;
reg debl_cfg_theta_22_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    debl_cfg_n_layers_c_blk_n;
reg    debl_cfg_K_c_blk_n;
reg    debl_cfg_lap_off_0_c_blk_n;
reg    debl_cfg_lap_off_1_c_blk_n;
reg    debl_cfg_lap_off_2_c_blk_n;
reg    debl_cfg_lap_off_3_c_blk_n;
reg    debl_cfg_lap_off_4_c_blk_n;
reg    debl_cfg_lap_off_5_c_blk_n;
reg    debl_cfg_theta_0_c_blk_n;
reg    debl_cfg_theta_1_c_blk_n;
reg    debl_cfg_theta_2_c_blk_n;
reg    debl_cfg_theta_3_c_blk_n;
reg    debl_cfg_theta_4_c_blk_n;
reg    debl_cfg_theta_5_c_blk_n;
reg    debl_cfg_theta_6_c_blk_n;
reg    debl_cfg_theta_7_c_blk_n;
reg    debl_cfg_theta_8_c_blk_n;
reg    debl_cfg_theta_9_c_blk_n;
reg    debl_cfg_theta_10_c_blk_n;
reg    debl_cfg_theta_11_c_blk_n;
reg    debl_cfg_theta_12_c_blk_n;
reg    debl_cfg_theta_13_c_blk_n;
reg    debl_cfg_theta_14_c_blk_n;
reg    debl_cfg_theta_15_c_blk_n;
reg    debl_cfg_theta_16_c_blk_n;
reg    debl_cfg_theta_17_c_blk_n;
reg    debl_cfg_theta_18_c_blk_n;
reg    debl_cfg_theta_19_c_blk_n;
reg    debl_cfg_theta_20_c_blk_n;
reg    debl_cfg_theta_21_c_blk_n;
reg    debl_cfg_theta_22_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_K_c_blk_n = debl_cfg_K_c_full_n;
    end else begin
        debl_cfg_K_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_K_c_write = 1'b1;
    end else begin
        debl_cfg_K_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_0_c_blk_n = debl_cfg_lap_off_0_c_full_n;
    end else begin
        debl_cfg_lap_off_0_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_0_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_0_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_1_c_blk_n = debl_cfg_lap_off_1_c_full_n;
    end else begin
        debl_cfg_lap_off_1_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_1_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_1_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_2_c_blk_n = debl_cfg_lap_off_2_c_full_n;
    end else begin
        debl_cfg_lap_off_2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_2_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_3_c_blk_n = debl_cfg_lap_off_3_c_full_n;
    end else begin
        debl_cfg_lap_off_3_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_3_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_3_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_4_c_blk_n = debl_cfg_lap_off_4_c_full_n;
    end else begin
        debl_cfg_lap_off_4_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_4_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_4_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_5_c_blk_n = debl_cfg_lap_off_5_c_full_n;
    end else begin
        debl_cfg_lap_off_5_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_lap_off_5_c_write = 1'b1;
    end else begin
        debl_cfg_lap_off_5_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_n_layers_c_blk_n = debl_cfg_n_layers_c_full_n;
    end else begin
        debl_cfg_n_layers_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_n_layers_c_write = 1'b1;
    end else begin
        debl_cfg_n_layers_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_0_c_blk_n = debl_cfg_theta_0_c_full_n;
    end else begin
        debl_cfg_theta_0_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_0_c_write = 1'b1;
    end else begin
        debl_cfg_theta_0_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_10_c_blk_n = debl_cfg_theta_10_c_full_n;
    end else begin
        debl_cfg_theta_10_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_10_c_write = 1'b1;
    end else begin
        debl_cfg_theta_10_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_11_c_blk_n = debl_cfg_theta_11_c_full_n;
    end else begin
        debl_cfg_theta_11_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_11_c_write = 1'b1;
    end else begin
        debl_cfg_theta_11_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_12_c_blk_n = debl_cfg_theta_12_c_full_n;
    end else begin
        debl_cfg_theta_12_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_12_c_write = 1'b1;
    end else begin
        debl_cfg_theta_12_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_13_c_blk_n = debl_cfg_theta_13_c_full_n;
    end else begin
        debl_cfg_theta_13_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_13_c_write = 1'b1;
    end else begin
        debl_cfg_theta_13_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_14_c_blk_n = debl_cfg_theta_14_c_full_n;
    end else begin
        debl_cfg_theta_14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_14_c_write = 1'b1;
    end else begin
        debl_cfg_theta_14_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_15_c_blk_n = debl_cfg_theta_15_c_full_n;
    end else begin
        debl_cfg_theta_15_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_15_c_write = 1'b1;
    end else begin
        debl_cfg_theta_15_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_16_c_blk_n = debl_cfg_theta_16_c_full_n;
    end else begin
        debl_cfg_theta_16_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_16_c_write = 1'b1;
    end else begin
        debl_cfg_theta_16_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_17_c_blk_n = debl_cfg_theta_17_c_full_n;
    end else begin
        debl_cfg_theta_17_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_17_c_write = 1'b1;
    end else begin
        debl_cfg_theta_17_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_18_c_blk_n = debl_cfg_theta_18_c_full_n;
    end else begin
        debl_cfg_theta_18_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_18_c_write = 1'b1;
    end else begin
        debl_cfg_theta_18_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_19_c_blk_n = debl_cfg_theta_19_c_full_n;
    end else begin
        debl_cfg_theta_19_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_19_c_write = 1'b1;
    end else begin
        debl_cfg_theta_19_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_1_c_blk_n = debl_cfg_theta_1_c_full_n;
    end else begin
        debl_cfg_theta_1_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_1_c_write = 1'b1;
    end else begin
        debl_cfg_theta_1_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_20_c_blk_n = debl_cfg_theta_20_c_full_n;
    end else begin
        debl_cfg_theta_20_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_20_c_write = 1'b1;
    end else begin
        debl_cfg_theta_20_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_21_c_blk_n = debl_cfg_theta_21_c_full_n;
    end else begin
        debl_cfg_theta_21_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_21_c_write = 1'b1;
    end else begin
        debl_cfg_theta_21_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_22_c_blk_n = debl_cfg_theta_22_c_full_n;
    end else begin
        debl_cfg_theta_22_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_22_c_write = 1'b1;
    end else begin
        debl_cfg_theta_22_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_2_c_blk_n = debl_cfg_theta_2_c_full_n;
    end else begin
        debl_cfg_theta_2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_2_c_write = 1'b1;
    end else begin
        debl_cfg_theta_2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_3_c_blk_n = debl_cfg_theta_3_c_full_n;
    end else begin
        debl_cfg_theta_3_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_3_c_write = 1'b1;
    end else begin
        debl_cfg_theta_3_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_4_c_blk_n = debl_cfg_theta_4_c_full_n;
    end else begin
        debl_cfg_theta_4_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_4_c_write = 1'b1;
    end else begin
        debl_cfg_theta_4_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_5_c_blk_n = debl_cfg_theta_5_c_full_n;
    end else begin
        debl_cfg_theta_5_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_5_c_write = 1'b1;
    end else begin
        debl_cfg_theta_5_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_6_c_blk_n = debl_cfg_theta_6_c_full_n;
    end else begin
        debl_cfg_theta_6_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_6_c_write = 1'b1;
    end else begin
        debl_cfg_theta_6_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_7_c_blk_n = debl_cfg_theta_7_c_full_n;
    end else begin
        debl_cfg_theta_7_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_7_c_write = 1'b1;
    end else begin
        debl_cfg_theta_7_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_8_c_blk_n = debl_cfg_theta_8_c_full_n;
    end else begin
        debl_cfg_theta_8_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_8_c_write = 1'b1;
    end else begin
        debl_cfg_theta_8_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_9_c_blk_n = debl_cfg_theta_9_c_full_n;
    end else begin
        debl_cfg_theta_9_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        debl_cfg_theta_9_c_write = 1'b1;
    end else begin
        debl_cfg_theta_9_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((debl_cfg_theta_0_c_full_n == 1'b0) | (debl_cfg_lap_off_5_c_full_n == 1'b0) | (debl_cfg_lap_off_4_c_full_n == 1'b0) | (real_start == 1'b0) | (debl_cfg_lap_off_3_c_full_n == 1'b0) | (debl_cfg_lap_off_2_c_full_n == 1'b0) | (debl_cfg_lap_off_1_c_full_n == 1'b0) | (debl_cfg_lap_off_0_c_full_n == 1'b0) | (debl_cfg_K_c_full_n == 1'b0) | (debl_cfg_n_layers_c_full_n == 1'b0) | (debl_cfg_theta_22_c_full_n == 1'b0) | (debl_cfg_theta_21_c_full_n == 1'b0) | (debl_cfg_theta_20_c_full_n == 1'b0) | (debl_cfg_theta_19_c_full_n == 1'b0) | (debl_cfg_theta_18_c_full_n == 1'b0) | (debl_cfg_theta_17_c_full_n == 1'b0) | (debl_cfg_theta_16_c_full_n == 1'b0) | (debl_cfg_theta_15_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (debl_cfg_theta_14_c_full_n == 1'b0) | (debl_cfg_theta_13_c_full_n == 1'b0) | (debl_cfg_theta_12_c_full_n == 1'b0) | (debl_cfg_theta_11_c_full_n == 1'b0) | (debl_cfg_theta_10_c_full_n == 1'b0) | (debl_cfg_theta_9_c_full_n == 1'b0) | (debl_cfg_theta_8_c_full_n == 1'b0) | (debl_cfg_theta_7_c_full_n == 1'b0) | (debl_cfg_theta_6_c_full_n 
    == 1'b0) | (debl_cfg_theta_5_c_full_n == 1'b0) | (debl_cfg_theta_4_c_full_n == 1'b0) | (debl_cfg_theta_3_c_full_n == 1'b0) | (debl_cfg_theta_2_c_full_n == 1'b0) | (debl_cfg_theta_1_c_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign debl_cfg_K_c_din = debl_cfg_K;

assign debl_cfg_lap_off_0_c_din = debl_cfg_lap_off_0;

assign debl_cfg_lap_off_1_c_din = debl_cfg_lap_off_1;

assign debl_cfg_lap_off_2_c_din = debl_cfg_lap_off_2;

assign debl_cfg_lap_off_3_c_din = debl_cfg_lap_off_3;

assign debl_cfg_lap_off_4_c_din = debl_cfg_lap_off_4;

assign debl_cfg_lap_off_5_c_din = debl_cfg_lap_off_5;

assign debl_cfg_n_layers_c_din = debl_cfg_n_layers;

assign debl_cfg_theta_0_c_din = debl_cfg_theta_0;

assign debl_cfg_theta_10_c_din = debl_cfg_theta_10;

assign debl_cfg_theta_11_c_din = debl_cfg_theta_11;

assign debl_cfg_theta_12_c_din = debl_cfg_theta_12;

assign debl_cfg_theta_13_c_din = debl_cfg_theta_13;

assign debl_cfg_theta_14_c_din = debl_cfg_theta_14;

assign debl_cfg_theta_15_c_din = debl_cfg_theta_15;

assign debl_cfg_theta_16_c_din = debl_cfg_theta_16;

assign debl_cfg_theta_17_c_din = debl_cfg_theta_17;

assign debl_cfg_theta_18_c_din = debl_cfg_theta_18;

assign debl_cfg_theta_19_c_din = debl_cfg_theta_19;

assign debl_cfg_theta_1_c_din = debl_cfg_theta_1;

assign debl_cfg_theta_20_c_din = debl_cfg_theta_20;

assign debl_cfg_theta_21_c_din = debl_cfg_theta_21;

assign debl_cfg_theta_22_c_din = debl_cfg_theta_22;

assign debl_cfg_theta_2_c_din = debl_cfg_theta_2;

assign debl_cfg_theta_3_c_din = debl_cfg_theta_3;

assign debl_cfg_theta_4_c_din = debl_cfg_theta_4;

assign debl_cfg_theta_5_c_din = debl_cfg_theta_5;

assign debl_cfg_theta_6_c_din = debl_cfg_theta_6;

assign debl_cfg_theta_7_c_din = debl_cfg_theta_7;

assign debl_cfg_theta_8_c_din = debl_cfg_theta_8;

assign debl_cfg_theta_9_c_din = debl_cfg_theta_9;

assign start_out = real_start;

endmodule //deepwaveaccel_entry_proc
