// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="deepwaveaccel_deepwaveaccel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.549457,HLS_SYN_LAT=58,HLS_SYN_TPT=4,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=8595,HLS_SYN_LUT=6053,HLS_VERSION=2025_1}" *)

module deepwaveaccel (
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        in_r_TDATA,
        out_r_TDATA,
        norm_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TVALID,
        out_r_TREADY,
        norm_TVALID,
        norm_TREADY
);

parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 10;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [31:0] in_r_TDATA;
output  [95:0] out_r_TDATA;
output  [23:0] norm_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;
output   norm_TVALID;
input   norm_TREADY;

 reg    ap_rst_n_inv;
wire   [63:0] goer_cfg_q0;
wire    goertzel_U0_ap_start;
wire    goertzel_U0_ap_done;
wire    goertzel_U0_ap_continue;
wire    goertzel_U0_ap_idle;
wire    goertzel_U0_ap_ready;
wire   [95:0] goertzel_U0_s_goertzel_din;
wire    goertzel_U0_s_goertzel_write;
wire    goertzel_U0_start_out;
wire    goertzel_U0_start_write;
wire    goertzel_U0_in_stream_TREADY;
wire   [5:0] goertzel_U0_goer_cfg_address0;
wire    goertzel_U0_goer_cfg_ce0;
wire    crosscor_U0_ap_start;
wire    crosscor_U0_ap_done;
wire    crosscor_U0_ap_continue;
wire    crosscor_U0_ap_idle;
wire    crosscor_U0_ap_ready;
wire    crosscor_U0_s_goertzel_read;
wire   [95:0] crosscor_U0_out_r_TDATA;
wire    crosscor_U0_out_r_TVALID;
wire   [23:0] crosscor_U0_norm_TDATA;
wire    crosscor_U0_norm_TVALID;
wire    s_goertzel_full_n;
wire   [95:0] s_goertzel_dout;
wire    s_goertzel_empty_n;
wire   [6:0] s_goertzel_num_data_valid;
wire   [6:0] s_goertzel_fifo_cap;
wire   [0:0] start_for_crosscor_U0_din;
wire    start_for_crosscor_U0_full_n;
wire   [0:0] start_for_crosscor_U0_dout;
wire    start_for_crosscor_U0_empty_n;

deepwaveaccel_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .goer_cfg_address0(goertzel_U0_goer_cfg_address0),
    .goer_cfg_ce0(goertzel_U0_goer_cfg_ce0),
    .goer_cfg_q0(goer_cfg_q0)
);

deepwaveaccel_goertzel goertzel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(goertzel_U0_ap_start),
    .start_full_n(start_for_crosscor_U0_full_n),
    .ap_done(goertzel_U0_ap_done),
    .ap_continue(goertzel_U0_ap_continue),
    .ap_idle(goertzel_U0_ap_idle),
    .ap_ready(goertzel_U0_ap_ready),
    .s_goertzel_din(goertzel_U0_s_goertzel_din),
    .s_goertzel_full_n(s_goertzel_full_n),
    .s_goertzel_write(goertzel_U0_s_goertzel_write),
    .s_goertzel_num_data_valid(s_goertzel_num_data_valid),
    .s_goertzel_fifo_cap(s_goertzel_fifo_cap),
    .start_out(goertzel_U0_start_out),
    .start_write(goertzel_U0_start_write),
    .in_stream_TDATA(in_r_TDATA),
    .in_stream_TVALID(in_r_TVALID),
    .in_stream_TREADY(goertzel_U0_in_stream_TREADY),
    .goer_cfg_address0(goertzel_U0_goer_cfg_address0),
    .goer_cfg_ce0(goertzel_U0_goer_cfg_ce0),
    .goer_cfg_q0(goer_cfg_q0)
);

deepwaveaccel_crosscor crosscor_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(crosscor_U0_ap_start),
    .ap_done(crosscor_U0_ap_done),
    .ap_continue(crosscor_U0_ap_continue),
    .ap_idle(crosscor_U0_ap_idle),
    .ap_ready(crosscor_U0_ap_ready),
    .s_goertzel_dout(s_goertzel_dout),
    .s_goertzel_empty_n(s_goertzel_empty_n),
    .s_goertzel_read(crosscor_U0_s_goertzel_read),
    .s_goertzel_num_data_valid(s_goertzel_num_data_valid),
    .s_goertzel_fifo_cap(s_goertzel_fifo_cap),
    .norm_TREADY(norm_TREADY),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TDATA(crosscor_U0_out_r_TDATA),
    .out_r_TVALID(crosscor_U0_out_r_TVALID),
    .norm_TDATA(crosscor_U0_norm_TDATA),
    .norm_TVALID(crosscor_U0_norm_TVALID)
);

deepwaveaccel_fifo_w96_d64_A s_goertzel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(goertzel_U0_s_goertzel_din),
    .if_full_n(s_goertzel_full_n),
    .if_write(goertzel_U0_s_goertzel_write),
    .if_dout(s_goertzel_dout),
    .if_empty_n(s_goertzel_empty_n),
    .if_read(crosscor_U0_s_goertzel_read),
    .if_num_data_valid(s_goertzel_num_data_valid),
    .if_fifo_cap(s_goertzel_fifo_cap)
);

deepwaveaccel_start_for_crosscor_U0 start_for_crosscor_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_crosscor_U0_din),
    .if_full_n(start_for_crosscor_U0_full_n),
    .if_write(goertzel_U0_start_write),
    .if_dout(start_for_crosscor_U0_dout),
    .if_empty_n(start_for_crosscor_U0_empty_n),
    .if_read(crosscor_U0_ap_ready)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign crosscor_U0_ap_continue = 1'b1;

assign crosscor_U0_ap_start = start_for_crosscor_U0_empty_n;

assign goertzel_U0_ap_continue = 1'b1;

assign goertzel_U0_ap_start = 1'b1;

assign in_r_TREADY = goertzel_U0_in_stream_TREADY;

assign norm_TDATA = crosscor_U0_norm_TDATA;

assign norm_TVALID = crosscor_U0_norm_TVALID;

assign out_r_TDATA = crosscor_U0_out_r_TDATA;

assign out_r_TVALID = crosscor_U0_out_r_TVALID;

assign start_for_crosscor_U0_din = 1'b1;

endmodule //deepwaveaccel
