// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="deepwaveaccel_deepwaveaccel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.047667,HLS_SYN_LAT=67,HLS_SYN_TPT=25,HLS_SYN_MEM=72,HLS_SYN_DSP=0,HLS_SYN_FF=7434,HLS_SYN_LUT=18511,HLS_VERSION=2025_1}" *)

module deepwaveaccel (
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        in_r_TDATA,
        param_bp_TDATA,
        param_db_TDATA,
        out_r_TDATA,
        out_r_TLAST,
        in_r_TVALID,
        in_r_TREADY,
        param_bp_TVALID,
        param_bp_TREADY,
        param_db_TVALID,
        param_db_TREADY,
        out_r_TVALID,
        out_r_TREADY
);

parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [31:0] in_r_TDATA;
input  [31:0] param_bp_TDATA;
input  [31:0] param_db_TDATA;
output  [31:0] out_r_TDATA;
output  [0:0] out_r_TLAST;
input   in_r_TVALID;
output   in_r_TREADY;
input   param_bp_TVALID;
output   param_bp_TREADY;
input   param_db_TVALID;
output   param_db_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;

 reg    ap_rst_n_inv;
wire   [17:0] goer_cfg_COS_OMEGA_0;
wire   [17:0] goer_cfg_COS_OMEGA_1;
wire   [17:0] goer_cfg_COS_OMEGA2_0;
wire   [17:0] goer_cfg_COS_OMEGA2_1;
wire   [17:0] goer_cfg_SIN_OMEGA_0;
wire   [17:0] goer_cfg_SIN_OMEGA_1;
wire   [7:0] debl_cfg;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [7:0] entry_proc_U0_debl_cfg_c_din;
wire    entry_proc_U0_debl_cfg_c_write;
wire    goertzel_U0_ap_start;
wire    goertzel_U0_ap_done;
wire    goertzel_U0_ap_continue;
wire    goertzel_U0_ap_idle;
wire    goertzel_U0_ap_ready;
wire    goertzel_U0_start_out;
wire    goertzel_U0_start_write;
wire    goertzel_U0_in_r_TREADY;
wire   [35:0] goertzel_U0_s_goertzel_din;
wire    goertzel_U0_s_goertzel_write;
wire   [31:0] goertzel_U0_status_gz_samples_in;
wire    goertzel_U0_status_gz_samples_in_ap_vld;
wire   [31:0] goertzel_U0_status_gz_sample_win;
wire    goertzel_U0_status_gz_sample_win_ap_vld;
wire   [31:0] goertzel_U0_status_gz_samples_out;
wire    goertzel_U0_status_gz_samples_out_ap_vld;
wire   [31:0] goertzel_U0_status_gz_samples_out_fifo;
wire    goertzel_U0_status_gz_samples_out_fifo_ap_vld;
wire    crosscor_U0_ap_start;
wire    crosscor_U0_ap_done;
wire    crosscor_U0_ap_continue;
wire    crosscor_U0_ap_idle;
wire    crosscor_U0_ap_ready;
wire    crosscor_U0_start_out;
wire    crosscor_U0_start_write;
wire    crosscor_U0_s_goertzel_read;
wire   [35:0] crosscor_U0_s_xcor_din;
wire    crosscor_U0_s_xcor_write;
wire   [24:0] crosscor_U0_s_norm_din;
wire    crosscor_U0_s_norm_write;
wire   [7:0] crosscor_U0_status_cc_state;
wire    crosscor_U0_status_cc_state_ap_vld;
wire   [31:0] crosscor_U0_status_cc_samples_in;
wire    crosscor_U0_status_cc_samples_in_ap_vld;
wire   [31:0] crosscor_U0_status_cc_samples_out;
wire    crosscor_U0_status_cc_samples_out_ap_vld;
wire   [31:0] crosscor_U0_status_cc_sample_idx;
wire    crosscor_U0_status_cc_sample_idx_ap_vld;
wire   [31:0] crosscor_U0_status_cc_current_norm;
wire    crosscor_U0_status_cc_current_norm_ap_vld;
wire   [31:0] crosscor_U0_status_cc_norms_written;
wire    crosscor_U0_status_cc_norms_written_ap_vld;
wire   [31:0] crosscor_U0_status_cc_out_fifo;
wire    crosscor_U0_status_cc_out_fifo_ap_vld;
wire   [31:0] crosscor_U0_status_cc_norms_fifo;
wire    crosscor_U0_status_cc_norms_fifo_ap_vld;
wire    backprojection_U0_ap_start;
wire    backprojection_U0_ap_done;
wire    backprojection_U0_ap_continue;
wire    backprojection_U0_ap_idle;
wire    backprojection_U0_ap_ready;
wire    backprojection_U0_s_xcor_read;
wire    backprojection_U0_param_bp_TREADY;
wire   [17:0] backprojection_U0_s_bp_din;
wire    backprojection_U0_s_bp_write;
wire   [0:0] backprojection_U0_status_bp_config_loaded;
wire    backprojection_U0_status_bp_config_loaded_ap_vld;
wire   [7:0] backprojection_U0_status_bp_fsm_state;
wire    backprojection_U0_status_bp_fsm_state_ap_vld;
wire   [7:0] backprojection_U0_status_bp_param_state;
wire    backprojection_U0_status_bp_param_state_ap_vld;
wire   [15:0] backprojection_U0_status_bp_idx;
wire    backprojection_U0_status_bp_idx_ap_vld;
wire   [31:0] backprojection_U0_status_bp_sigmas_in;
wire    backprojection_U0_status_bp_sigmas_in_ap_vld;
wire   [31:0] backprojection_U0_status_bp_pixels_out;
wire    backprojection_U0_status_bp_pixels_out_ap_vld;
wire   [15:0] backprojection_U0_status_bp_out_fifo_level;
wire    backprojection_U0_status_bp_out_fifo_level_ap_vld;
wire    deblur_U0_ap_start;
wire    deblur_U0_ap_done;
wire    deblur_U0_ap_continue;
wire    deblur_U0_ap_idle;
wire    deblur_U0_ap_ready;
wire    deblur_U0_debl_cfg_read;
wire    deblur_U0_s_bp_read;
wire    deblur_U0_param_db_TREADY;
wire   [31:0] deblur_U0_out_r_TDATA;
wire    deblur_U0_out_r_TVALID;
wire   [0:0] deblur_U0_out_r_TLAST;
wire    deblur_U0_s_norm_read;
wire   [0:0] deblur_U0_status_db_config_loaded;
wire    deblur_U0_status_db_config_loaded_ap_vld;
wire   [7:0] deblur_U0_status_db_fsm_state;
wire    deblur_U0_status_db_fsm_state_ap_vld;
wire   [7:0] deblur_U0_status_db_param_state;
wire    deblur_U0_status_db_param_state_ap_vld;
wire   [15:0] deblur_U0_status_db_idx;
wire    deblur_U0_status_db_idx_ap_vld;
wire   [31:0] deblur_U0_status_db_pixels_in;
wire    deblur_U0_status_db_pixels_in_ap_vld;
wire   [31:0] deblur_U0_status_db_pixels_out;
wire    deblur_U0_status_db_pixels_out_ap_vld;
wire    debl_cfg_c_full_n;
wire   [7:0] debl_cfg_c_dout;
wire    debl_cfg_c_empty_n;
wire   [3:0] debl_cfg_c_num_data_valid;
wire   [3:0] debl_cfg_c_fifo_cap;
wire    s_goertzel_full_n;
wire   [35:0] s_goertzel_dout;
wire    s_goertzel_empty_n;
wire   [6:0] s_goertzel_num_data_valid;
wire   [6:0] s_goertzel_fifo_cap;
wire    s_xcor_full_n;
wire   [35:0] s_xcor_dout;
wire    s_xcor_empty_n;
wire   [6:0] s_xcor_num_data_valid;
wire   [6:0] s_xcor_fifo_cap;
wire    s_norm_full_n;
wire   [24:0] s_norm_dout;
wire    s_norm_empty_n;
wire   [2:0] s_norm_num_data_valid;
wire   [2:0] s_norm_fifo_cap;
wire    s_bp_full_n;
wire   [17:0] s_bp_dout;
wire    s_bp_empty_n;
wire   [6:0] s_bp_num_data_valid;
wire   [6:0] s_bp_fifo_cap;
wire   [0:0] start_for_deblur_U0_din;
wire    start_for_deblur_U0_full_n;
wire   [0:0] start_for_deblur_U0_dout;
wire    start_for_deblur_U0_empty_n;
wire   [0:0] start_for_crosscor_U0_din;
wire    start_for_crosscor_U0_full_n;
wire   [0:0] start_for_crosscor_U0_dout;
wire    start_for_crosscor_U0_empty_n;
wire   [0:0] start_for_backprojection_U0_din;
wire    start_for_backprojection_U0_full_n;
wire   [0:0] start_for_backprojection_U0_dout;
wire    start_for_backprojection_U0_empty_n;

deepwaveaccel_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .goer_cfg_COS_OMEGA_0(goer_cfg_COS_OMEGA_0),
    .goer_cfg_COS_OMEGA_1(goer_cfg_COS_OMEGA_1),
    .goer_cfg_COS_OMEGA2_0(goer_cfg_COS_OMEGA2_0),
    .goer_cfg_COS_OMEGA2_1(goer_cfg_COS_OMEGA2_1),
    .goer_cfg_SIN_OMEGA_0(goer_cfg_SIN_OMEGA_0),
    .goer_cfg_SIN_OMEGA_1(goer_cfg_SIN_OMEGA_1),
    .debl_cfg(debl_cfg),
    .status_gz_samples_in(goertzel_U0_status_gz_samples_in),
    .status_gz_samples_in_ap_vld(goertzel_U0_status_gz_samples_in_ap_vld),
    .status_gz_sample_win(goertzel_U0_status_gz_sample_win),
    .status_gz_sample_win_ap_vld(goertzel_U0_status_gz_sample_win_ap_vld),
    .status_gz_samples_out(goertzel_U0_status_gz_samples_out),
    .status_gz_samples_out_ap_vld(goertzel_U0_status_gz_samples_out_ap_vld),
    .status_gz_samples_out_fifo(goertzel_U0_status_gz_samples_out_fifo),
    .status_gz_samples_out_fifo_ap_vld(goertzel_U0_status_gz_samples_out_fifo_ap_vld),
    .status_cc_state(crosscor_U0_status_cc_state),
    .status_cc_state_ap_vld(crosscor_U0_status_cc_state_ap_vld),
    .status_cc_samples_in(crosscor_U0_status_cc_samples_in),
    .status_cc_samples_in_ap_vld(crosscor_U0_status_cc_samples_in_ap_vld),
    .status_cc_samples_out(crosscor_U0_status_cc_samples_out),
    .status_cc_samples_out_ap_vld(crosscor_U0_status_cc_samples_out_ap_vld),
    .status_cc_sample_idx(crosscor_U0_status_cc_sample_idx),
    .status_cc_sample_idx_ap_vld(crosscor_U0_status_cc_sample_idx_ap_vld),
    .status_cc_current_norm(crosscor_U0_status_cc_current_norm),
    .status_cc_current_norm_ap_vld(crosscor_U0_status_cc_current_norm_ap_vld),
    .status_cc_norms_written(crosscor_U0_status_cc_norms_written),
    .status_cc_norms_written_ap_vld(crosscor_U0_status_cc_norms_written_ap_vld),
    .status_cc_out_fifo(crosscor_U0_status_cc_out_fifo),
    .status_cc_out_fifo_ap_vld(crosscor_U0_status_cc_out_fifo_ap_vld),
    .status_cc_norms_fifo(crosscor_U0_status_cc_norms_fifo),
    .status_cc_norms_fifo_ap_vld(crosscor_U0_status_cc_norms_fifo_ap_vld),
    .status_bp_config_loaded(backprojection_U0_status_bp_config_loaded),
    .status_bp_config_loaded_ap_vld(backprojection_U0_status_bp_config_loaded_ap_vld),
    .status_bp_fsm_state(backprojection_U0_status_bp_fsm_state),
    .status_bp_fsm_state_ap_vld(backprojection_U0_status_bp_fsm_state_ap_vld),
    .status_bp_param_state(backprojection_U0_status_bp_param_state),
    .status_bp_param_state_ap_vld(backprojection_U0_status_bp_param_state_ap_vld),
    .status_bp_idx(backprojection_U0_status_bp_idx),
    .status_bp_idx_ap_vld(backprojection_U0_status_bp_idx_ap_vld),
    .status_bp_sigmas_in(backprojection_U0_status_bp_sigmas_in),
    .status_bp_sigmas_in_ap_vld(backprojection_U0_status_bp_sigmas_in_ap_vld),
    .status_bp_pixels_out(backprojection_U0_status_bp_pixels_out),
    .status_bp_pixels_out_ap_vld(backprojection_U0_status_bp_pixels_out_ap_vld),
    .status_bp_out_fifo_level(backprojection_U0_status_bp_out_fifo_level),
    .status_bp_out_fifo_level_ap_vld(backprojection_U0_status_bp_out_fifo_level_ap_vld),
    .status_db_config_loaded(deblur_U0_status_db_config_loaded),
    .status_db_config_loaded_ap_vld(deblur_U0_status_db_config_loaded_ap_vld),
    .status_db_fsm_state(deblur_U0_status_db_fsm_state),
    .status_db_fsm_state_ap_vld(deblur_U0_status_db_fsm_state_ap_vld),
    .status_db_param_state(deblur_U0_status_db_param_state),
    .status_db_param_state_ap_vld(deblur_U0_status_db_param_state_ap_vld),
    .status_db_idx(deblur_U0_status_db_idx),
    .status_db_idx_ap_vld(deblur_U0_status_db_idx_ap_vld),
    .status_db_pixels_in(deblur_U0_status_db_pixels_in),
    .status_db_pixels_in_ap_vld(deblur_U0_status_db_pixels_in_ap_vld),
    .status_db_pixels_out(deblur_U0_status_db_pixels_out),
    .status_db_pixels_out_ap_vld(deblur_U0_status_db_pixels_out_ap_vld)
);

deepwaveaccel_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_deblur_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .debl_cfg(debl_cfg),
    .debl_cfg_c_din(entry_proc_U0_debl_cfg_c_din),
    .debl_cfg_c_full_n(debl_cfg_c_full_n),
    .debl_cfg_c_write(entry_proc_U0_debl_cfg_c_write),
    .debl_cfg_c_num_data_valid(debl_cfg_c_num_data_valid),
    .debl_cfg_c_fifo_cap(debl_cfg_c_fifo_cap)
);

deepwaveaccel_goertzel goertzel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(goertzel_U0_ap_start),
    .start_full_n(start_for_crosscor_U0_full_n),
    .ap_done(goertzel_U0_ap_done),
    .ap_continue(goertzel_U0_ap_continue),
    .ap_idle(goertzel_U0_ap_idle),
    .ap_ready(goertzel_U0_ap_ready),
    .start_out(goertzel_U0_start_out),
    .start_write(goertzel_U0_start_write),
    .goer_cfg_COS_OMEGA_0(goer_cfg_COS_OMEGA_0),
    .goer_cfg_COS_OMEGA_1(goer_cfg_COS_OMEGA_1),
    .goer_cfg_COS_OMEGA2_0(goer_cfg_COS_OMEGA2_0),
    .goer_cfg_COS_OMEGA2_1(goer_cfg_COS_OMEGA2_1),
    .goer_cfg_SIN_OMEGA_0(goer_cfg_SIN_OMEGA_0),
    .goer_cfg_SIN_OMEGA_1(goer_cfg_SIN_OMEGA_1),
    .in_r_TDATA(in_r_TDATA),
    .in_r_TVALID(in_r_TVALID),
    .in_r_TREADY(goertzel_U0_in_r_TREADY),
    .s_goertzel_din(goertzel_U0_s_goertzel_din),
    .s_goertzel_full_n(s_goertzel_full_n),
    .s_goertzel_write(goertzel_U0_s_goertzel_write),
    .s_goertzel_num_data_valid(s_goertzel_num_data_valid),
    .s_goertzel_fifo_cap(s_goertzel_fifo_cap),
    .status_gz_samples_in(goertzel_U0_status_gz_samples_in),
    .status_gz_samples_in_ap_vld(goertzel_U0_status_gz_samples_in_ap_vld),
    .status_gz_sample_win(goertzel_U0_status_gz_sample_win),
    .status_gz_sample_win_ap_vld(goertzel_U0_status_gz_sample_win_ap_vld),
    .status_gz_samples_out(goertzel_U0_status_gz_samples_out),
    .status_gz_samples_out_ap_vld(goertzel_U0_status_gz_samples_out_ap_vld),
    .status_gz_samples_out_fifo(goertzel_U0_status_gz_samples_out_fifo),
    .status_gz_samples_out_fifo_ap_vld(goertzel_U0_status_gz_samples_out_fifo_ap_vld)
);

deepwaveaccel_crosscor crosscor_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(crosscor_U0_ap_start),
    .start_full_n(start_for_backprojection_U0_full_n),
    .ap_done(crosscor_U0_ap_done),
    .ap_continue(crosscor_U0_ap_continue),
    .ap_idle(crosscor_U0_ap_idle),
    .ap_ready(crosscor_U0_ap_ready),
    .start_out(crosscor_U0_start_out),
    .start_write(crosscor_U0_start_write),
    .s_goertzel_dout(s_goertzel_dout),
    .s_goertzel_empty_n(s_goertzel_empty_n),
    .s_goertzel_read(crosscor_U0_s_goertzel_read),
    .s_goertzel_num_data_valid(s_goertzel_num_data_valid),
    .s_goertzel_fifo_cap(s_goertzel_fifo_cap),
    .s_xcor_din(crosscor_U0_s_xcor_din),
    .s_xcor_full_n(s_xcor_full_n),
    .s_xcor_write(crosscor_U0_s_xcor_write),
    .s_xcor_num_data_valid(s_xcor_num_data_valid),
    .s_xcor_fifo_cap(s_xcor_fifo_cap),
    .s_norm_din(crosscor_U0_s_norm_din),
    .s_norm_full_n(s_norm_full_n),
    .s_norm_write(crosscor_U0_s_norm_write),
    .s_norm_num_data_valid(s_norm_num_data_valid),
    .s_norm_fifo_cap(s_norm_fifo_cap),
    .status_cc_state(crosscor_U0_status_cc_state),
    .status_cc_state_ap_vld(crosscor_U0_status_cc_state_ap_vld),
    .status_cc_samples_in(crosscor_U0_status_cc_samples_in),
    .status_cc_samples_in_ap_vld(crosscor_U0_status_cc_samples_in_ap_vld),
    .status_cc_samples_out(crosscor_U0_status_cc_samples_out),
    .status_cc_samples_out_ap_vld(crosscor_U0_status_cc_samples_out_ap_vld),
    .status_cc_sample_idx(crosscor_U0_status_cc_sample_idx),
    .status_cc_sample_idx_ap_vld(crosscor_U0_status_cc_sample_idx_ap_vld),
    .status_cc_current_norm(crosscor_U0_status_cc_current_norm),
    .status_cc_current_norm_ap_vld(crosscor_U0_status_cc_current_norm_ap_vld),
    .status_cc_norms_written(crosscor_U0_status_cc_norms_written),
    .status_cc_norms_written_ap_vld(crosscor_U0_status_cc_norms_written_ap_vld),
    .status_cc_out_fifo(crosscor_U0_status_cc_out_fifo),
    .status_cc_out_fifo_ap_vld(crosscor_U0_status_cc_out_fifo_ap_vld),
    .status_cc_norms_fifo(crosscor_U0_status_cc_norms_fifo),
    .status_cc_norms_fifo_ap_vld(crosscor_U0_status_cc_norms_fifo_ap_vld)
);

deepwaveaccel_backprojection backprojection_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(backprojection_U0_ap_start),
    .ap_done(backprojection_U0_ap_done),
    .ap_continue(backprojection_U0_ap_continue),
    .ap_idle(backprojection_U0_ap_idle),
    .ap_ready(backprojection_U0_ap_ready),
    .s_xcor_dout(s_xcor_dout),
    .s_xcor_empty_n(s_xcor_empty_n),
    .s_xcor_read(backprojection_U0_s_xcor_read),
    .s_xcor_num_data_valid(s_xcor_num_data_valid),
    .s_xcor_fifo_cap(s_xcor_fifo_cap),
    .param_bp_TDATA(param_bp_TDATA),
    .param_bp_TVALID(param_bp_TVALID),
    .param_bp_TREADY(backprojection_U0_param_bp_TREADY),
    .s_bp_din(backprojection_U0_s_bp_din),
    .s_bp_full_n(s_bp_full_n),
    .s_bp_write(backprojection_U0_s_bp_write),
    .s_bp_num_data_valid(s_bp_num_data_valid),
    .s_bp_fifo_cap(s_bp_fifo_cap),
    .status_bp_config_loaded(backprojection_U0_status_bp_config_loaded),
    .status_bp_config_loaded_ap_vld(backprojection_U0_status_bp_config_loaded_ap_vld),
    .status_bp_fsm_state(backprojection_U0_status_bp_fsm_state),
    .status_bp_fsm_state_ap_vld(backprojection_U0_status_bp_fsm_state_ap_vld),
    .status_bp_param_state(backprojection_U0_status_bp_param_state),
    .status_bp_param_state_ap_vld(backprojection_U0_status_bp_param_state_ap_vld),
    .status_bp_idx(backprojection_U0_status_bp_idx),
    .status_bp_idx_ap_vld(backprojection_U0_status_bp_idx_ap_vld),
    .status_bp_sigmas_in(backprojection_U0_status_bp_sigmas_in),
    .status_bp_sigmas_in_ap_vld(backprojection_U0_status_bp_sigmas_in_ap_vld),
    .status_bp_pixels_out(backprojection_U0_status_bp_pixels_out),
    .status_bp_pixels_out_ap_vld(backprojection_U0_status_bp_pixels_out_ap_vld),
    .status_bp_out_fifo_level(backprojection_U0_status_bp_out_fifo_level),
    .status_bp_out_fifo_level_ap_vld(backprojection_U0_status_bp_out_fifo_level_ap_vld)
);

deepwaveaccel_deblur deblur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(deblur_U0_ap_start),
    .ap_done(deblur_U0_ap_done),
    .ap_continue(deblur_U0_ap_continue),
    .ap_idle(deblur_U0_ap_idle),
    .ap_ready(deblur_U0_ap_ready),
    .debl_cfg_dout(debl_cfg_c_dout),
    .debl_cfg_empty_n(debl_cfg_c_empty_n),
    .debl_cfg_read(deblur_U0_debl_cfg_read),
    .debl_cfg_num_data_valid(debl_cfg_c_num_data_valid),
    .debl_cfg_fifo_cap(debl_cfg_c_fifo_cap),
    .s_bp_dout(s_bp_dout),
    .s_bp_empty_n(s_bp_empty_n),
    .s_bp_read(deblur_U0_s_bp_read),
    .s_bp_num_data_valid(s_bp_num_data_valid),
    .s_bp_fifo_cap(s_bp_fifo_cap),
    .param_db_TDATA(param_db_TDATA),
    .param_db_TVALID(param_db_TVALID),
    .param_db_TREADY(deblur_U0_param_db_TREADY),
    .out_r_TDATA(deblur_U0_out_r_TDATA),
    .out_r_TVALID(deblur_U0_out_r_TVALID),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TLAST(deblur_U0_out_r_TLAST),
    .s_norm_dout(s_norm_dout),
    .s_norm_empty_n(s_norm_empty_n),
    .s_norm_read(deblur_U0_s_norm_read),
    .s_norm_num_data_valid(s_norm_num_data_valid),
    .s_norm_fifo_cap(s_norm_fifo_cap),
    .status_db_config_loaded(deblur_U0_status_db_config_loaded),
    .status_db_config_loaded_ap_vld(deblur_U0_status_db_config_loaded_ap_vld),
    .status_db_fsm_state(deblur_U0_status_db_fsm_state),
    .status_db_fsm_state_ap_vld(deblur_U0_status_db_fsm_state_ap_vld),
    .status_db_param_state(deblur_U0_status_db_param_state),
    .status_db_param_state_ap_vld(deblur_U0_status_db_param_state_ap_vld),
    .status_db_idx(deblur_U0_status_db_idx),
    .status_db_idx_ap_vld(deblur_U0_status_db_idx_ap_vld),
    .status_db_pixels_in(deblur_U0_status_db_pixels_in),
    .status_db_pixels_in_ap_vld(deblur_U0_status_db_pixels_in_ap_vld),
    .status_db_pixels_out(deblur_U0_status_db_pixels_out),
    .status_db_pixels_out_ap_vld(deblur_U0_status_db_pixels_out_ap_vld)
);

deepwaveaccel_fifo_w8_d5_S debl_cfg_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_debl_cfg_c_din),
    .if_full_n(debl_cfg_c_full_n),
    .if_write(entry_proc_U0_debl_cfg_c_write),
    .if_dout(debl_cfg_c_dout),
    .if_empty_n(debl_cfg_c_empty_n),
    .if_read(deblur_U0_debl_cfg_read),
    .if_num_data_valid(debl_cfg_c_num_data_valid),
    .if_fifo_cap(debl_cfg_c_fifo_cap)
);

deepwaveaccel_fifo_w36_d64_A s_goertzel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(goertzel_U0_s_goertzel_din),
    .if_full_n(s_goertzel_full_n),
    .if_write(goertzel_U0_s_goertzel_write),
    .if_dout(s_goertzel_dout),
    .if_empty_n(s_goertzel_empty_n),
    .if_read(crosscor_U0_s_goertzel_read),
    .if_num_data_valid(s_goertzel_num_data_valid),
    .if_fifo_cap(s_goertzel_fifo_cap)
);

deepwaveaccel_fifo_w36_d64_A s_xcor_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(crosscor_U0_s_xcor_din),
    .if_full_n(s_xcor_full_n),
    .if_write(crosscor_U0_s_xcor_write),
    .if_dout(s_xcor_dout),
    .if_empty_n(s_xcor_empty_n),
    .if_read(backprojection_U0_s_xcor_read),
    .if_num_data_valid(s_xcor_num_data_valid),
    .if_fifo_cap(s_xcor_fifo_cap)
);

deepwaveaccel_fifo_w25_d4_S s_norm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(crosscor_U0_s_norm_din),
    .if_full_n(s_norm_full_n),
    .if_write(crosscor_U0_s_norm_write),
    .if_dout(s_norm_dout),
    .if_empty_n(s_norm_empty_n),
    .if_read(deblur_U0_s_norm_read),
    .if_num_data_valid(s_norm_num_data_valid),
    .if_fifo_cap(s_norm_fifo_cap)
);

deepwaveaccel_fifo_w18_d64_A s_bp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(backprojection_U0_s_bp_din),
    .if_full_n(s_bp_full_n),
    .if_write(backprojection_U0_s_bp_write),
    .if_dout(s_bp_dout),
    .if_empty_n(s_bp_empty_n),
    .if_read(deblur_U0_s_bp_read),
    .if_num_data_valid(s_bp_num_data_valid),
    .if_fifo_cap(s_bp_fifo_cap)
);

deepwaveaccel_start_for_deblur_U0 start_for_deblur_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_deblur_U0_din),
    .if_full_n(start_for_deblur_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_deblur_U0_dout),
    .if_empty_n(start_for_deblur_U0_empty_n),
    .if_read(deblur_U0_ap_ready)
);

deepwaveaccel_start_for_crosscor_U0 start_for_crosscor_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_crosscor_U0_din),
    .if_full_n(start_for_crosscor_U0_full_n),
    .if_write(goertzel_U0_start_write),
    .if_dout(start_for_crosscor_U0_dout),
    .if_empty_n(start_for_crosscor_U0_empty_n),
    .if_read(crosscor_U0_ap_ready)
);

deepwaveaccel_start_for_backprojection_U0 start_for_backprojection_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_backprojection_U0_din),
    .if_full_n(start_for_backprojection_U0_full_n),
    .if_write(crosscor_U0_start_write),
    .if_dout(start_for_backprojection_U0_dout),
    .if_empty_n(start_for_backprojection_U0_empty_n),
    .if_read(backprojection_U0_ap_ready)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign backprojection_U0_ap_continue = 1'b1;

assign backprojection_U0_ap_start = start_for_backprojection_U0_empty_n;

assign crosscor_U0_ap_continue = 1'b1;

assign crosscor_U0_ap_start = start_for_crosscor_U0_empty_n;

assign deblur_U0_ap_continue = 1'b1;

assign deblur_U0_ap_start = start_for_deblur_U0_empty_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = 1'b1;

assign goertzel_U0_ap_continue = 1'b1;

assign goertzel_U0_ap_start = 1'b1;

assign in_r_TREADY = goertzel_U0_in_r_TREADY;

assign out_r_TDATA = deblur_U0_out_r_TDATA;

assign out_r_TLAST = deblur_U0_out_r_TLAST;

assign out_r_TVALID = deblur_U0_out_r_TVALID;

assign param_bp_TREADY = backprojection_U0_param_bp_TREADY;

assign param_db_TREADY = deblur_U0_param_db_TREADY;

assign start_for_backprojection_U0_din = 1'b1;

assign start_for_crosscor_U0_din = 1'b1;

assign start_for_deblur_U0_din = 1'b1;

endmodule //deepwaveaccel
