SLStudio.Utils.RemoveHighlighting(get_param('Model', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Model', 'handle'));
annotate_port('gm_Model/DUT_Test/CrossCor', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel', 0, 1, '');
annotate_port('gm_Model/DUT_Test/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in4_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Compare To Constant2', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Compare To Constant2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Bus Creator2', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Bus Creator2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Product', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_ReIm2Complex', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product1', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Product', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_C2ReIm', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidResetDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Selector', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Diag', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/DataRT_outrepeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidRT_outrepeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay6', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/DataRT', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataRT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidRT', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/ValidRT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidResetCounter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Math Function1', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Correlation/Math Function1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product1', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product2', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AC_minus_BD', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_ReIm2Complex', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AD_plus_BC', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product3', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay11', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay7', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in4_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/t146', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Switch', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Add', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Add', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch1', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Switch1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidMem_lowered', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/DataMem', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/in5_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/NOT', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/RisingEdgeDetector/NOT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/t149', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/DataInSW', 0, 1, '');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataInSW', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in0_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in1_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in3_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in4_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in0_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/Delay11', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidResetDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/DataRT', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/DataRT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidRT', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/ValidRT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidResetCounter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in1_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in5_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/DataMem', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidMem_lowered', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/in2_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/NOT', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/RisingEdgeDetector/NOT', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in8_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay1_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/HDL Counter_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/countFrom', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/or', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare1', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/switch', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/adder', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/step_value', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in7_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Delay_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Constant', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Switch', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in6_repeat', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Delay_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Constant', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Switch', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat4', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay11', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay41', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay12', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Hann/Hann', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Hann', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch1', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add11', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add21', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch11', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat5', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/Delay3_enbsw', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add1', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1/tapped_delay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay31', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Hann/Hann', 0, 1, '');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Hann', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_ge_50', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_96', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_eq_97', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_ge_3', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_49', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_eq_50', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_46', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_eq_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_46', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_eq_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_ge_6', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_52', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_eq_53', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_46', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_eq_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_46', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_eq_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_46', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_eq_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_ge_2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_48', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_eq_49', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/counter', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_47', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_ge_2', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_48', 0, 1, '');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_eq_49', 0, 1, '');
