open_system('Model');
open_system('gm_Model');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidResetCounter', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay7', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidResetCounter', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidResetCounter_absorbed', 'user5');
hilite_system('Model/DUT_Test/Goertzel/DataValidDownsampler/ValidResetCounter', 'user5');
