open_system('gm_Model');
open_system('Model');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay1_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay1_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/HDL Counter_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/HDL Counter_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/countFrom', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/countFrom', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/Delay_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/or', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/or', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/compare1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/switch', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/adder', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/adder', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/step_value', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/step_value', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Delay_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Delay_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Constant', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Constant', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Switch', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/Switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Delay_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Delay_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Constant', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Constant', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Switch', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/Switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add11', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add11', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add1_out_dtc1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add21', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add21', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Multiply-Add2_out_dtc1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch11', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Switch11', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/Delay1_enbsw1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/t1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/Delay3_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/Delay3_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add', 0, 1, 'Streaming Group 2');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 'user2');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add1', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/Multiply-Add1', 0, 1, 'Streaming Group 2');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 'user2');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay/tapped_delay', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1/tapped_delay', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1/tapped_delay', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t1', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/t1', 0, 1, 'Streaming Group 2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 'user2');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 0, 1, 'Streaming Group 2');
