open_system('Model');
open_system('gm_Model');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/CrossCor', 'user1');
annotate_port('Model/DUT_Test/CrossCor', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel', 'user1');
annotate_port('Model/DUT_Test/Goertzel', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/t', 'user1');
annotate_port('gm_Model/DUT_Test/t', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in0_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in2_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in0_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in1_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in3_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in4_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Compare To Constant2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Compare To Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/CrossCor/Compare To Constant2', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Compare To Constant2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in0_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in1_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in2_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in3_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in1_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in2_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidResetDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidResetDelay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/DataRT_outrepeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/DataRT_outrepeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidRT_outrepeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidRT_outrepeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay4', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay6', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay6', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay5', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/DataRT', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/DataRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataRT', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidRT', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/ValidRT', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/ValidRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidResetCounter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidResetCounter', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in0_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in0_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Math Function1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Math Function1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/CrossCor/Correlation/Math Function1', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Correlation/Math Function1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in3_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in3_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay11', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay11', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Delay7', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Delay7', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in4_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in4_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/HDL Counter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/HDL Counter', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in1_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in1_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in2_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in2_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/ValidMem_lowered', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/ValidMem_lowered', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/DataMem', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/DataMem', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/in5_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/NOT', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/RisingEdgeDetector/NOT', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/RisingEdgeDetector/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in0_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in1_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in3_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in4_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in0_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/Delay11', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/Delay11', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidResetDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidResetDelay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/DataRT', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/DataRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/DataValidDownsampler/DataRT', 'user1');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/DataRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidRT', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/DataValidDownsampler/ValidRT', 'user1');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/ValidRT', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidResetCounter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidResetCounter', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in1_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in5_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/DataMem', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/DataMem', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/ValidMem_lowered', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/ValidMem_lowered', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/in2_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/NOT', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/Goertzel/DataValidDownsampler/RisingEdgeDetector/NOT', 'user1');
annotate_port('Model/DUT_Test/Goertzel/DataValidDownsampler/RisingEdgeDetector/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in8_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in8_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat4', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat5', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in0_repeat5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in4_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay2', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat4', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in7_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in7_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat3', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Delay4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in6_repeat', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in6_repeat', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat4', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat4', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat4', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay5', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat5', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in3_repeat5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay11', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay11', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat5', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in2_repeat5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay41', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay41', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay12', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay12', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in5_repeat1', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Hann/Hann', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Hann/Hann', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Hann', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Hann', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/Compare To Constant', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat5', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/in1_repeat5', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay31', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/Delay31', 0, 1, 'Delays not moved across due to different sample times at inputs and outputs');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_ge_50', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_ge_50', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_96', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_le_96', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_eq_97', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed1/enb_counter_eq_97', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/tappedDelay1', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_ge_3', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_ge_3', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_49', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_le_49', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_eq_50', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed2/enb_counter_eq_50', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_46', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_46', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_eq_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed1/enb_counter_eq_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_46', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_46', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_eq_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed2/enb_counter_eq_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/tappedDelay1', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_ge_6', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_ge_6', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_52', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_le_52', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_eq_53', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/streaming_partition_streamed/enb_counter_eq_53', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/counter', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_46', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_46', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_eq_47', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/EnabledGoertzel/crp_temp_streamed/enb_counter_eq_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/counter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_46', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_46', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_eq_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/enb_counter_eq_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/counter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_46', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_46', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_eq_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/enb_counter_eq_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/counter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_ge_2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_48', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_le_48', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_eq_49', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/enb_counter_eq_49', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 0, 1, 'Delays not moved into or out of an unsupported subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/counter', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/counter', 0, 1, 'Delays not moved into or out of an enabled subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_47', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_47', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_ge_2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_ge_2', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_48', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_le_48', 0, 1, 'Delays not moved across the block because it is created for scheduling');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_eq_49', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/enb_counter_eq_49', 0, 1, 'Delays not moved across the block because it is created for scheduling');
