open_system('gm_Model');
open_system('Model');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Bus Creator2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Bus Creator2', 0, 1, 'Unsupported block');
hilite_system('Model/DUT_Test/CrossCor/Bus Creator2', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Bus Creator2', 0, 1, 'Unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/NormalizationPower/Product', 'user1');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Product', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_ReIm2Complex', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_ReIm2Complex', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/NormalizationPower/Product', 'user1');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Product', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_C2ReIm', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/Product_C2ReIm', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/t', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/Selector', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/Selector', 0, 1, 'Unsupported block');
hilite_system('Model/DUT_Test/CrossCor/NormalizationPower/Diag', 'user1');
annotate_port('Model/DUT_Test/CrossCor/NormalizationPower/Diag', 0, 1, 'Unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product2', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AC_minus_BD', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AC_minus_BD', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_ReIm2Complex', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_ReIm2Complex', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AD_plus_BC', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_AD_plus_BC', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_out_dtc3', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product3', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Correlation/MatrixMultiply', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/MMul_dot_product_C2ReIm_1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/t', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/t146', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/t146', 0, 1, 'Unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Grouping/Switch', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Switch', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Add', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Add', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Grouping/Add', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Add', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch1', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/Switch1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Grouping/Switch1', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/Switch1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/t', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/t149', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/t149', 0, 1, 'Unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/DataInSW', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/DataInSW', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataInSW', 'user1');
annotate_port('Model/DUT_Test/CrossCor/Grouping/DataValidDownsampler/DataInSW', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/t', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 'user1');
annotate_port('gm_Model/DUT_Test/CrossCor/streaming_partition_streamed3', 0, 1, 'Streaming Group 1');
