open_system('gm_Model');
open_system('Model');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/Multiply-Add', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/Multiply-Add', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Delay_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Delay_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Constant', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Constant', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Switch', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/Switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Delay1_enbsw', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Delay1_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Constant1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Constant1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Constant1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add2', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Multiply-Add2', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Switch1', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Switch1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 'user1');
annotate_port('Model/DUT_Test/Goertzel/EnabledGoertzel/For All Bins Filter/Switch1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add1_out_dtc', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add1_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add2_out_dtc', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/Multiply-Add2_out_dtc', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/t', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2', 'user1');
annotate_port('gm_Model/DUT_Test/Goertzel/For All Bins Filter_instance2/crp_temp_streamed2', 0, 1, 'Streaming Group 1');
