open_system('gm_Model');
open_system('Model');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/Delay1_enbsw', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/Delay1_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/HDL Counter_enbsw', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/HDL Counter_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/countFrom', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/countFrom', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/Delay_enbsw', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/Delay_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/compare', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/compare', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/or', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/or', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/compare1', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/compare1', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/switch', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/switch', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/adder', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/adder', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/step_value', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/step_value', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/HDL Counter', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/t', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/Hann/Hann', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/Hann/Hann', 0, 1, 'Unsupported block');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/Symmetric Hann/Hann', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/Symmetric Hann/Hann', 0, 1, 'Unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/Product', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/Product', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/EnabledGoertzel/Product', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/EnabledGoertzel/Product', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/t', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/streaming_partition_streamed', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/Delay4_enbsw', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/Delay4_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/Delay3_enbsw', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/Delay3_enbsw', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/t', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed1', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/Delay_Switch', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/Delay_Switch', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/ValidSampleOR', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/ValidSampleOR', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/DataValidDownsampler/ValidSampleOR', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/DataValidDownsampler/ValidSampleOR', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/NOT', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/NOT', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/DataValidDownsampler/RisingEdgeDetector/NOT', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/DataValidDownsampler/RisingEdgeDetector/NOT', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/AND', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/AND', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/DataValidDownsampler/RisingEdgeDetector/AND', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/DataValidDownsampler/RisingEdgeDetector/AND', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/DataInSW', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/DataInSW', 0, 1, 'Streaming Group 1');
hilite_system('Model/DUT_FixP/Goertzel/DataValidDownsampler/DataInSW', 'user1');
annotate_port('Model/DUT_FixP/Goertzel/DataValidDownsampler/DataInSW', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/tappedDelay/tapped_delay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/tappedDelay/tapped_delay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/tappedDelay', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/tappedDelay', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/t', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2/t', 0, 1, 'Streaming Group 1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2', 'user1');
annotate_port('gm_Model/DUT_FixP/Goertzel/crp_temp_streamed2', 0, 1, 'Streaming Group 1');
