-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity deepwaveaccel is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 10;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    norm_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    in_r_TVALID : IN STD_LOGIC;
    in_r_TREADY : OUT STD_LOGIC;
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    norm_TVALID : OUT STD_LOGIC;
    norm_TREADY : IN STD_LOGIC );
end;


architecture behav of deepwaveaccel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "deepwaveaccel_deepwaveaccel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.549457,HLS_SYN_LAT=58,HLS_SYN_TPT=4,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=8595,HLS_SYN_LUT=6053,HLS_VERSION=2025_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal goer_cfg_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal goertzel_U0_ap_start : STD_LOGIC;
    signal goertzel_U0_ap_done : STD_LOGIC;
    signal goertzel_U0_ap_continue : STD_LOGIC;
    signal goertzel_U0_ap_idle : STD_LOGIC;
    signal goertzel_U0_ap_ready : STD_LOGIC;
    signal goertzel_U0_s_goertzel_din : STD_LOGIC_VECTOR (95 downto 0);
    signal goertzel_U0_s_goertzel_write : STD_LOGIC;
    signal goertzel_U0_start_out : STD_LOGIC;
    signal goertzel_U0_start_write : STD_LOGIC;
    signal goertzel_U0_in_stream_TREADY : STD_LOGIC;
    signal goertzel_U0_goer_cfg_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal goertzel_U0_goer_cfg_ce0 : STD_LOGIC;
    signal crosscor_U0_ap_start : STD_LOGIC;
    signal crosscor_U0_ap_done : STD_LOGIC;
    signal crosscor_U0_ap_continue : STD_LOGIC;
    signal crosscor_U0_ap_idle : STD_LOGIC;
    signal crosscor_U0_ap_ready : STD_LOGIC;
    signal crosscor_U0_s_goertzel_read : STD_LOGIC;
    signal crosscor_U0_out_r_TDATA : STD_LOGIC_VECTOR (95 downto 0);
    signal crosscor_U0_out_r_TVALID : STD_LOGIC;
    signal crosscor_U0_norm_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal crosscor_U0_norm_TVALID : STD_LOGIC;
    signal s_goertzel_full_n : STD_LOGIC;
    signal s_goertzel_dout : STD_LOGIC_VECTOR (95 downto 0);
    signal s_goertzel_empty_n : STD_LOGIC;
    signal s_goertzel_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_goertzel_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal start_for_crosscor_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_crosscor_U0_full_n : STD_LOGIC;
    signal start_for_crosscor_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_crosscor_U0_empty_n : STD_LOGIC;

    component deepwaveaccel_goertzel IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_goertzel_din : OUT STD_LOGIC_VECTOR (95 downto 0);
        s_goertzel_full_n : IN STD_LOGIC;
        s_goertzel_write : OUT STD_LOGIC;
        s_goertzel_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_goertzel_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TREADY : OUT STD_LOGIC;
        goer_cfg_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        goer_cfg_ce0 : OUT STD_LOGIC;
        goer_cfg_q0 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component deepwaveaccel_crosscor IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_goertzel_dout : IN STD_LOGIC_VECTOR (95 downto 0);
        s_goertzel_empty_n : IN STD_LOGIC;
        s_goertzel_read : OUT STD_LOGIC;
        s_goertzel_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_goertzel_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        norm_TREADY : IN STD_LOGIC;
        out_r_TREADY : IN STD_LOGIC;
        out_r_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
        out_r_TVALID : OUT STD_LOGIC;
        norm_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        norm_TVALID : OUT STD_LOGIC );
    end component;


    component deepwaveaccel_fifo_w96_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (95 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (95 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component deepwaveaccel_start_for_crosscor_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component deepwaveaccel_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        goer_cfg_address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        goer_cfg_ce0 : IN STD_LOGIC;
        goer_cfg_q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    CTRL_BUS_s_axi_U : component deepwaveaccel_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        goer_cfg_address0 => goertzel_U0_goer_cfg_address0,
        goer_cfg_ce0 => goertzel_U0_goer_cfg_ce0,
        goer_cfg_q0 => goer_cfg_q0);

    goertzel_U0 : component deepwaveaccel_goertzel
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => goertzel_U0_ap_start,
        start_full_n => start_for_crosscor_U0_full_n,
        ap_done => goertzel_U0_ap_done,
        ap_continue => goertzel_U0_ap_continue,
        ap_idle => goertzel_U0_ap_idle,
        ap_ready => goertzel_U0_ap_ready,
        s_goertzel_din => goertzel_U0_s_goertzel_din,
        s_goertzel_full_n => s_goertzel_full_n,
        s_goertzel_write => goertzel_U0_s_goertzel_write,
        s_goertzel_num_data_valid => s_goertzel_num_data_valid,
        s_goertzel_fifo_cap => s_goertzel_fifo_cap,
        start_out => goertzel_U0_start_out,
        start_write => goertzel_U0_start_write,
        in_stream_TDATA => in_r_TDATA,
        in_stream_TVALID => in_r_TVALID,
        in_stream_TREADY => goertzel_U0_in_stream_TREADY,
        goer_cfg_address0 => goertzel_U0_goer_cfg_address0,
        goer_cfg_ce0 => goertzel_U0_goer_cfg_ce0,
        goer_cfg_q0 => goer_cfg_q0);

    crosscor_U0 : component deepwaveaccel_crosscor
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => crosscor_U0_ap_start,
        ap_done => crosscor_U0_ap_done,
        ap_continue => crosscor_U0_ap_continue,
        ap_idle => crosscor_U0_ap_idle,
        ap_ready => crosscor_U0_ap_ready,
        s_goertzel_dout => s_goertzel_dout,
        s_goertzel_empty_n => s_goertzel_empty_n,
        s_goertzel_read => crosscor_U0_s_goertzel_read,
        s_goertzel_num_data_valid => s_goertzel_num_data_valid,
        s_goertzel_fifo_cap => s_goertzel_fifo_cap,
        norm_TREADY => norm_TREADY,
        out_r_TREADY => out_r_TREADY,
        out_r_TDATA => crosscor_U0_out_r_TDATA,
        out_r_TVALID => crosscor_U0_out_r_TVALID,
        norm_TDATA => crosscor_U0_norm_TDATA,
        norm_TVALID => crosscor_U0_norm_TVALID);

    s_goertzel_U : component deepwaveaccel_fifo_w96_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => goertzel_U0_s_goertzel_din,
        if_full_n => s_goertzel_full_n,
        if_write => goertzel_U0_s_goertzel_write,
        if_dout => s_goertzel_dout,
        if_empty_n => s_goertzel_empty_n,
        if_read => crosscor_U0_s_goertzel_read,
        if_num_data_valid => s_goertzel_num_data_valid,
        if_fifo_cap => s_goertzel_fifo_cap);

    start_for_crosscor_U0_U : component deepwaveaccel_start_for_crosscor_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_crosscor_U0_din,
        if_full_n => start_for_crosscor_U0_full_n,
        if_write => goertzel_U0_start_write,
        if_dout => start_for_crosscor_U0_dout,
        if_empty_n => start_for_crosscor_U0_empty_n,
        if_read => crosscor_U0_ap_ready);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    crosscor_U0_ap_continue <= ap_const_logic_1;
    crosscor_U0_ap_start <= start_for_crosscor_U0_empty_n;
    goertzel_U0_ap_continue <= ap_const_logic_1;
    goertzel_U0_ap_start <= ap_const_logic_1;
    in_r_TREADY <= goertzel_U0_in_stream_TREADY;
    norm_TDATA <= crosscor_U0_norm_TDATA;
    norm_TVALID <= crosscor_U0_norm_TVALID;
    out_r_TDATA <= crosscor_U0_out_r_TDATA;
    out_r_TVALID <= crosscor_U0_out_r_TVALID;
    start_for_crosscor_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
