-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity goertzel is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 10;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of goertzel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "goertzel_goertzel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.055333,HLS_SYN_LAT=9,HLS_SYN_TPT=3,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=678,HLS_SYN_LUT=821,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv64_34 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000110100";
    constant ap_const_lv64_35 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000110101";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal cfg_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal sample : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal elem : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal tmp_reg_711 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage2_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal tmp_reg_711_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_745 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_745_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage2_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_nbreadreq_fu_130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op140_write_state10 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter3_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg_iter0 : BOOLEAN := false;
    signal tmp_reg_711_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sample_load_reg_715 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln59_1_fu_284_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln59_1_reg_725 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln60_1_fu_305_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln60_1_reg_730 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln76_fu_309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_reg_740 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln79_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_745_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_749 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_state3_pp0_stage2_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal cosw_fu_393_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal cosw_reg_754 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_predicate_op139_write_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage2_iter2_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1_load_reg_764 : STD_LOGIC_VECTOR (17 downto 0);
    signal cosw_1_reg_775 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785 : STD_LOGIC_VECTOR (17 downto 0);
    signal goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785_pp0_iter1_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln71_2_reg_801 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln85_fu_528_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sinw_1_reg_822 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal sext_ln85_2_fu_570_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_9_reg_848 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_reg_853 : STD_LOGIC_VECTOR (17 downto 0);
    signal regslice_both_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_phi_mux_sample_new_0_phi_fu_186_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_new_0_phi_fu_197_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln1_fu_485_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_phi_mux_goertzel_stream_stream_complex_0_goertzel_config_s_prev_1_new_0_phi_fu_230_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln59_fu_279_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal select_ln94_fu_336_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_01001_grp2 : BOOLEAN;
    signal cfg_ce0_local : STD_LOGIC;
    signal cfg_address0_local : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln59_fu_251_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_255_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln59_fu_263_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln59_1_fu_269_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln59_1_fu_288_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln59_1_fu_295_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln59_fu_299_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln93_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln94_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln60_fu_350_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1_fu_354_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln60_1_fu_362_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln60_fu_377_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln60_fu_377_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln71_fu_397_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln2_fu_401_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln71_1_fu_417_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_8_fu_421_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal and_ln_fu_431_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln71_3_fu_447_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_6_fu_457_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_657_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln71_1_fu_472_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln71_fu_480_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of sub_ln71_fu_480_p2 : signal is "no";
    signal grp_fu_666_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln71_2_fu_500_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln71_1_fu_508_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 of sub_ln71_1_fu_508_p2 : signal is "no";
    signal sinw_fu_524_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage2_grp0 : BOOLEAN;
    signal tmp_9_fu_579_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_675_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_s_fu_588_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_684_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln85_2_fu_611_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln85_fu_618_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_693_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln85_fu_618_p2 : STD_LOGIC_VECTOR (33 downto 0);
    attribute use_dsp48 of add_ln85_fu_618_p2 : signal is "no";
    signal trunc_ln3_fu_633_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_702_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln3_fu_633_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln2_fu_623_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_1_fu_642_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_fu_657_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal shl_i_i26_i224_fu_464_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_666_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_675_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_675_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_684_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_693_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_693_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_702_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_702_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_657_ce : STD_LOGIC;
    signal grp_fu_666_ce : STD_LOGIC;
    signal grp_fu_675_ce : STD_LOGIC;
    signal grp_fu_684_ce : STD_LOGIC;
    signal grp_fu_693_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal grp_fu_702_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_U_vld_out : STD_LOGIC;
    signal mul_ln60_fu_377_p00 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_condition_800 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component goertzel_mul_13ns_14s_27_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component goertzel_mac_muladd_18s_18s_30s_34_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component goertzel_mac_mulsub_18s_18s_34ns_34_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component goertzel_mac_mulsub_18s_18s_1ns_34_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component goertzel_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        cfg_address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        cfg_ce0 : IN STD_LOGIC;
        cfg_q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component goertzel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    CTRL_BUS_s_axi_U : component goertzel_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        cfg_address0 => cfg_address0_local,
        cfg_ce0 => cfg_ce0_local,
        cfg_q0 => cfg_q0);

    mul_13ns_14s_27_1_1_U1 : component goertzel_mul_13ns_14s_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 14,
        dout_WIDTH => 27)
    port map (
        din0 => mul_ln60_fu_377_p0,
        din1 => shl_ln1_fu_354_p3,
        dout => mul_ln60_fu_377_p2);

    mac_muladd_18s_18s_30s_34_2_1_U2 : component goertzel_mac_muladd_18s_18s_30s_34_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 30,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => shl_ln2_fu_401_p3,
        din1 => sext_ln71_1_fu_417_p0,
        din2 => grp_fu_657_p2,
        ce => grp_fu_657_ce,
        dout => grp_fu_657_p3);

    mac_muladd_18s_18s_30s_34_2_1_U3 : component goertzel_mac_muladd_18s_18s_30s_34_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 30,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln71_3_fu_447_p0,
        din1 => and_ln_fu_431_p3,
        din2 => grp_fu_666_p2,
        ce => grp_fu_666_ce,
        dout => grp_fu_666_p3);

    mac_mulsub_18s_18s_34ns_34_4_1_U4 : component goertzel_mac_mulsub_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_675_p0,
        din1 => cosw_reg_754,
        din2 => grp_fu_675_p2,
        ce => grp_fu_675_ce,
        dout => grp_fu_675_p3);

    mac_mulsub_18s_18s_1ns_34_4_1_U5 : component goertzel_mac_mulsub_18s_18s_1ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 1,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sinw_fu_524_p1,
        din1 => grp_fu_684_p1,
        din2 => grp_fu_684_p2,
        ce => grp_fu_684_ce,
        dout => grp_fu_684_p3);

    mac_mulsub_18s_18s_34ns_34_4_1_U6 : component goertzel_mac_mulsub_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_693_p0,
        din1 => cosw_1_reg_775,
        din2 => grp_fu_693_p2,
        ce => grp_fu_693_ce,
        dout => grp_fu_693_p3);

    mac_mulsub_18s_18s_34ns_34_4_1_U7 : component goertzel_mac_mulsub_18s_18s_34ns_34_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        din2_WIDTH => 34,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sinw_1_reg_822,
        din1 => grp_fu_702_p1,
        din2 => grp_fu_702_p2,
        ce => grp_fu_702_ce,
        dout => grp_fu_702_p3);

    regslice_both_in_stream_U : component goertzel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);

    regslice_both_out_stream_U : component goertzel_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg_iter0 <= ap_const_boolean_0;
            else
                if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg_iter0 <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg_iter0 <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2)) then 
                        ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                if ((ap_const_boolean_1 = ap_condition_800)) then 
                    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215 <= ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                if ((ap_const_boolean_1 = ap_condition_800)) then 
                    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204 <= ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln76_reg_740 <= add_ln76_fu_309_p2;
                icmp_ln79_reg_745 <= icmp_ln79_fu_314_p2;
                icmp_ln79_reg_745_pp0_iter1_reg <= icmp_ln79_reg_745;
                icmp_ln79_reg_745_pp0_iter2_reg <= icmp_ln79_reg_745_pp0_iter1_reg;
                trunc_ln60_1_reg_730 <= trunc_ln60_1_fu_305_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                cosw_1_reg_775 <= cfg_q0(49 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                cosw_reg_754 <= cosw_fu_393_p1;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1_load_reg_764 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785_pp0_iter1_reg <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln79_fu_314_p2 = ap_const_lv1_1))) then
                elem <= select_ln94_fu_336_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev <= ap_phi_mux_goertzel_stream_stream_complex_0_goertzel_config_s_prev_1_new_0_phi_fu_230_p4;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2 <= ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_1 <= ap_phi_reg_pp0_iter1_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204;
                goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1 <= ap_phi_mux_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_new_0_phi_fu_197_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                sample <= ap_phi_mux_sample_new_0_phi_fu_186_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sample_load_reg_715 <= sample;
                tmp_reg_711 <= tmp_nbreadreq_fu_130_p3;
                    trunc_ln59_1_reg_725(2 downto 1) <= trunc_ln59_1_fu_284_p1(2 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sinw_1_reg_822 <= cfg_q0(49 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_9_reg_848 <= tmp_9_fu_579_p1(33 downto 16);
                tmp_reg_711_pp0_iter1_reg <= tmp_reg_711;
                tmp_reg_711_pp0_iter2_reg <= tmp_reg_711_pp0_iter1_reg;
                tmp_s_reg_853 <= tmp_s_fu_588_p1(33 downto 16);
                trunc_ln71_2_reg_801 <= sub_ln71_1_fu_508_p2(33 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                trunc_ln_reg_749 <= mul_ln60_fu_377_p2(26 downto 13);
            end if;
        end if;
    end process;
    trunc_ln59_1_reg_725(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln59_fu_263_p2 <= std_logic_vector(unsigned(shl_ln_fu_255_p3) + unsigned(ap_const_lv9_10));
    add_ln76_fu_309_p2 <= std_logic_vector(unsigned(sample_load_reg_715) + unsigned(ap_const_lv32_1));
    add_ln85_fu_618_p1 <= grp_fu_693_p3;
    add_ln85_fu_618_p2 <= std_logic_vector(unsigned(shl_ln85_2_fu_611_p3) + unsigned(add_ln85_fu_618_p1));
    add_ln93_fu_324_p2 <= std_logic_vector(unsigned(elem) + unsigned(ap_const_lv32_1));
    and_ln_fu_431_p3 <= (tmp_8_fu_421_p4 & ap_const_lv1_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state10_pp0_stage0_iter3_grp3, regslice_both_out_stream_U_apdone_blk)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter3_grp3))));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state10_pp0_stage0_iter3_grp3)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter3_grp3));
    end process;

        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state10_pp0_stage0_iter3_grp3, regslice_both_out_stream_U_apdone_blk)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter3_grp3))));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state10_pp0_stage0_iter3_grp3)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter3_grp3));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state9_pp0_stage2_iter2_grp2)
    begin
                ap_block_pp0_stage2_01001_grp2 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state9_pp0_stage2_iter2_grp2));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state3_pp0_stage2_iter0_grp1, ap_block_state9_pp0_stage2_iter2_grp2)
    begin
                ap_block_pp0_stage2_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state9_pp0_stage2_iter2_grp2)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1)));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_pp0_stage2_iter0_grp1)
    begin
                ap_block_pp0_stage2_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1));
    end process;


    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state9_pp0_stage2_iter2_grp2)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state9_pp0_stage2_iter2_grp2));
    end process;

        ap_block_pp0_stage2_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state3_pp0_stage2_iter0_grp1, ap_block_state9_pp0_stage2_iter2_grp2)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state9_pp0_stage2_iter2_grp2)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1)));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_grp1_assign_proc : process(ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_pp0_stage2_iter0_grp1)
    begin
                ap_block_pp0_stage2_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1));
    end process;


    ap_block_pp0_stage2_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state9_pp0_stage2_iter2_grp2)
    begin
                ap_block_pp0_stage2_subdone_grp2 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state9_pp0_stage2_iter2_grp2));
    end process;


    ap_block_state10_pp0_stage0_iter3_grp3_assign_proc : process(ap_predicate_op140_write_state10, out_stream_TREADY_int_regslice)
    begin
                ap_block_state10_pp0_stage0_iter3_grp3 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op140_write_state10 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp1_assign_proc : process(tmp_reg_711, in_stream_TVALID_int_regslice)
    begin
                ap_block_state3_pp0_stage2_iter0_grp1 <= ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (tmp_reg_711 = ap_const_lv1_1));
    end process;


    ap_block_state9_pp0_stage2_iter2_grp2_assign_proc : process(ap_predicate_op139_write_state9, out_stream_TREADY_int_regslice)
    begin
                ap_block_state9_pp0_stage2_iter2_grp2 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op139_write_state9 = ap_const_boolean_1));
    end process;


    ap_condition_800_assign_proc : process(tmp_reg_711, icmp_ln79_reg_745, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_pp0_stage2_11001_grp2)
    begin
                ap_condition_800 <= ((icmp_ln79_reg_745 = ap_const_lv1_0) and (tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_complex_0_goertzel_config_s_prev_1_new_0_phi_fu_230_p4_assign_proc : process(tmp_reg_711, icmp_ln79_reg_745, sub_ln71_1_fu_508_p2)
    begin
        if (((icmp_ln79_reg_745 = ap_const_lv1_0) and (tmp_reg_711 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_complex_0_goertzel_config_s_prev_1_new_0_phi_fu_230_p4 <= sub_ln71_1_fu_508_p2(33 downto 16);
        else 
            ap_phi_mux_goertzel_stream_stream_complex_0_goertzel_config_s_prev_1_new_0_phi_fu_230_p4 <= ap_const_lv18_0;
        end if; 
    end process;


    ap_phi_mux_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_new_0_phi_fu_197_p4_assign_proc : process(tmp_reg_711, icmp_ln79_reg_745, sub_ln71_fu_480_p2)
    begin
        if (((icmp_ln79_reg_745 = ap_const_lv1_0) and (tmp_reg_711 = ap_const_lv1_1))) then 
            ap_phi_mux_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_new_0_phi_fu_197_p4 <= sub_ln71_fu_480_p2(33 downto 16);
        else 
            ap_phi_mux_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_new_0_phi_fu_197_p4 <= ap_const_lv18_0;
        end if; 
    end process;


    ap_phi_mux_sample_new_0_phi_fu_186_p4_assign_proc : process(tmp_reg_711, icmp_ln79_reg_745, add_ln76_reg_740)
    begin
        if (((icmp_ln79_reg_745 = ap_const_lv1_0) and (tmp_reg_711 = ap_const_lv1_1))) then 
            ap_phi_mux_sample_new_0_phi_fu_186_p4 <= add_ln76_reg_740;
        else 
            ap_phi_mux_sample_new_0_phi_fu_186_p4 <= ap_const_lv32_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_0_goertzel_config_s_prev2_2_new_0_reg_215 <= ap_const_lv18_0;
    ap_phi_reg_pp0_iter0_goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_new_0_reg_204 <= ap_const_lv18_0;

    ap_predicate_op139_write_state9_assign_proc : process(tmp_reg_711_pp0_iter2_reg, icmp_ln79_reg_745_pp0_iter2_reg)
    begin
                ap_predicate_op139_write_state9 <= ((icmp_ln79_reg_745_pp0_iter2_reg = ap_const_lv1_1) and (tmp_reg_711_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op140_write_state10_assign_proc : process(tmp_reg_711_pp0_iter2_reg, icmp_ln79_reg_745_pp0_iter2_reg)
    begin
                ap_predicate_op140_write_state10 <= ((icmp_ln79_reg_745_pp0_iter2_reg = ap_const_lv1_1) and (tmp_reg_711_pp0_iter2_reg = ap_const_lv1_1));
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    cfg_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_grp3, ap_CS_fsm_pp0_stage1, zext_ln59_fu_279_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            cfg_address0_local <= ap_const_lv64_35(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            cfg_address0_local <= ap_const_lv64_34(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cfg_address0_local <= zext_ln59_fu_279_p1(6 - 1 downto 0);
        else 
            cfg_address0_local <= "XXXXXX";
        end if; 
    end process;


    cfg_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            cfg_ce0_local <= ap_const_logic_1;
        else 
            cfg_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cosw_fu_393_p1 <= cfg_q0(18 - 1 downto 0);

    grp_fu_657_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_block_pp0_stage2_11001_grp2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_657_ce <= ap_const_logic_1;
        else 
            grp_fu_657_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_657_p2 <= shl_i_i26_i224_fu_464_p1(30 - 1 downto 0);

    grp_fu_666_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_block_pp0_stage2_11001_grp2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_666_ce <= ap_const_logic_1;
        else 
            grp_fu_666_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_666_p2 <= shl_i_i26_i224_fu_464_p1(30 - 1 downto 0);

    grp_fu_675_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_675_ce <= ap_const_logic_1;
        else 
            grp_fu_675_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_675_p0 <= sext_ln85_fu_528_p1(18 - 1 downto 0);
    grp_fu_675_p2 <= (goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1_load_reg_764 & ap_const_lv16_0);

    grp_fu_684_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_684_ce <= ap_const_logic_1;
        else 
            grp_fu_684_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_684_p1 <= sext_ln85_fu_528_p1(18 - 1 downto 0);
    grp_fu_684_p2 <= ap_const_lv34_0(1 - 1 downto 0);

    grp_fu_693_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_693_ce <= ap_const_logic_1;
        else 
            grp_fu_693_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_693_p0 <= sext_ln85_2_fu_570_p1(18 - 1 downto 0);
    grp_fu_693_p2 <= (goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_load_reg_785_pp0_iter1_reg & ap_const_lv16_0);

    grp_fu_702_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_702_ce <= ap_const_logic_1;
        else 
            grp_fu_702_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_702_p1 <= sext_ln85_2_fu_570_p1(18 - 1 downto 0);
    grp_fu_702_p2 <= (tmp_s_reg_853 & ap_const_lv16_0);
    icmp_ln79_fu_314_p2 <= "1" when (add_ln76_fu_309_p2 = ap_const_lv32_C8) else "0";
    icmp_ln94_fu_330_p2 <= "1" when (add_ln93_fu_324_p2 = ap_const_lv32_30) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, tmp_reg_711, ap_block_pp0_stage2_subdone_grp1_done_reg, in_stream_TVALID_int_regslice)
    begin
        if (((tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage2, tmp_reg_711, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_11001_grp1)
    begin
        if (((tmp_reg_711 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln59_1_fu_269_p4 <= add_ln59_fu_263_p2(8 downto 3);
    lshr_ln59_fu_299_p2 <= std_logic_vector(shift_right(unsigned(cfg_q0),to_integer(unsigned('0' & zext_ln59_1_fu_295_p1(31-1 downto 0)))));
    mul_ln60_fu_377_p0 <= mul_ln60_fu_377_p00(13 - 1 downto 0);
    mul_ln60_fu_377_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln60_1_fu_362_p3),27));

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_grp2, tmp_reg_711_pp0_iter2_reg, icmp_ln79_reg_745_pp0_iter2_reg, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln79_reg_745_pp0_iter2_reg = ap_const_lv1_1) and (tmp_reg_711_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln79_reg_745_pp0_iter2_reg = ap_const_lv1_1) and (tmp_reg_711_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_642_p4),64));
    out_stream_TVALID <= regslice_both_out_stream_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_predicate_op139_write_state9, ap_block_pp0_stage2_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_op139_write_state9 = ap_const_boolean_1))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln94_fu_336_p3 <= 
        ap_const_lv32_0 when (icmp_ln94_fu_330_p2(0) = '1') else 
        add_ln93_fu_324_p2;
    sext_ln71_1_fu_417_p0 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev_1;
    sext_ln71_3_fu_447_p0 <= goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev;
        sext_ln85_2_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln71_2_reg_801),34));

        sext_ln85_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_485_p4),34));

        shl_i_i26_i224_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_457_p3),34));

    shl_ln1_fu_354_p3 <= (trunc_ln60_fu_350_p1 & ap_const_lv2_0);
    shl_ln2_fu_401_p3 <= (trunc_ln71_fu_397_p1 & ap_const_lv1_0);
    shl_ln59_1_fu_288_p3 <= (trunc_ln59_1_reg_725 & ap_const_lv3_0);
    shl_ln60_1_fu_362_p3 <= (trunc_ln60_1_reg_730 & ap_const_lv1_0);
    shl_ln71_1_fu_472_p3 <= (goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2_1 & ap_const_lv16_0);
    shl_ln71_2_fu_500_p3 <= (goertzel_stream_stream_complex_ap_fixed_0_goertzel_config_s_prev2 & ap_const_lv16_0);
    shl_ln85_2_fu_611_p3 <= (tmp_9_reg_848 & ap_const_lv16_0);
    shl_ln_fu_255_p3 <= (trunc_ln59_fu_251_p1 & ap_const_lv1_0);
    sinw_fu_524_p1 <= cfg_q0(18 - 1 downto 0);
    sub_ln71_1_fu_508_p2 <= std_logic_vector(signed(grp_fu_666_p3) - signed(shl_ln71_2_fu_500_p3));
    sub_ln71_fu_480_p2 <= std_logic_vector(signed(grp_fu_657_p3) - signed(shl_ln71_1_fu_472_p3));
    tmp_1_fu_642_p4 <= ((trunc_ln3_fu_633_p4 & ap_const_lv14_0) & trunc_ln2_fu_623_p4);
    tmp_6_fu_457_p3 <= (trunc_ln_reg_749 & ap_const_lv16_0);
    tmp_8_fu_421_p4 <= cfg_q0(48 downto 32);
    tmp_9_fu_579_p1 <= grp_fu_675_p3;
    tmp_nbreadreq_fu_130_p3 <= (0=>(in_stream_TVALID_int_regslice), others=>'-');
    tmp_s_fu_588_p1 <= grp_fu_684_p3;
    trunc_ln1_fu_485_p4 <= sub_ln71_fu_480_p2(33 downto 16);
    trunc_ln2_fu_623_p4 <= add_ln85_fu_618_p2(33 downto 16);
    trunc_ln3_fu_633_p1 <= grp_fu_702_p3;
    trunc_ln3_fu_633_p4 <= trunc_ln3_fu_633_p1(33 downto 16);
    trunc_ln59_1_fu_284_p1 <= add_ln59_fu_263_p2(3 - 1 downto 0);
    trunc_ln59_fu_251_p1 <= sample(8 - 1 downto 0);
    trunc_ln60_1_fu_305_p1 <= lshr_ln59_fu_299_p2(12 - 1 downto 0);
    trunc_ln60_fu_350_p1 <= in_stream_TDATA_int_regslice(12 - 1 downto 0);
    trunc_ln71_fu_397_p1 <= cfg_q0(17 - 1 downto 0);
    zext_ln59_1_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln59_1_fu_288_p3),64));
    zext_ln59_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln59_1_fu_269_p4),64));
end behav;
